/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module parity(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input a;
  input b;
  input c;
  input d;
  input e;
  input f;
  input g;
  input h;
  input i;
  input j;
  input k;
  input l;
  input m;
  input n;
  input o;
  input p;
  output q;
  XNOR2X1 _14_ (
    .A(n),
    .B(m),
    .Y(_00_)
  );
  XOR2X1 _15_ (
    .A(k),
    .B(l),
    .Y(_01_)
  );
  XNOR2X1 _16_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  XNOR2X1 _17_ (
    .A(p),
    .B(o),
    .Y(_03_)
  );
  XOR2X1 _18_ (
    .A(i),
    .B(j),
    .Y(_04_)
  );
  XNOR2X1 _19_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  XNOR2X1 _20_ (
    .A(_02_),
    .B(_05_),
    .Y(_06_)
  );
  XNOR2X1 _21_ (
    .A(f),
    .B(e),
    .Y(_07_)
  );
  XNOR2X1 _22_ (
    .A(c),
    .B(d),
    .Y(_08_)
  );
  XNOR2X1 _23_ (
    .A(_07_),
    .B(_08_),
    .Y(_09_)
  );
  XNOR2X1 _24_ (
    .A(h),
    .B(g),
    .Y(_10_)
  );
  XOR2X1 _25_ (
    .A(a),
    .B(b),
    .Y(_11_)
  );
  XNOR2X1 _26_ (
    .A(_10_),
    .B(_11_),
    .Y(_12_)
  );
  XNOR2X1 _27_ (
    .A(_09_),
    .B(_12_),
    .Y(_13_)
  );
  XNOR2X1 _28_ (
    .A(_06_),
    .B(_13_),
    .Y(q)
  );
endmodule
