/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module lal(a, b, c, d, e, f, g, h, j, k, l, m, n, o, p, q, r, s, t, u, v
, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0
, r0, s0, t0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  input a;
  input a0;
  input b;
  output b0;
  input c;
  output c0;
  input d;
  output d0;
  input e;
  output e0;
  input f;
  output f0;
  input g;
  output g0;
  input h;
  output h0;
  output i0;
  input j;
  output j0;
  input k;
  output k0;
  input l;
  output l0;
  input m;
  output m0;
  input n;
  output n0;
  input o;
  output o0;
  input p;
  output p0;
  input q;
  output q0;
  input r;
  output r0;
  input s;
  output s0;
  input t;
  output t0;
  input u;
  input v;
  input w;
  input x;
  input y;
  input z;
  INVX1 _045_ (
    .A(a0),
    .Y(_005_)
  );
  INVX1 _046_ (
    .A(z),
    .Y(_006_)
  );
  INVX1 _047_ (
    .A(v),
    .Y(_007_)
  );
  OR2X2 _048_ (
    .A(s),
    .B(t),
    .Y(_008_)
  );
  OAI21X1 _049_ (
    .A(u),
    .B(_008_),
    .C(_007_),
    .Y(_009_)
  );
  INVX1 _050_ (
    .A(x),
    .Y(_010_)
  );
  INVX1 _051_ (
    .A(w),
    .Y(_011_)
  );
  NOR2X1 _052_ (
    .A(_010_),
    .B(_011_),
    .Y(_012_)
  );
  AOI21X1 _053_ (
    .A(_009_),
    .B(_012_),
    .C(y),
    .Y(_013_)
  );
  OR2X2 _054_ (
    .A(_006_),
    .B(_013_),
    .Y(_014_)
  );
  AND2X2 _055_ (
    .A(_014_),
    .B(_005_),
    .Y(e0)
  );
  OAI21X1 _056_ (
    .A(_006_),
    .B(_013_),
    .C(_005_),
    .Y(j0)
  );
  INVX1 _057_ (
    .A(y),
    .Y(_015_)
  );
  AND2X2 _058_ (
    .A(s),
    .B(t),
    .Y(_016_)
  );
  AND2X2 _059_ (
    .A(_016_),
    .B(u),
    .Y(_017_)
  );
  AND2X2 _060_ (
    .A(_017_),
    .B(_007_),
    .Y(_018_)
  );
  AND2X2 _061_ (
    .A(_018_),
    .B(_011_),
    .Y(_019_)
  );
  AND2X2 _062_ (
    .A(_019_),
    .B(_010_),
    .Y(_020_)
  );
  AND2X2 _063_ (
    .A(_020_),
    .B(_015_),
    .Y(_021_)
  );
  AND2X2 _064_ (
    .A(_021_),
    .B(_006_),
    .Y(_022_)
  );
  AND2X2 _065_ (
    .A(_022_),
    .B(_005_),
    .Y(_023_)
  );
  INVX1 _066_ (
    .A(h),
    .Y(_024_)
  );
  NAND2X1 _067_ (
    .A(e),
    .B(f),
    .Y(_025_)
  );
  NAND2X1 _068_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_)
  );
  OR2X2 _069_ (
    .A(q),
    .B(_026_),
    .Y(_027_)
  );
  NAND3X1 _070_ (
    .A(_020_),
    .B(_006_),
    .C(_015_),
    .Y(_028_)
  );
  AND2X2 _071_ (
    .A(_028_),
    .B(a0),
    .Y(_029_)
  );
  OR2X2 _072_ (
    .A(_027_),
    .B(_029_),
    .Y(_030_)
  );
  OR2X2 _073_ (
    .A(_023_),
    .B(_030_),
    .Y(t0)
  );
  NOR2X1 _074_ (
    .A(_026_),
    .B(q),
    .Y(_031_)
  );
  OR2X2 _075_ (
    .A(_006_),
    .B(_021_),
    .Y(_032_)
  );
  NAND3X1 _076_ (
    .A(_031_),
    .B(_032_),
    .C(_028_),
    .Y(s0)
  );
  NAND2X1 _077_ (
    .A(_015_),
    .B(_020_),
    .Y(_033_)
  );
  OR2X2 _078_ (
    .A(_015_),
    .B(_020_),
    .Y(_034_)
  );
  NAND3X1 _079_ (
    .A(_031_),
    .B(_034_),
    .C(_033_),
    .Y(r0)
  );
  NOR2X1 _080_ (
    .A(_019_),
    .B(_010_),
    .Y(_035_)
  );
  OR2X2 _081_ (
    .A(_020_),
    .B(_027_),
    .Y(_036_)
  );
  OR2X2 _082_ (
    .A(_035_),
    .B(_036_),
    .Y(q0)
  );
  INVX1 _083_ (
    .A(_019_),
    .Y(_037_)
  );
  NAND2X1 _084_ (
    .A(_007_),
    .B(_017_),
    .Y(_038_)
  );
  NAND2X1 _085_ (
    .A(w),
    .B(_038_),
    .Y(_039_)
  );
  NAND3X1 _086_ (
    .A(_031_),
    .B(_037_),
    .C(_039_),
    .Y(p0)
  );
  OR2X2 _087_ (
    .A(_007_),
    .B(_017_),
    .Y(_040_)
  );
  NAND3X1 _088_ (
    .A(_031_),
    .B(_038_),
    .C(_040_),
    .Y(o0)
  );
  NOR2X1 _089_ (
    .A(_016_),
    .B(u),
    .Y(_041_)
  );
  NOR3X1 _090_ (
    .A(_027_),
    .B(_017_),
    .C(_041_),
    .Y(n0)
  );
  INVX1 _091_ (
    .A(_008_),
    .Y(_042_)
  );
  NOR3X1 _092_ (
    .A(_027_),
    .B(_042_),
    .C(_016_),
    .Y(m0)
  );
  NOR2X1 _093_ (
    .A(_027_),
    .B(s),
    .Y(l0)
  );
  NOR3X1 _094_ (
    .A(_025_),
    .B(q),
    .C(h),
    .Y(k0)
  );
  INVX1 _095_ (
    .A(j),
    .Y(_043_)
  );
  NAND2X1 _096_ (
    .A(g),
    .B(_043_),
    .Y(i0)
  );
  AND2X2 _097_ (
    .A(_043_),
    .B(p),
    .Y(h0)
  );
  NOR2X1 _098_ (
    .A(j),
    .B(o),
    .Y(g0)
  );
  XOR2X1 _099_ (
    .A(d),
    .B(n),
    .Y(_044_)
  );
  XOR2X1 _100_ (
    .A(a),
    .B(k),
    .Y(_000_)
  );
  XNOR2X1 _101_ (
    .A(c),
    .B(m),
    .Y(_001_)
  );
  XNOR2X1 _102_ (
    .A(b),
    .B(l),
    .Y(_002_)
  );
  NAND2X1 _103_ (
    .A(_001_),
    .B(_002_),
    .Y(_003_)
  );
  NOR3X1 _104_ (
    .A(_003_),
    .B(_044_),
    .C(_000_),
    .Y(_004_)
  );
  NOR2X1 _105_ (
    .A(_004_),
    .B(j),
    .Y(f0)
  );
  OR2X2 _106_ (
    .A(_026_),
    .B(e0),
    .Y(c0)
  );
  NOR2X1 _107_ (
    .A(_043_),
    .B(r),
    .Y(b0)
  );
  assign d0 = r;
endmodule
