/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module newapla1(\SRC1s<0> , \SRC1s<1> , \SRC1s<2> , \SRC1s<3> , \SRC1s<4> , \CPIPE1s<7> , pbusDtoINA, SRC2equal16, SRC2equalDST2, opc2load, DSTvalid, SRC1equalDST2, pbusStobusA, pSHAtobusA, pSHBtobusA, preadPSWtoA, preadCWPtoA, LoadforwtoINB1, LoadforwtoINA1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input \CPIPE1s<7> ;
  input DSTvalid;
  output LoadforwtoINA1;
  output LoadforwtoINB1;
  input SRC1equalDST2;
  input \SRC1s<0> ;
  input \SRC1s<1> ;
  input \SRC1s<2> ;
  input \SRC1s<3> ;
  input \SRC1s<4> ;
  input SRC2equal16;
  input SRC2equalDST2;
  input opc2load;
  output pSHAtobusA;
  output pSHBtobusA;
  input pbusDtoINA;
  output pbusStobusA;
  output preadCWPtoA;
  output preadPSWtoA;
  INVX1 _17_ (
    .A(\SRC1s<1> ),
    .Y(_00_)
  );
  INVX1 _18_ (
    .A(\SRC1s<3> ),
    .Y(_01_)
  );
  AND2X2 _19_ (
    .A(_01_),
    .B(\SRC1s<4> ),
    .Y(_02_)
  );
  NOR2X1 _20_ (
    .A(\SRC1s<0> ),
    .B(\SRC1s<2> ),
    .Y(_03_)
  );
  NAND3X1 _21_ (
    .A(_02_),
    .B(_00_),
    .C(_03_),
    .Y(_04_)
  );
  AND2X2 _22_ (
    .A(opc2load),
    .B(DSTvalid),
    .Y(_05_)
  );
  INVX1 _23_ (
    .A(pbusDtoINA),
    .Y(_06_)
  );
  AND2X2 _24_ (
    .A(_06_),
    .B(\CPIPE1s<7> ),
    .Y(_07_)
  );
  AND2X2 _25_ (
    .A(_07_),
    .B(SRC1equalDST2),
    .Y(_08_)
  );
  AND2X2 _26_ (
    .A(_08_),
    .B(_05_),
    .Y(_09_)
  );
  AND2X2 _27_ (
    .A(_04_),
    .B(_09_),
    .Y(LoadforwtoINA1)
  );
  INVX1 _28_ (
    .A(SRC2equal16),
    .Y(_10_)
  );
  AND2X2 _29_ (
    .A(_07_),
    .B(_10_),
    .Y(_11_)
  );
  AND2X2 _30_ (
    .A(_05_),
    .B(SRC2equalDST2),
    .Y(_12_)
  );
  AND2X2 _31_ (
    .A(_11_),
    .B(_12_),
    .Y(LoadforwtoINB1)
  );
  AND2X2 _32_ (
    .A(_02_),
    .B(\SRC1s<1> ),
    .Y(_13_)
  );
  AND2X2 _33_ (
    .A(_13_),
    .B(_07_),
    .Y(_14_)
  );
  AND2X2 _34_ (
    .A(_14_),
    .B(\SRC1s<2> ),
    .Y(pbusStobusA)
  );
  INVX1 _35_ (
    .A(\SRC1s<0> ),
    .Y(_15_)
  );
  AND2X2 _36_ (
    .A(pbusStobusA),
    .B(_15_),
    .Y(preadCWPtoA)
  );
  AND2X2 _37_ (
    .A(pbusStobusA),
    .B(\SRC1s<0> ),
    .Y(preadPSWtoA)
  );
  AND2X2 _38_ (
    .A(_14_),
    .B(_03_),
    .Y(pSHBtobusA)
  );
  NOR2X1 _39_ (
    .A(_15_),
    .B(\SRC1s<2> ),
    .Y(_16_)
  );
  AND2X2 _40_ (
    .A(_16_),
    .B(_14_),
    .Y(pSHAtobusA)
  );
endmodule
