/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module newtpla2(GStrap, trapinstr, datapagefINT, winunderflow, winoverflow, SWI, intTAGtrap, illegalopc, instrpagefINT, IOINT, TRAPreason3, TRAPreason2, TRAPreason1, TRAPreason0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  input GStrap;
  input IOINT;
  input SWI;
  output TRAPreason0;
  output TRAPreason1;
  output TRAPreason2;
  output TRAPreason3;
  input datapagefINT;
  input illegalopc;
  input instrpagefINT;
  input intTAGtrap;
  input trapinstr;
  input winoverflow;
  input winunderflow;
  INVX1 _23_ (
    .A(illegalopc),
    .Y(_00_)
  );
  INVX1 _24_ (
    .A(SWI),
    .Y(_01_)
  );
  INVX1 _25_ (
    .A(winunderflow),
    .Y(_02_)
  );
  INVX1 _26_ (
    .A(trapinstr),
    .Y(_03_)
  );
  INVX1 _27_ (
    .A(instrpagefINT),
    .Y(_04_)
  );
  AND2X2 _28_ (
    .A(_04_),
    .B(IOINT),
    .Y(_05_)
  );
  OR2X2 _29_ (
    .A(GStrap),
    .B(_05_),
    .Y(_06_)
  );
  AND2X2 _30_ (
    .A(_06_),
    .B(_03_),
    .Y(_07_)
  );
  OR2X2 _31_ (
    .A(datapagefINT),
    .B(_07_),
    .Y(_08_)
  );
  AND2X2 _32_ (
    .A(_08_),
    .B(_02_),
    .Y(_09_)
  );
  OR2X2 _33_ (
    .A(winoverflow),
    .B(_09_),
    .Y(_10_)
  );
  AND2X2 _34_ (
    .A(_10_),
    .B(_01_),
    .Y(_11_)
  );
  OR2X2 _35_ (
    .A(intTAGtrap),
    .B(_11_),
    .Y(_12_)
  );
  AND2X2 _36_ (
    .A(_12_),
    .B(_00_),
    .Y(TRAPreason0)
  );
  INVX1 _37_ (
    .A(winoverflow),
    .Y(_13_)
  );
  NAND2X1 _38_ (
    .A(_01_),
    .B(_13_),
    .Y(_14_)
  );
  NOR2X1 _39_ (
    .A(winunderflow),
    .B(datapagefINT),
    .Y(_15_)
  );
  OR2X2 _40_ (
    .A(trapinstr),
    .B(GStrap),
    .Y(_16_)
  );
  AOI21X1 _41_ (
    .A(_15_),
    .B(_16_),
    .C(_14_),
    .Y(_17_)
  );
  NOR3X1 _42_ (
    .A(_17_),
    .B(illegalopc),
    .C(intTAGtrap),
    .Y(TRAPreason1)
  );
  NOR3X1 _43_ (
    .A(_16_),
    .B(winunderflow),
    .C(datapagefINT),
    .Y(_18_)
  );
  NOR2X1 _44_ (
    .A(illegalopc),
    .B(intTAGtrap),
    .Y(_19_)
  );
  NAND3X1 _45_ (
    .A(_19_),
    .B(_01_),
    .C(_13_),
    .Y(_20_)
  );
  NOR2X1 _46_ (
    .A(_20_),
    .B(_18_),
    .Y(TRAPreason2)
  );
  INVX1 _47_ (
    .A(IOINT),
    .Y(_21_)
  );
  AOI21X1 _48_ (
    .A(_21_),
    .B(_04_),
    .C(_20_),
    .Y(_22_)
  );
  AND2X2 _49_ (
    .A(_22_),
    .B(_18_),
    .Y(TRAPreason3)
  );
endmodule
