/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module dekoder(v0, v1, v2, v3, \v4.0 , \v4.1 , \v4.2 , \v4.3 , \v4.4 , \v4.5 , \v4.6 );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  input v0;
  input v1;
  input v2;
  input v3;
  output \v4.0 ;
  output \v4.1 ;
  output \v4.2 ;
  output \v4.3 ;
  output \v4.4 ;
  output \v4.5 ;
  output \v4.6 ;
  NAND3X1 _22_ (
    .A(v1),
    .B(v3),
    .C(v2),
    .Y(_00_)
  );
  OR2X2 _23_ (
    .A(v1),
    .B(v2),
    .Y(_01_)
  );
  XOR2X1 _24_ (
    .A(v0),
    .B(_01_),
    .Y(_02_)
  );
  AND2X2 _25_ (
    .A(_00_),
    .B(_02_),
    .Y(\v4.6 )
  );
  INVX1 _26_ (
    .A(v1),
    .Y(_03_)
  );
  OAI21X1 _27_ (
    .A(v0),
    .B(_03_),
    .C(_01_),
    .Y(_04_)
  );
  INVX1 _28_ (
    .A(v3),
    .Y(_05_)
  );
  OR2X2 _29_ (
    .A(v0),
    .B(_05_),
    .Y(_06_)
  );
  NOR2X1 _30_ (
    .A(_03_),
    .B(v2),
    .Y(_07_)
  );
  OR2X2 _31_ (
    .A(_06_),
    .B(_07_),
    .Y(_08_)
  );
  AND2X2 _32_ (
    .A(_08_),
    .B(_04_),
    .Y(\v4.5 )
  );
  INVX1 _33_ (
    .A(v2),
    .Y(_09_)
  );
  NAND2X1 _34_ (
    .A(v1),
    .B(_09_),
    .Y(_10_)
  );
  AOI21X1 _35_ (
    .A(v0),
    .B(v2),
    .C(v3),
    .Y(_11_)
  );
  AND2X2 _36_ (
    .A(_10_),
    .B(_11_),
    .Y(\v4.4 )
  );
  NAND2X1 _37_ (
    .A(v0),
    .B(_01_),
    .Y(_12_)
  );
  OR2X2 _38_ (
    .A(v3),
    .B(v2),
    .Y(_13_)
  );
  NAND2X1 _39_ (
    .A(v3),
    .B(v2),
    .Y(_14_)
  );
  AND2X2 _40_ (
    .A(_14_),
    .B(v1),
    .Y(_15_)
  );
  AND2X2 _41_ (
    .A(_15_),
    .B(_13_),
    .Y(_16_)
  );
  OR2X2 _42_ (
    .A(v0),
    .B(_03_),
    .Y(_17_)
  );
  OR2X2 _43_ (
    .A(v2),
    .B(_06_),
    .Y(_18_)
  );
  AND2X2 _44_ (
    .A(_18_),
    .B(_17_),
    .Y(_19_)
  );
  OR2X2 _45_ (
    .A(_16_),
    .B(_19_),
    .Y(_20_)
  );
  AND2X2 _46_ (
    .A(_20_),
    .B(_12_),
    .Y(\v4.3 )
  );
  NAND3X1 _47_ (
    .A(_17_),
    .B(_01_),
    .C(_06_),
    .Y(\v4.2 )
  );
  AOI22X1 _48_ (
    .A(v0),
    .B(_01_),
    .C(_15_),
    .D(_13_),
    .Y(\v4.1 )
  );
  AOI21X1 _49_ (
    .A(_05_),
    .B(_09_),
    .C(v0),
    .Y(_21_)
  );
  XNOR2X1 _50_ (
    .A(_01_),
    .B(_21_),
    .Y(\v4.0 )
  );
endmodule
