/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module x2(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  input a;
  input b;
  input c;
  input d;
  input e;
  input f;
  input g;
  input h;
  input i;
  input j;
  output k;
  output l;
  output m;
  output n;
  output o;
  output p;
  output q;
  INVX1 _32_ (
    .A(g),
    .Y(_00_)
  );
  INVX1 _33_ (
    .A(h),
    .Y(_01_)
  );
  AND2X2 _34_ (
    .A(_01_),
    .B(j),
    .Y(_02_)
  );
  AND2X2 _35_ (
    .A(i),
    .B(f),
    .Y(_03_)
  );
  AND2X2 _36_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  OR2X2 _37_ (
    .A(_00_),
    .B(_04_),
    .Y(_05_)
  );
  INVX1 _38_ (
    .A(i),
    .Y(_06_)
  );
  XNOR2X1 _39_ (
    .A(h),
    .B(j),
    .Y(_07_)
  );
  AND2X2 _40_ (
    .A(_07_),
    .B(_06_),
    .Y(_08_)
  );
  NOR3X1 _41_ (
    .A(c),
    .B(b),
    .C(a),
    .Y(_09_)
  );
  AND2X2 _42_ (
    .A(_09_),
    .B(j),
    .Y(_10_)
  );
  INVX1 _43_ (
    .A(j),
    .Y(_11_)
  );
  AND2X2 _44_ (
    .A(_11_),
    .B(d),
    .Y(_12_)
  );
  AND2X2 _45_ (
    .A(e),
    .B(i),
    .Y(_13_)
  );
  AND2X2 _46_ (
    .A(_12_),
    .B(_13_),
    .Y(_14_)
  );
  OR2X2 _47_ (
    .A(_14_),
    .B(_10_),
    .Y(_15_)
  );
  AND2X2 _48_ (
    .A(_15_),
    .B(h),
    .Y(_16_)
  );
  OR2X2 _49_ (
    .A(_08_),
    .B(_16_),
    .Y(_17_)
  );
  OR2X2 _50_ (
    .A(_05_),
    .B(_17_),
    .Y(q)
  );
  INVX1 _51_ (
    .A(_08_),
    .Y(l)
  );
  NOR2X1 _52_ (
    .A(b),
    .B(a),
    .Y(_18_)
  );
  AND2X2 _53_ (
    .A(_18_),
    .B(c),
    .Y(_19_)
  );
  AND2X2 _54_ (
    .A(_19_),
    .B(_01_),
    .Y(_20_)
  );
  OR2X2 _55_ (
    .A(_11_),
    .B(_20_),
    .Y(_21_)
  );
  AND2X2 _56_ (
    .A(_21_),
    .B(_06_),
    .Y(_22_)
  );
  AND2X2 _57_ (
    .A(i),
    .B(j),
    .Y(_23_)
  );
  AND2X2 _58_ (
    .A(_19_),
    .B(_23_),
    .Y(_24_)
  );
  INVX1 _59_ (
    .A(e),
    .Y(_25_)
  );
  AND2X2 _60_ (
    .A(_12_),
    .B(_25_),
    .Y(_26_)
  );
  OR2X2 _61_ (
    .A(_26_),
    .B(_24_),
    .Y(_27_)
  );
  AND2X2 _62_ (
    .A(_27_),
    .B(h),
    .Y(_28_)
  );
  OR2X2 _63_ (
    .A(_05_),
    .B(_28_),
    .Y(_29_)
  );
  OR2X2 _64_ (
    .A(_22_),
    .B(_29_),
    .Y(p)
  );
  INVX1 _65_ (
    .A(_23_),
    .Y(_30_)
  );
  NAND3X1 _66_ (
    .A(_30_),
    .B(h),
    .C(g),
    .Y(o)
  );
  NOR2X1 _67_ (
    .A(h),
    .B(j),
    .Y(_31_)
  );
  NAND3X1 _68_ (
    .A(_09_),
    .B(i),
    .C(_31_),
    .Y(n)
  );
  NOR3X1 _69_ (
    .A(h),
    .B(i),
    .C(j),
    .Y(m)
  );
  NAND3X1 _70_ (
    .A(_11_),
    .B(h),
    .C(i),
    .Y(k)
  );
endmodule
