/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module cm150a(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u
, v);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  input a;
  input b;
  input c;
  input d;
  input e;
  input f;
  input g;
  input h;
  input i;
  input j;
  input k;
  input l;
  input m;
  input n;
  input o;
  input p;
  input q;
  input r;
  input s;
  input t;
  input u;
  output v;
  INVX1 _41_ (
    .A(t),
    .Y(_00_)
  );
  INVX1 _42_ (
    .A(f),
    .Y(_01_)
  );
  AND2X2 _43_ (
    .A(_01_),
    .B(q),
    .Y(_02_)
  );
  INVX1 _44_ (
    .A(r),
    .Y(_03_)
  );
  OAI21X1 _45_ (
    .A(q),
    .B(e),
    .C(_03_),
    .Y(_04_)
  );
  OR2X2 _46_ (
    .A(_02_),
    .B(_04_),
    .Y(_05_)
  );
  INVX1 _47_ (
    .A(h),
    .Y(_06_)
  );
  AND2X2 _48_ (
    .A(_06_),
    .B(q),
    .Y(_07_)
  );
  OAI21X1 _49_ (
    .A(q),
    .B(g),
    .C(r),
    .Y(_08_)
  );
  OR2X2 _50_ (
    .A(_08_),
    .B(_07_),
    .Y(_09_)
  );
  AND2X2 _51_ (
    .A(_09_),
    .B(s),
    .Y(_10_)
  );
  AND2X2 _52_ (
    .A(_05_),
    .B(_10_),
    .Y(_11_)
  );
  INVX1 _53_ (
    .A(b),
    .Y(_12_)
  );
  AND2X2 _54_ (
    .A(_12_),
    .B(q),
    .Y(_13_)
  );
  OAI21X1 _55_ (
    .A(q),
    .B(a),
    .C(_03_),
    .Y(_14_)
  );
  OR2X2 _56_ (
    .A(_13_),
    .B(_14_),
    .Y(_15_)
  );
  INVX1 _57_ (
    .A(s),
    .Y(_16_)
  );
  INVX1 _58_ (
    .A(d),
    .Y(_17_)
  );
  AND2X2 _59_ (
    .A(_17_),
    .B(q),
    .Y(_18_)
  );
  OAI21X1 _60_ (
    .A(q),
    .B(c),
    .C(r),
    .Y(_19_)
  );
  OR2X2 _61_ (
    .A(_19_),
    .B(_18_),
    .Y(_20_)
  );
  AND2X2 _62_ (
    .A(_20_),
    .B(_16_),
    .Y(_21_)
  );
  AND2X2 _63_ (
    .A(_15_),
    .B(_21_),
    .Y(_22_)
  );
  OR2X2 _64_ (
    .A(_11_),
    .B(_22_),
    .Y(_23_)
  );
  AND2X2 _65_ (
    .A(_23_),
    .B(_00_),
    .Y(_24_)
  );
  INVX1 _66_ (
    .A(q),
    .Y(_25_)
  );
  MUX2X1 _67_ (
    .A(o),
    .B(k),
    .S(s),
    .Y(_26_)
  );
  AND2X2 _68_ (
    .A(_26_),
    .B(_25_),
    .Y(_27_)
  );
  MUX2X1 _69_ (
    .A(p),
    .B(l),
    .S(s),
    .Y(_28_)
  );
  AND2X2 _70_ (
    .A(_28_),
    .B(q),
    .Y(_29_)
  );
  OR2X2 _71_ (
    .A(_03_),
    .B(_29_),
    .Y(_30_)
  );
  OR2X2 _72_ (
    .A(_27_),
    .B(_30_),
    .Y(_31_)
  );
  MUX2X1 _73_ (
    .A(n),
    .B(j),
    .S(s),
    .Y(_32_)
  );
  AND2X2 _74_ (
    .A(_32_),
    .B(q),
    .Y(_33_)
  );
  MUX2X1 _75_ (
    .A(m),
    .B(i),
    .S(s),
    .Y(_34_)
  );
  AND2X2 _76_ (
    .A(_34_),
    .B(_25_),
    .Y(_35_)
  );
  OR2X2 _77_ (
    .A(r),
    .B(_35_),
    .Y(_36_)
  );
  OR2X2 _78_ (
    .A(_33_),
    .B(_36_),
    .Y(_37_)
  );
  AND2X2 _79_ (
    .A(_37_),
    .B(t),
    .Y(_38_)
  );
  AND2X2 _80_ (
    .A(_38_),
    .B(_31_),
    .Y(_39_)
  );
  OR2X2 _81_ (
    .A(u),
    .B(_39_),
    .Y(_40_)
  );
  OR2X2 _82_ (
    .A(_24_),
    .B(_40_),
    .Y(v)
  );
endmodule
