/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module cm42a(a, b, c, d, e, f, g, h, i, j, k, l, m, n);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input a;
  input b;
  input c;
  input d;
  output e;
  output f;
  output g;
  output h;
  output i;
  output j;
  output k;
  output l;
  output m;
  output n;
  INVX1 _11_ (
    .A(a),
    .Y(_00_)
  );
  OR2X2 _12_ (
    .A(b),
    .B(_00_),
    .Y(_01_)
  );
  INVX1 _13_ (
    .A(d),
    .Y(_02_)
  );
  OR2X2 _14_ (
    .A(c),
    .B(_02_),
    .Y(_03_)
  );
  OR2X2 _15_ (
    .A(_01_),
    .B(_03_),
    .Y(n)
  );
  OR2X2 _16_ (
    .A(a),
    .B(b),
    .Y(_04_)
  );
  OR2X2 _17_ (
    .A(_04_),
    .B(_03_),
    .Y(m)
  );
  NAND2X1 _18_ (
    .A(a),
    .B(b),
    .Y(_05_)
  );
  INVX1 _19_ (
    .A(c),
    .Y(_06_)
  );
  OR2X2 _20_ (
    .A(d),
    .B(_06_),
    .Y(_07_)
  );
  OR2X2 _21_ (
    .A(_05_),
    .B(_07_),
    .Y(l)
  );
  INVX1 _22_ (
    .A(b),
    .Y(_08_)
  );
  OR2X2 _23_ (
    .A(a),
    .B(_08_),
    .Y(_09_)
  );
  OR2X2 _24_ (
    .A(_07_),
    .B(_09_),
    .Y(k)
  );
  OR2X2 _25_ (
    .A(_01_),
    .B(_07_),
    .Y(j)
  );
  OR2X2 _26_ (
    .A(_04_),
    .B(_07_),
    .Y(i)
  );
  OR2X2 _27_ (
    .A(d),
    .B(c),
    .Y(_10_)
  );
  OR2X2 _28_ (
    .A(_10_),
    .B(_05_),
    .Y(h)
  );
  OR2X2 _29_ (
    .A(_10_),
    .B(_09_),
    .Y(g)
  );
  OR2X2 _30_ (
    .A(_10_),
    .B(_01_),
    .Y(f)
  );
  OR2X2 _31_ (
    .A(_04_),
    .B(_10_),
    .Y(e)
  );
endmodule
