/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module cm163a(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u
);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  input a;
  input b;
  input c;
  input d;
  input e;
  input f;
  input g;
  input h;
  input i;
  input j;
  input k;
  input l;
  input m;
  input n;
  input o;
  input p;
  output q;
  output r;
  output s;
  output t;
  output u;
  NAND2X1 _27_ (
    .A(d),
    .B(p),
    .Y(_00_)
  );
  NAND3X1 _28_ (
    .A(i),
    .B(k),
    .C(o),
    .Y(_01_)
  );
  NOR2X1 _29_ (
    .A(_01_),
    .B(_00_),
    .Y(u)
  );
  INVX1 _30_ (
    .A(e),
    .Y(_02_)
  );
  NAND3X1 _31_ (
    .A(_02_),
    .B(h),
    .C(f),
    .Y(_03_)
  );
  NAND2X1 _32_ (
    .A(e),
    .B(f),
    .Y(_04_)
  );
  INVX1 _33_ (
    .A(m),
    .Y(_05_)
  );
  INVX1 _34_ (
    .A(l),
    .Y(_06_)
  );
  INVX1 _35_ (
    .A(j),
    .Y(_07_)
  );
  AND2X2 _36_ (
    .A(d),
    .B(c),
    .Y(_08_)
  );
  AND2X2 _37_ (
    .A(_07_),
    .B(_08_),
    .Y(_09_)
  );
  AND2X2 _38_ (
    .A(_09_),
    .B(_06_),
    .Y(_10_)
  );
  AND2X2 _39_ (
    .A(_10_),
    .B(_05_),
    .Y(_11_)
  );
  XOR2X1 _40_ (
    .A(n),
    .B(_11_),
    .Y(_12_)
  );
  OR2X2 _41_ (
    .A(_04_),
    .B(_12_),
    .Y(_13_)
  );
  AND2X2 _42_ (
    .A(_13_),
    .B(_03_),
    .Y(t)
  );
  NAND3X1 _43_ (
    .A(_02_),
    .B(g),
    .C(f),
    .Y(_14_)
  );
  AOI21X1 _44_ (
    .A(_06_),
    .B(_09_),
    .C(_05_),
    .Y(_15_)
  );
  OR2X2 _45_ (
    .A(_04_),
    .B(_11_),
    .Y(_16_)
  );
  OR2X2 _46_ (
    .A(_15_),
    .B(_16_),
    .Y(_17_)
  );
  AND2X2 _47_ (
    .A(_17_),
    .B(_14_),
    .Y(s)
  );
  NAND3X1 _48_ (
    .A(_02_),
    .B(b),
    .C(f),
    .Y(_18_)
  );
  NOR2X1 _49_ (
    .A(_09_),
    .B(_06_),
    .Y(_19_)
  );
  OR2X2 _50_ (
    .A(_04_),
    .B(_10_),
    .Y(_20_)
  );
  OR2X2 _51_ (
    .A(_20_),
    .B(_19_),
    .Y(_21_)
  );
  AND2X2 _52_ (
    .A(_21_),
    .B(_18_),
    .Y(r)
  );
  NAND3X1 _53_ (
    .A(_02_),
    .B(f),
    .C(a),
    .Y(_22_)
  );
  INVX1 _54_ (
    .A(_04_),
    .Y(_23_)
  );
  INVX1 _55_ (
    .A(_09_),
    .Y(_24_)
  );
  OR2X2 _56_ (
    .A(_08_),
    .B(_07_),
    .Y(_25_)
  );
  NAND3X1 _57_ (
    .A(_24_),
    .B(_23_),
    .C(_25_),
    .Y(_26_)
  );
  AND2X2 _58_ (
    .A(_26_),
    .B(_22_),
    .Y(q)
  );
endmodule
