/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module cordic(a6, a4, a3, a2, a5, v, x0, x1, x2, x3, y0, y1, y2, y3, z0, z1, z2, ex0, ex1, ex2, ey0
, ey1, ey2, d, dn);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  input a2;
  input a3;
  input a4;
  input a5;
  input a6;
  output d;
  output dn;
  input ex0;
  input ex1;
  input ex2;
  input ey0;
  input ey1;
  input ey2;
  input v;
  input x0;
  input x1;
  input x2;
  input x3;
  input y0;
  input y1;
  input y2;
  input y3;
  input z0;
  input z1;
  input z2;
  OR2X2 _38_ (
    .A(a3),
    .B(a2),
    .Y(_00_)
  );
  OR2X2 _39_ (
    .A(a6),
    .B(a5),
    .Y(_01_)
  );
  OR2X2 _40_ (
    .A(a4),
    .B(_01_),
    .Y(_02_)
  );
  OR2X2 _41_ (
    .A(_00_),
    .B(_02_),
    .Y(_03_)
  );
  AND2X2 _42_ (
    .A(_03_),
    .B(v),
    .Y(_04_)
  );
  AND2X2 _43_ (
    .A(ex2),
    .B(ex0),
    .Y(_05_)
  );
  NOR2X1 _44_ (
    .A(ex2),
    .B(ex0),
    .Y(_06_)
  );
  MUX2X1 _45_ (
    .A(_05_),
    .B(_06_),
    .S(ex1),
    .Y(_07_)
  );
  NOR2X1 _46_ (
    .A(ey1),
    .B(ey2),
    .Y(_08_)
  );
  AND2X2 _47_ (
    .A(ey1),
    .B(ey2),
    .Y(_09_)
  );
  MUX2X1 _48_ (
    .A(_09_),
    .B(_08_),
    .S(ey0),
    .Y(_10_)
  );
  OR2X2 _49_ (
    .A(_07_),
    .B(_10_),
    .Y(_11_)
  );
  XNOR2X1 _50_ (
    .A(x2),
    .B(x3),
    .Y(_12_)
  );
  XOR2X1 _51_ (
    .A(x1),
    .B(x0),
    .Y(_13_)
  );
  XNOR2X1 _52_ (
    .A(_12_),
    .B(_13_),
    .Y(_14_)
  );
  XNOR2X1 _53_ (
    .A(y2),
    .B(y3),
    .Y(_15_)
  );
  XOR2X1 _54_ (
    .A(y1),
    .B(y0),
    .Y(_16_)
  );
  XNOR2X1 _55_ (
    .A(_15_),
    .B(_16_),
    .Y(_17_)
  );
  INVX1 _56_ (
    .A(z1),
    .Y(_18_)
  );
  INVX1 _57_ (
    .A(z2),
    .Y(_19_)
  );
  AND2X2 _58_ (
    .A(_19_),
    .B(z0),
    .Y(_20_)
  );
  AND2X2 _59_ (
    .A(_20_),
    .B(_18_),
    .Y(_21_)
  );
  INVX1 _60_ (
    .A(z0),
    .Y(_22_)
  );
  AND2X2 _61_ (
    .A(_22_),
    .B(z2),
    .Y(_23_)
  );
  AND2X2 _62_ (
    .A(_23_),
    .B(z1),
    .Y(_24_)
  );
  OR2X2 _63_ (
    .A(_21_),
    .B(_24_),
    .Y(_25_)
  );
  OR2X2 _64_ (
    .A(_17_),
    .B(_25_),
    .Y(_26_)
  );
  OR2X2 _65_ (
    .A(_14_),
    .B(_26_),
    .Y(_27_)
  );
  OR2X2 _66_ (
    .A(_11_),
    .B(_27_),
    .Y(_28_)
  );
  NOR2X1 _67_ (
    .A(a4),
    .B(a2),
    .Y(_29_)
  );
  NAND3X1 _68_ (
    .A(_29_),
    .B(a6),
    .C(a3),
    .Y(_30_)
  );
  NAND2X1 _69_ (
    .A(a6),
    .B(a4),
    .Y(_31_)
  );
  OR2X2 _70_ (
    .A(_00_),
    .B(_31_),
    .Y(_32_)
  );
  AND2X2 _71_ (
    .A(_32_),
    .B(_03_),
    .Y(_33_)
  );
  AND2X2 _72_ (
    .A(_30_),
    .B(_33_),
    .Y(_34_)
  );
  AND2X2 _73_ (
    .A(_28_),
    .B(_34_),
    .Y(_35_)
  );
  OR2X2 _74_ (
    .A(_04_),
    .B(_35_),
    .Y(_36_)
  );
  AND2X2 _75_ (
    .A(_11_),
    .B(_33_),
    .Y(_37_)
  );
  OR2X2 _76_ (
    .A(_37_),
    .B(_36_),
    .Y(d)
  );
  AOI21X1 _77_ (
    .A(_34_),
    .B(_28_),
    .C(_04_),
    .Y(dn)
  );
endmodule
