/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module sct(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u
, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  input a;
  output a0;
  input b;
  output b0;
  input c;
  output c0;
  input d;
  output d0;
  input e;
  output e0;
  input f;
  output f0;
  input g;
  output g0;
  input h;
  output h0;
  input i;
  input j;
  input k;
  input l;
  input m;
  input n;
  input o;
  input p;
  input q;
  input r;
  input s;
  output t;
  output u;
  output v;
  output w;
  output x;
  output y;
  output z;
  AND2X2 _39_ (
    .A(e),
    .B(r),
    .Y(h0)
  );
  INVX1 _40_ (
    .A(q),
    .Y(_00_)
  );
  INVX1 _41_ (
    .A(d),
    .Y(_01_)
  );
  INVX1 _42_ (
    .A(c),
    .Y(_02_)
  );
  OAI21X1 _43_ (
    .A(d),
    .B(_02_),
    .C(e),
    .Y(_03_)
  );
  AOI21X1 _44_ (
    .A(_00_),
    .B(_01_),
    .C(_03_),
    .Y(f0)
  );
  INVX1 _45_ (
    .A(n),
    .Y(_04_)
  );
  INVX1 _46_ (
    .A(m),
    .Y(_05_)
  );
  INVX1 _47_ (
    .A(l),
    .Y(_06_)
  );
  INVX1 _48_ (
    .A(k),
    .Y(_07_)
  );
  INVX1 _49_ (
    .A(j),
    .Y(_08_)
  );
  AND2X2 _50_ (
    .A(h),
    .B(g),
    .Y(_09_)
  );
  AND2X2 _51_ (
    .A(_09_),
    .B(i),
    .Y(_10_)
  );
  AND2X2 _52_ (
    .A(_10_),
    .B(_08_),
    .Y(_11_)
  );
  AND2X2 _53_ (
    .A(_11_),
    .B(_07_),
    .Y(_12_)
  );
  AND2X2 _54_ (
    .A(_12_),
    .B(_06_),
    .Y(_13_)
  );
  AND2X2 _55_ (
    .A(_13_),
    .B(_05_),
    .Y(_14_)
  );
  AND2X2 _56_ (
    .A(_14_),
    .B(_04_),
    .Y(_15_)
  );
  AOI21X1 _57_ (
    .A(_01_),
    .B(c),
    .C(_00_),
    .Y(_16_)
  );
  AND2X2 _58_ (
    .A(_11_),
    .B(a),
    .Y(_17_)
  );
  OR2X2 _59_ (
    .A(_17_),
    .B(_16_),
    .Y(_18_)
  );
  OR2X2 _60_ (
    .A(_18_),
    .B(_15_),
    .Y(_19_)
  );
  INVX1 _61_ (
    .A(e),
    .Y(_20_)
  );
  INVX1 _62_ (
    .A(o),
    .Y(_21_)
  );
  AOI21X1 _63_ (
    .A(_21_),
    .B(_16_),
    .C(_20_),
    .Y(_22_)
  );
  AND2X2 _64_ (
    .A(_19_),
    .B(_22_),
    .Y(d0)
  );
  OR2X2 _65_ (
    .A(_20_),
    .B(_16_),
    .Y(_23_)
  );
  NAND3X1 _66_ (
    .A(_12_),
    .B(_05_),
    .C(_06_),
    .Y(_24_)
  );
  AND2X2 _67_ (
    .A(_24_),
    .B(n),
    .Y(_25_)
  );
  OR2X2 _68_ (
    .A(_23_),
    .B(_25_),
    .Y(_26_)
  );
  OR2X2 _69_ (
    .A(_15_),
    .B(_26_),
    .Y(c0)
  );
  AOI21X1 _70_ (
    .A(_06_),
    .B(_12_),
    .C(_05_),
    .Y(_27_)
  );
  OR2X2 _71_ (
    .A(_23_),
    .B(_27_),
    .Y(_28_)
  );
  OR2X2 _72_ (
    .A(_14_),
    .B(_28_),
    .Y(b0)
  );
  NOR2X1 _73_ (
    .A(_12_),
    .B(_06_),
    .Y(_29_)
  );
  OR2X2 _74_ (
    .A(_23_),
    .B(_29_),
    .Y(_30_)
  );
  OR2X2 _75_ (
    .A(_13_),
    .B(_30_),
    .Y(a0)
  );
  NOR2X1 _76_ (
    .A(_11_),
    .B(_07_),
    .Y(_31_)
  );
  OR2X2 _77_ (
    .A(_23_),
    .B(_31_),
    .Y(_32_)
  );
  OR2X2 _78_ (
    .A(_12_),
    .B(_32_),
    .Y(z)
  );
  NOR2X1 _79_ (
    .A(_10_),
    .B(_08_),
    .Y(_33_)
  );
  OR2X2 _80_ (
    .A(_33_),
    .B(_23_),
    .Y(_34_)
  );
  OR2X2 _81_ (
    .A(_11_),
    .B(_34_),
    .Y(y)
  );
  NOR2X1 _82_ (
    .A(_09_),
    .B(i),
    .Y(_35_)
  );
  NOR3X1 _83_ (
    .A(_23_),
    .B(_10_),
    .C(_35_),
    .Y(x)
  );
  NOR2X1 _84_ (
    .A(h),
    .B(g),
    .Y(_36_)
  );
  NOR3X1 _85_ (
    .A(_23_),
    .B(_09_),
    .C(_36_),
    .Y(w)
  );
  NOR2X1 _86_ (
    .A(_23_),
    .B(g),
    .Y(v)
  );
  INVX1 _87_ (
    .A(s),
    .Y(_37_)
  );
  NOR2X1 _88_ (
    .A(_37_),
    .B(p),
    .Y(_38_)
  );
  MUX2X1 _89_ (
    .A(e),
    .B(_38_),
    .S(f),
    .Y(u)
  );
  MUX2X1 _90_ (
    .A(c),
    .B(o),
    .S(b),
    .Y(t)
  );
  assign g0 = e;
  assign e0 = c;
endmodule
