/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module b1(a, b, c, d, e, f, g);
  wire _0_;
  wire _1_;
  wire _2_;
  input a;
  input b;
  input c;
  output d;
  output e;
  output f;
  output g;
  INVX1 _3_ (
    .A(c),
    .Y(g)
  );
  AND2X2 _4_ (
    .A(b),
    .B(a),
    .Y(_1_)
  );
  OR2X2 _5_ (
    .A(c),
    .B(_1_),
    .Y(_2_)
  );
  OAI21X1 _6_ (
    .A(b),
    .B(a),
    .C(c),
    .Y(_0_)
  );
  AND2X2 _7_ (
    .A(_0_),
    .B(_2_),
    .Y(f)
  );
  XOR2X1 _8_ (
    .A(b),
    .B(a),
    .Y(e)
  );
  assign d = c;
endmodule
