/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module newapla(\CPIPE1s<7> , \SRC1s<0> , \SRC1s<1> , \SRC1s<2> , \SRC1s<3> , \SRC1s<4> , SRC1equalDST2, DSTvalid, pbusDtoINA, SRC2equal16, SRC2equalDST2, opc2load, readRFaccessA1, readRFaccessB1, AIzero1, AIzeroforce, busDtobusAa, DSTtobusDa2, preadTBtoA, preadSWPtoA, pForwardtoINB
, preadPCtoA);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  output AIzero1;
  output AIzeroforce;
  input \CPIPE1s<7> ;
  output DSTtobusDa2;
  input DSTvalid;
  input SRC1equalDST2;
  input \SRC1s<0> ;
  input \SRC1s<1> ;
  input \SRC1s<2> ;
  input \SRC1s<3> ;
  input \SRC1s<4> ;
  input SRC2equal16;
  input SRC2equalDST2;
  output busDtobusAa;
  input opc2load;
  output pForwardtoINB;
  input pbusDtoINA;
  output preadPCtoA;
  output preadSWPtoA;
  output preadTBtoA;
  output readRFaccessA1;
  output readRFaccessB1;
  INVX1 _27_ (
    .A(\CPIPE1s<7> ),
    .Y(AIzeroforce)
  );
  INVX1 _28_ (
    .A(\SRC1s<4> ),
    .Y(_00_)
  );
  OR2X2 _29_ (
    .A(\SRC1s<3> ),
    .B(_00_),
    .Y(_01_)
  );
  OR2X2 _30_ (
    .A(pbusDtoINA),
    .B(_01_),
    .Y(_02_)
  );
  OR2X2 _31_ (
    .A(\SRC1s<2> ),
    .B(_02_),
    .Y(_03_)
  );
  INVX1 _32_ (
    .A(\SRC1s<1> ),
    .Y(_04_)
  );
  NAND3X1 _33_ (
    .A(_04_),
    .B(\CPIPE1s<7> ),
    .C(\SRC1s<0> ),
    .Y(_05_)
  );
  NOR2X1 _34_ (
    .A(_03_),
    .B(_05_),
    .Y(preadPCtoA)
  );
  INVX1 _35_ (
    .A(DSTvalid),
    .Y(_06_)
  );
  OR2X2 _36_ (
    .A(pbusDtoINA),
    .B(_06_),
    .Y(_07_)
  );
  INVX1 _37_ (
    .A(SRC2equalDST2),
    .Y(_08_)
  );
  OR2X2 _38_ (
    .A(SRC2equal16),
    .B(_08_),
    .Y(_09_)
  );
  OR2X2 _39_ (
    .A(opc2load),
    .B(AIzeroforce),
    .Y(_10_)
  );
  NOR3X1 _40_ (
    .A(_07_),
    .B(_09_),
    .C(_10_),
    .Y(pForwardtoINB)
  );
  INVX1 _41_ (
    .A(\SRC1s<2> ),
    .Y(_11_)
  );
  INVX1 _42_ (
    .A(\SRC1s<0> ),
    .Y(_12_)
  );
  NAND3X1 _43_ (
    .A(_12_),
    .B(\CPIPE1s<7> ),
    .C(_04_),
    .Y(_13_)
  );
  NOR3X1 _44_ (
    .A(_13_),
    .B(_11_),
    .C(_02_),
    .Y(preadSWPtoA)
  );
  NOR3X1 _45_ (
    .A(_05_),
    .B(_11_),
    .C(_02_),
    .Y(preadTBtoA)
  );
  INVX1 _46_ (
    .A(_09_),
    .Y(_14_)
  );
  OR2X2 _47_ (
    .A(\SRC1s<1> ),
    .B(_01_),
    .Y(_15_)
  );
  OR2X2 _48_ (
    .A(\SRC1s<2> ),
    .B(\SRC1s<0> ),
    .Y(_16_)
  );
  OR2X2 _49_ (
    .A(_16_),
    .B(_15_),
    .Y(_17_)
  );
  AND2X2 _50_ (
    .A(_17_),
    .B(SRC1equalDST2),
    .Y(_18_)
  );
  OR2X2 _51_ (
    .A(_14_),
    .B(_18_),
    .Y(_19_)
  );
  NOR2X1 _52_ (
    .A(_10_),
    .B(_06_),
    .Y(_20_)
  );
  AND2X2 _53_ (
    .A(_19_),
    .B(_20_),
    .Y(_21_)
  );
  OR2X2 _54_ (
    .A(pbusDtoINA),
    .B(_21_),
    .Y(DSTtobusDa2)
  );
  NAND2X1 _55_ (
    .A(DSTvalid),
    .B(SRC1equalDST2),
    .Y(_22_)
  );
  OAI21X1 _56_ (
    .A(opc2load),
    .B(_22_),
    .C(_15_),
    .Y(_23_)
  );
  NOR2X1 _57_ (
    .A(AIzeroforce),
    .B(pbusDtoINA),
    .Y(_24_)
  );
  AND2X2 _58_ (
    .A(_17_),
    .B(_24_),
    .Y(_25_)
  );
  AND2X2 _59_ (
    .A(_23_),
    .B(_25_),
    .Y(busDtobusAa)
  );
  OAI21X1 _60_ (
    .A(_13_),
    .B(_03_),
    .C(\CPIPE1s<7> ),
    .Y(AIzero1)
  );
  INVX1 _61_ (
    .A(_07_),
    .Y(_26_)
  );
  AOI21X1 _62_ (
    .A(_26_),
    .B(_14_),
    .C(AIzeroforce),
    .Y(readRFaccessB1)
  );
  AOI21X1 _63_ (
    .A(_26_),
    .B(_18_),
    .C(AIzeroforce),
    .Y(readRFaccessA1)
  );
endmodule
