/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module apex7(CAPSD, CAT0, CAT1, CAT2, CAT3, CAT4, CAT5, VACC, MMERR, IBT0, IBT1, IBT2, ICLR, LSD, ACCRPY, VERR_N, RATR, MARSSR, VLENESR, VSUMESR, PLUTO0
, PLUTO1, PLUTO2, PLUTO3, PLUTO4, PLUTO5, ORWD_N, OWL_N, PY, END, FBI, WATCH, OVACC, KBG_N, DEL1, COMPPAR, VST0, VST1, STAR0, STAR1, STAR2, STAR3
, BULL0, BULL1, BULL2, BULL3, BULL4, BULL5, BULL6, SDO, LSD_P, ACCRPY_P, VERR_F, RATR_P, MARSSR_P, VLENESR_P, VSUMESR_P, PLUTO0_P, PLUTO1_P, PLUTO2_P, PLUTO3_P, PLUTO4_P, PLUTO5_P
, ORWD_F, OWL_F, PY_P, END_P, FBI_P, WATCH_P, OVACC_P, KBG_F, DEL1_P, COMPPAR_P, VST0_P, VST1_P, STAR0_P, STAR1_P, STAR2_P, STAR3_P, BULL0_P, BULL1_P, BULL2_P, BULL3_P, BULL4_P
, BULL5_P, BULL6_P);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  input ACCRPY;
  output ACCRPY_P;
  input BULL0;
  output BULL0_P;
  input BULL1;
  output BULL1_P;
  input BULL2;
  output BULL2_P;
  input BULL3;
  output BULL3_P;
  input BULL4;
  output BULL4_P;
  input BULL5;
  output BULL5_P;
  input BULL6;
  output BULL6_P;
  input CAPSD;
  input CAT0;
  input CAT1;
  input CAT2;
  input CAT3;
  input CAT4;
  input CAT5;
  input COMPPAR;
  output COMPPAR_P;
  input DEL1;
  output DEL1_P;
  input END;
  output END_P;
  input FBI;
  output FBI_P;
  input IBT0;
  input IBT1;
  input IBT2;
  input ICLR;
  output KBG_F;
  input KBG_N;
  input LSD;
  output LSD_P;
  input MARSSR;
  output MARSSR_P;
  input MMERR;
  output ORWD_F;
  input ORWD_N;
  input OVACC;
  output OVACC_P;
  output OWL_F;
  input OWL_N;
  input PLUTO0;
  output PLUTO0_P;
  input PLUTO1;
  output PLUTO1_P;
  input PLUTO2;
  output PLUTO2_P;
  input PLUTO3;
  output PLUTO3_P;
  input PLUTO4;
  output PLUTO4_P;
  input PLUTO5;
  output PLUTO5_P;
  input PY;
  output PY_P;
  input RATR;
  output RATR_P;
  output SDO;
  input STAR0;
  output STAR0_P;
  input STAR1;
  output STAR1_P;
  input STAR2;
  output STAR2_P;
  input STAR3;
  output STAR3_P;
  input VACC;
  output VERR_F;
  input VERR_N;
  input VLENESR;
  output VLENESR_P;
  input VST0;
  output VST0_P;
  input VST1;
  output VST1_P;
  input VSUMESR;
  output VSUMESR_P;
  input WATCH;
  output WATCH_P;
  INVX1 _128_ (
    .A(OWL_N),
    .Y(_115_)
  );
  INVX1 _129_ (
    .A(BULL5),
    .Y(_116_)
  );
  INVX1 _130_ (
    .A(BULL4),
    .Y(_117_)
  );
  INVX1 _131_ (
    .A(BULL3),
    .Y(_118_)
  );
  INVX1 _132_ (
    .A(BULL2),
    .Y(_119_)
  );
  NAND3X1 _133_ (
    .A(BULL1),
    .B(WATCH),
    .C(BULL0),
    .Y(_120_)
  );
  OR2X2 _134_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  OR2X2 _135_ (
    .A(_118_),
    .B(_121_),
    .Y(_122_)
  );
  NOR3X1 _136_ (
    .A(_122_),
    .B(_116_),
    .C(_117_),
    .Y(_123_)
  );
  NOR2X1 _137_ (
    .A(_123_),
    .B(BULL6),
    .Y(_124_)
  );
  AND2X2 _138_ (
    .A(_123_),
    .B(BULL6),
    .Y(_125_)
  );
  NOR3X1 _139_ (
    .A(_124_),
    .B(_115_),
    .C(_125_),
    .Y(BULL6_P)
  );
  NOR2X1 _140_ (
    .A(_122_),
    .B(_117_),
    .Y(_126_)
  );
  NOR2X1 _141_ (
    .A(_126_),
    .B(BULL5),
    .Y(_127_)
  );
  NOR3X1 _142_ (
    .A(_127_),
    .B(_115_),
    .C(_123_),
    .Y(BULL5_P)
  );
  OAI21X1 _143_ (
    .A(_117_),
    .B(_122_),
    .C(OWL_N),
    .Y(_000_)
  );
  AOI21X1 _144_ (
    .A(_117_),
    .B(_122_),
    .C(_000_),
    .Y(BULL4_P)
  );
  NAND2X1 _145_ (
    .A(OWL_N),
    .B(_122_),
    .Y(_001_)
  );
  AOI21X1 _146_ (
    .A(_118_),
    .B(_121_),
    .C(_001_),
    .Y(BULL3_P)
  );
  NAND2X1 _147_ (
    .A(OWL_N),
    .B(_121_),
    .Y(_002_)
  );
  AOI21X1 _148_ (
    .A(_119_),
    .B(_120_),
    .C(_002_),
    .Y(BULL2_P)
  );
  INVX1 _149_ (
    .A(BULL1),
    .Y(_003_)
  );
  NAND2X1 _150_ (
    .A(WATCH),
    .B(BULL0),
    .Y(_004_)
  );
  NAND2X1 _151_ (
    .A(OWL_N),
    .B(_120_),
    .Y(_005_)
  );
  AOI21X1 _152_ (
    .A(_003_),
    .B(_004_),
    .C(_005_),
    .Y(BULL1_P)
  );
  INVX1 _153_ (
    .A(WATCH),
    .Y(_006_)
  );
  INVX1 _154_ (
    .A(BULL0),
    .Y(_007_)
  );
  NAND2X1 _155_ (
    .A(OWL_N),
    .B(_004_),
    .Y(_008_)
  );
  AOI21X1 _156_ (
    .A(_006_),
    .B(_007_),
    .C(_008_),
    .Y(BULL0_P)
  );
  INVX1 _157_ (
    .A(ORWD_N),
    .Y(_009_)
  );
  INVX1 _158_ (
    .A(CAT3),
    .Y(_010_)
  );
  INVX1 _159_ (
    .A(IBT1),
    .Y(_011_)
  );
  AND2X2 _160_ (
    .A(_011_),
    .B(IBT0),
    .Y(_012_)
  );
  AND2X2 _161_ (
    .A(_012_),
    .B(_010_),
    .Y(_013_)
  );
  INVX1 _162_ (
    .A(CAT5),
    .Y(_014_)
  );
  AND2X2 _163_ (
    .A(IBT0),
    .B(IBT1),
    .Y(_015_)
  );
  AND2X2 _164_ (
    .A(_014_),
    .B(_015_),
    .Y(_016_)
  );
  OR2X2 _165_ (
    .A(_016_),
    .B(_013_),
    .Y(_017_)
  );
  NOR3X1 _166_ (
    .A(IBT0),
    .B(IBT1),
    .C(CAT2),
    .Y(_018_)
  );
  INVX1 _167_ (
    .A(CAT4),
    .Y(_019_)
  );
  INVX1 _168_ (
    .A(IBT0),
    .Y(_020_)
  );
  AND2X2 _169_ (
    .A(_020_),
    .B(IBT1),
    .Y(_021_)
  );
  AND2X2 _170_ (
    .A(_021_),
    .B(_019_),
    .Y(_022_)
  );
  OR2X2 _171_ (
    .A(_018_),
    .B(_022_),
    .Y(_023_)
  );
  OR2X2 _172_ (
    .A(_017_),
    .B(_023_),
    .Y(_024_)
  );
  AND2X2 _173_ (
    .A(_024_),
    .B(IBT2),
    .Y(_025_)
  );
  NAND2X1 _174_ (
    .A(IBT0),
    .B(CAT1),
    .Y(_026_)
  );
  NAND2X1 _175_ (
    .A(CAT0),
    .B(_020_),
    .Y(_027_)
  );
  INVX1 _176_ (
    .A(IBT2),
    .Y(_028_)
  );
  AND2X2 _177_ (
    .A(_028_),
    .B(IBT1),
    .Y(_029_)
  );
  AND2X2 _178_ (
    .A(_027_),
    .B(_029_),
    .Y(_030_)
  );
  AND2X2 _179_ (
    .A(_030_),
    .B(_026_),
    .Y(_031_)
  );
  OR2X2 _180_ (
    .A(_031_),
    .B(_025_),
    .Y(_032_)
  );
  AND2X2 _181_ (
    .A(_032_),
    .B(WATCH),
    .Y(_033_)
  );
  AND2X2 _182_ (
    .A(_033_),
    .B(_009_),
    .Y(_034_)
  );
  OR2X2 _183_ (
    .A(FBI),
    .B(_034_),
    .Y(_035_)
  );
  AND2X2 _184_ (
    .A(_035_),
    .B(STAR0),
    .Y(_036_)
  );
  AND2X2 _185_ (
    .A(_036_),
    .B(STAR1),
    .Y(_037_)
  );
  AND2X2 _186_ (
    .A(_037_),
    .B(STAR2),
    .Y(_038_)
  );
  OR2X2 _187_ (
    .A(STAR3),
    .B(_038_),
    .Y(_039_)
  );
  NAND3X1 _188_ (
    .A(_037_),
    .B(STAR3),
    .C(STAR2),
    .Y(_040_)
  );
  AND2X2 _189_ (
    .A(_040_),
    .B(OWL_N),
    .Y(_041_)
  );
  AND2X2 _190_ (
    .A(_041_),
    .B(_039_),
    .Y(STAR3_P)
  );
  AOI21X1 _191_ (
    .A(STAR1),
    .B(_036_),
    .C(_115_),
    .Y(_042_)
  );
  AND2X2 _192_ (
    .A(_042_),
    .B(STAR2),
    .Y(_043_)
  );
  NAND2X1 _193_ (
    .A(STAR1),
    .B(STAR0),
    .Y(_044_)
  );
  OR2X2 _194_ (
    .A(STAR2),
    .B(_044_),
    .Y(_045_)
  );
  INVX1 _195_ (
    .A(_045_),
    .Y(_046_)
  );
  AND2X2 _196_ (
    .A(_035_),
    .B(OWL_N),
    .Y(_047_)
  );
  AND2X2 _197_ (
    .A(_047_),
    .B(_046_),
    .Y(_048_)
  );
  OR2X2 _198_ (
    .A(_048_),
    .B(_043_),
    .Y(STAR2_P)
  );
  OR2X2 _199_ (
    .A(STAR1),
    .B(_036_),
    .Y(_049_)
  );
  AND2X2 _200_ (
    .A(_042_),
    .B(_049_),
    .Y(STAR1_P)
  );
  NOR2X1 _201_ (
    .A(_035_),
    .B(STAR0),
    .Y(_050_)
  );
  NOR3X1 _202_ (
    .A(_050_),
    .B(_115_),
    .C(_036_),
    .Y(STAR0_P)
  );
  INVX1 _203_ (
    .A(FBI),
    .Y(_051_)
  );
  INVX1 _204_ (
    .A(ICLR),
    .Y(_052_)
  );
  NAND3X1 _205_ (
    .A(_051_),
    .B(VST1),
    .C(_052_),
    .Y(_053_)
  );
  NAND3X1 _206_ (
    .A(_052_),
    .B(PY),
    .C(FBI),
    .Y(_054_)
  );
  NAND2X1 _207_ (
    .A(_054_),
    .B(_053_),
    .Y(VST1_P)
  );
  NAND3X1 _208_ (
    .A(_052_),
    .B(VST1),
    .C(FBI),
    .Y(_055_)
  );
  NAND3X1 _209_ (
    .A(_051_),
    .B(VST0),
    .C(_052_),
    .Y(_056_)
  );
  NAND2X1 _210_ (
    .A(_055_),
    .B(_056_),
    .Y(VST0_P)
  );
  INVX1 _211_ (
    .A(COMPPAR),
    .Y(_057_)
  );
  NAND2X1 _212_ (
    .A(FBI),
    .B(DEL1),
    .Y(_058_)
  );
  OAI21X1 _213_ (
    .A(_057_),
    .B(_058_),
    .C(OWL_N),
    .Y(_059_)
  );
  AOI21X1 _214_ (
    .A(_057_),
    .B(_058_),
    .C(_059_),
    .Y(COMPPAR_P)
  );
  AND2X2 _215_ (
    .A(_052_),
    .B(CAPSD),
    .Y(DEL1_P)
  );
  NOR2X1 _216_ (
    .A(_115_),
    .B(_051_),
    .Y(_060_)
  );
  AND2X2 _217_ (
    .A(_060_),
    .B(_045_),
    .Y(_061_)
  );
  AOI21X1 _218_ (
    .A(_060_),
    .B(_033_),
    .C(_061_),
    .Y(_062_)
  );
  NAND2X1 _219_ (
    .A(STAR3),
    .B(_046_),
    .Y(_063_)
  );
  NOR2X1 _220_ (
    .A(CAT1),
    .B(CAT0),
    .Y(_064_)
  );
  NAND2X1 _221_ (
    .A(WATCH),
    .B(_064_),
    .Y(_065_)
  );
  NOR3X1 _222_ (
    .A(_065_),
    .B(IBT2),
    .C(_011_),
    .Y(_066_)
  );
  OR2X2 _223_ (
    .A(_066_),
    .B(_033_),
    .Y(_067_)
  );
  AND2X2 _224_ (
    .A(_067_),
    .B(_063_),
    .Y(_068_)
  );
  OR2X2 _225_ (
    .A(_068_),
    .B(_062_),
    .Y(_069_)
  );
  AND2X2 _226_ (
    .A(_069_),
    .B(KBG_N),
    .Y(_070_)
  );
  OR2X2 _227_ (
    .A(_115_),
    .B(_070_),
    .Y(KBG_F)
  );
  INVX1 _228_ (
    .A(VACC),
    .Y(_071_)
  );
  NOR2X1 _229_ (
    .A(_071_),
    .B(ICLR),
    .Y(OVACC_P)
  );
  NAND2X1 _230_ (
    .A(OVACC),
    .B(_071_),
    .Y(_072_)
  );
  AOI21X1 _231_ (
    .A(_006_),
    .B(_072_),
    .C(_115_),
    .Y(WATCH_P)
  );
  NAND3X1 _232_ (
    .A(_047_),
    .B(_033_),
    .C(_044_),
    .Y(_073_)
  );
  NAND2X1 _233_ (
    .A(OWL_N),
    .B(_034_),
    .Y(_074_)
  );
  NAND3X1 _234_ (
    .A(_073_),
    .B(_062_),
    .C(_074_),
    .Y(FBI_P)
  );
  INVX1 _235_ (
    .A(_033_),
    .Y(ORWD_F)
  );
  AND2X2 _236_ (
    .A(_062_),
    .B(_060_),
    .Y(_075_)
  );
  AND2X2 _237_ (
    .A(OWL_N),
    .B(END),
    .Y(_076_)
  );
  OR2X2 _238_ (
    .A(_076_),
    .B(_075_),
    .Y(END_P)
  );
  NAND3X1 _239_ (
    .A(_051_),
    .B(PY),
    .C(_052_),
    .Y(_077_)
  );
  OAI21X1 _240_ (
    .A(ICLR),
    .B(_058_),
    .C(_077_),
    .Y(PY_P)
  );
  NAND3X1 _241_ (
    .A(_116_),
    .B(BULL6),
    .C(BULL4),
    .Y(_078_)
  );
  NOR2X1 _242_ (
    .A(BULL3),
    .B(BULL2),
    .Y(_079_)
  );
  NAND3X1 _243_ (
    .A(_079_),
    .B(BULL1),
    .C(_007_),
    .Y(_080_)
  );
  OR2X2 _244_ (
    .A(_078_),
    .B(_080_),
    .Y(_081_)
  );
  OAI21X1 _245_ (
    .A(_006_),
    .B(_081_),
    .C(KBG_N),
    .Y(_082_)
  );
  NOR3X1 _246_ (
    .A(_082_),
    .B(ICLR),
    .C(END),
    .Y(OWL_F)
  );
  AND2X2 _247_ (
    .A(OWL_N),
    .B(PLUTO5),
    .Y(_083_)
  );
  AND2X2 _248_ (
    .A(_082_),
    .B(OWL_N),
    .Y(_084_)
  );
  OAI21X1 _249_ (
    .A(VST0),
    .B(MMERR),
    .C(COMPPAR),
    .Y(_085_)
  );
  NAND2X1 _250_ (
    .A(_076_),
    .B(_085_),
    .Y(_086_)
  );
  NAND2X1 _251_ (
    .A(VST1),
    .B(_076_),
    .Y(_087_)
  );
  NAND2X1 _252_ (
    .A(_087_),
    .B(_086_),
    .Y(_088_)
  );
  OR2X2 _253_ (
    .A(_088_),
    .B(_084_),
    .Y(_089_)
  );
  AND2X2 _254_ (
    .A(_089_),
    .B(IBT2),
    .Y(_090_)
  );
  AND2X2 _255_ (
    .A(_090_),
    .B(_015_),
    .Y(_091_)
  );
  OR2X2 _256_ (
    .A(_083_),
    .B(_091_),
    .Y(PLUTO5_P)
  );
  AND2X2 _257_ (
    .A(OWL_N),
    .B(PLUTO4),
    .Y(_092_)
  );
  AND2X2 _258_ (
    .A(_090_),
    .B(_021_),
    .Y(_093_)
  );
  OR2X2 _259_ (
    .A(_092_),
    .B(_093_),
    .Y(PLUTO4_P)
  );
  AND2X2 _260_ (
    .A(OWL_N),
    .B(PLUTO3),
    .Y(_094_)
  );
  AND2X2 _261_ (
    .A(_090_),
    .B(_012_),
    .Y(_095_)
  );
  OR2X2 _262_ (
    .A(_094_),
    .B(_095_),
    .Y(PLUTO3_P)
  );
  NAND2X1 _263_ (
    .A(_020_),
    .B(_011_),
    .Y(_096_)
  );
  NAND2X1 _264_ (
    .A(IBT2),
    .B(_089_),
    .Y(_097_)
  );
  NAND2X1 _265_ (
    .A(OWL_N),
    .B(PLUTO2),
    .Y(_098_)
  );
  OAI21X1 _266_ (
    .A(_096_),
    .B(_097_),
    .C(_098_),
    .Y(PLUTO2_P)
  );
  NAND2X1 _267_ (
    .A(OWL_N),
    .B(PLUTO1),
    .Y(_099_)
  );
  NAND2X1 _268_ (
    .A(_029_),
    .B(_089_),
    .Y(_100_)
  );
  OAI21X1 _269_ (
    .A(_020_),
    .B(_100_),
    .C(_099_),
    .Y(PLUTO1_P)
  );
  NAND2X1 _270_ (
    .A(OWL_N),
    .B(PLUTO0),
    .Y(_101_)
  );
  OAI21X1 _271_ (
    .A(IBT0),
    .B(_100_),
    .C(_101_),
    .Y(PLUTO0_P)
  );
  NAND2X1 _272_ (
    .A(OWL_N),
    .B(VSUMESR),
    .Y(_102_)
  );
  NAND2X1 _273_ (
    .A(_102_),
    .B(_087_),
    .Y(VSUMESR_P)
  );
  INVX1 _274_ (
    .A(VLENESR),
    .Y(_103_)
  );
  AOI21X1 _275_ (
    .A(KBG_N),
    .B(_103_),
    .C(_115_),
    .Y(VLENESR_P)
  );
  INVX1 _276_ (
    .A(_081_),
    .Y(_104_)
  );
  AOI21X1 _277_ (
    .A(WATCH),
    .B(_104_),
    .C(MARSSR),
    .Y(_105_)
  );
  NOR2X1 _278_ (
    .A(_105_),
    .B(_115_),
    .Y(MARSSR_P)
  );
  NAND2X1 _279_ (
    .A(OWL_N),
    .B(RATR),
    .Y(_106_)
  );
  NAND2X1 _280_ (
    .A(_106_),
    .B(_086_),
    .Y(RATR_P)
  );
  NOR2X1 _281_ (
    .A(_061_),
    .B(WATCH),
    .Y(_107_)
  );
  AND2X2 _282_ (
    .A(_069_),
    .B(_081_),
    .Y(_108_)
  );
  OR2X2 _283_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  AND2X2 _284_ (
    .A(_109_),
    .B(VERR_N),
    .Y(_110_)
  );
  OR2X2 _285_ (
    .A(_115_),
    .B(_110_),
    .Y(VERR_F)
  );
  AND2X2 _286_ (
    .A(OWL_N),
    .B(ACCRPY),
    .Y(_111_)
  );
  OR2X2 _287_ (
    .A(_111_),
    .B(_075_),
    .Y(ACCRPY_P)
  );
  AND2X2 _288_ (
    .A(_033_),
    .B(_060_),
    .Y(_112_)
  );
  AOI22X1 _289_ (
    .A(OWL_N),
    .B(LSD),
    .C(_112_),
    .D(_046_),
    .Y(_113_)
  );
  NOR2X1 _290_ (
    .A(_063_),
    .B(_051_),
    .Y(_114_)
  );
  NOR2X1 _291_ (
    .A(_113_),
    .B(_114_),
    .Y(LSD_P)
  );
  assign SDO = VST0;
endmodule
