/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module cmb(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  input a;
  input b;
  input c;
  input d;
  input e;
  input f;
  input g;
  input h;
  input i;
  input j;
  input k;
  input l;
  input m;
  input n;
  input o;
  input p;
  output q;
  output r;
  output s;
  output t;
  OR2X2 _32_ (
    .A(h),
    .B(g),
    .Y(_00_)
  );
  NOR3X1 _33_ (
    .A(_00_),
    .B(k),
    .C(p),
    .Y(_01_)
  );
  OR2X2 _34_ (
    .A(o),
    .B(n),
    .Y(_02_)
  );
  OR2X2 _35_ (
    .A(m),
    .B(l),
    .Y(_03_)
  );
  OR2X2 _36_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  OR2X2 _37_ (
    .A(j),
    .B(i),
    .Y(_05_)
  );
  OR2X2 _38_ (
    .A(e),
    .B(f),
    .Y(_06_)
  );
  NOR3X1 _39_ (
    .A(_04_),
    .B(_05_),
    .C(_06_),
    .Y(_07_)
  );
  AND2X2 _40_ (
    .A(_07_),
    .B(_01_),
    .Y(t)
  );
  INVX1 _41_ (
    .A(o),
    .Y(_08_)
  );
  NAND2X1 _42_ (
    .A(k),
    .B(l),
    .Y(_09_)
  );
  AND2X2 _43_ (
    .A(_09_),
    .B(_04_),
    .Y(_10_)
  );
  NAND2X1 _44_ (
    .A(m),
    .B(n),
    .Y(_11_)
  );
  AND2X2 _45_ (
    .A(_11_),
    .B(_02_),
    .Y(_12_)
  );
  INVX1 _46_ (
    .A(j),
    .Y(_13_)
  );
  AND2X2 _47_ (
    .A(_13_),
    .B(k),
    .Y(_14_)
  );
  OR2X2 _48_ (
    .A(_14_),
    .B(_12_),
    .Y(_15_)
  );
  OR2X2 _49_ (
    .A(_10_),
    .B(_15_),
    .Y(_16_)
  );
  NAND2X1 _50_ (
    .A(h),
    .B(i),
    .Y(_17_)
  );
  AND2X2 _51_ (
    .A(_17_),
    .B(_05_),
    .Y(_18_)
  );
  NAND2X1 _52_ (
    .A(p),
    .B(e),
    .Y(_19_)
  );
  AND2X2 _53_ (
    .A(_19_),
    .B(_06_),
    .Y(_20_)
  );
  NAND2X1 _54_ (
    .A(g),
    .B(f),
    .Y(_21_)
  );
  AND2X2 _55_ (
    .A(_21_),
    .B(_00_),
    .Y(_22_)
  );
  OR2X2 _56_ (
    .A(_20_),
    .B(_22_),
    .Y(_23_)
  );
  OR2X2 _57_ (
    .A(_18_),
    .B(_23_),
    .Y(_24_)
  );
  OR2X2 _58_ (
    .A(_16_),
    .B(_24_),
    .Y(_25_)
  );
  OR2X2 _59_ (
    .A(_08_),
    .B(_25_),
    .Y(s)
  );
  OR2X2 _60_ (
    .A(p),
    .B(_25_),
    .Y(r)
  );
  NAND2X1 _61_ (
    .A(j),
    .B(c),
    .Y(_26_)
  );
  NAND2X1 _62_ (
    .A(e),
    .B(d),
    .Y(_27_)
  );
  NOR2X1 _63_ (
    .A(_26_),
    .B(_27_),
    .Y(_28_)
  );
  NAND3X1 _64_ (
    .A(k),
    .B(l),
    .C(a),
    .Y(_29_)
  );
  NAND3X1 _65_ (
    .A(g),
    .B(f),
    .C(b),
    .Y(_30_)
  );
  NOR3X1 _66_ (
    .A(_29_),
    .B(_17_),
    .C(_30_),
    .Y(_31_)
  );
  AND2X2 _67_ (
    .A(_31_),
    .B(_28_),
    .Y(q)
  );
endmodule
