/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module newtpla(tagcompare, \tCPIPE1s<0> , \tCPIPE1s<1> , \tCPIPE1s<2> , \tCPIPE1s<3> , \tCPIPE1s<4> , \tCPIPE1s<5> , \tCPIPE1s<7> , \tbusA<31> , \tbusB<31> , \tbusB<30> , \tbusB<29> , \tbusB<28> , \tCPIPE1s<6> , \tCPIPE1s<8> , GStrap, trapinstr, TAGtrap, pov_unflow, skipCONDenable);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  output GStrap;
  output TAGtrap;
  output pov_unflow;
  output skipCONDenable;
  input \tCPIPE1s<0> ;
  input \tCPIPE1s<1> ;
  input \tCPIPE1s<2> ;
  input \tCPIPE1s<3> ;
  input \tCPIPE1s<4> ;
  input \tCPIPE1s<5> ;
  input \tCPIPE1s<6> ;
  input \tCPIPE1s<7> ;
  input \tCPIPE1s<8> ;
  input tagcompare;
  input \tbusA<31> ;
  input \tbusB<28> ;
  input \tbusB<29> ;
  input \tbusB<30> ;
  input \tbusB<31> ;
  output trapinstr;
  INVX1 _45_ (
    .A(\tCPIPE1s<7> ),
    .Y(_00_)
  );
  NOR3X1 _46_ (
    .A(\tCPIPE1s<2> ),
    .B(\tCPIPE1s<0> ),
    .C(\tCPIPE1s<1> ),
    .Y(_01_)
  );
  INVX1 _47_ (
    .A(_01_),
    .Y(_02_)
  );
  INVX1 _48_ (
    .A(\tCPIPE1s<3> ),
    .Y(_03_)
  );
  INVX1 _49_ (
    .A(\tCPIPE1s<5> ),
    .Y(_04_)
  );
  AND2X2 _50_ (
    .A(_04_),
    .B(\tCPIPE1s<4> ),
    .Y(_05_)
  );
  AND2X2 _51_ (
    .A(_05_),
    .B(_03_),
    .Y(_06_)
  );
  INVX1 _52_ (
    .A(_06_),
    .Y(_07_)
  );
  NOR3X1 _53_ (
    .A(_07_),
    .B(_00_),
    .C(_02_),
    .Y(skipCONDenable)
  );
  AND2X2 _54_ (
    .A(\tCPIPE1s<7> ),
    .B(\tCPIPE1s<6> ),
    .Y(_08_)
  );
  NAND2X1 _55_ (
    .A(\tCPIPE1s<3> ),
    .B(_08_),
    .Y(_09_)
  );
  INVX1 _56_ (
    .A(\tCPIPE1s<2> ),
    .Y(_10_)
  );
  NAND2X1 _57_ (
    .A(\tCPIPE1s<0> ),
    .B(\tCPIPE1s<1> ),
    .Y(_11_)
  );
  INVX1 _58_ (
    .A(\tCPIPE1s<4> ),
    .Y(_12_)
  );
  AND2X2 _59_ (
    .A(_12_),
    .B(\tCPIPE1s<5> ),
    .Y(_13_)
  );
  NAND3X1 _60_ (
    .A(_13_),
    .B(_10_),
    .C(_11_),
    .Y(_14_)
  );
  NOR2X1 _61_ (
    .A(_14_),
    .B(_09_),
    .Y(pov_unflow)
  );
  INVX1 _62_ (
    .A(\tbusA<31> ),
    .Y(_15_)
  );
  OR2X2 _63_ (
    .A(\tCPIPE1s<8> ),
    .B(\tbusB<31> ),
    .Y(_16_)
  );
  NAND2X1 _64_ (
    .A(_16_),
    .B(_15_),
    .Y(_17_)
  );
  INVX1 _65_ (
    .A(\tCPIPE1s<1> ),
    .Y(_18_)
  );
  AND2X2 _66_ (
    .A(_18_),
    .B(\tCPIPE1s<3> ),
    .Y(_19_)
  );
  INVX1 _67_ (
    .A(\tCPIPE1s<0> ),
    .Y(_20_)
  );
  AND2X2 _68_ (
    .A(\tCPIPE1s<2> ),
    .B(\tCPIPE1s<1> ),
    .Y(_21_)
  );
  OR2X2 _69_ (
    .A(_21_),
    .B(_20_),
    .Y(_22_)
  );
  OR2X2 _70_ (
    .A(_19_),
    .B(_22_),
    .Y(_23_)
  );
  NAND2X1 _71_ (
    .A(\tCPIPE1s<2> ),
    .B(\tCPIPE1s<3> ),
    .Y(_24_)
  );
  AND2X2 _72_ (
    .A(_13_),
    .B(_24_),
    .Y(_25_)
  );
  AND2X2 _73_ (
    .A(_25_),
    .B(_23_),
    .Y(_26_)
  );
  OR2X2 _74_ (
    .A(_06_),
    .B(_26_),
    .Y(_27_)
  );
  AND2X2 _75_ (
    .A(_27_),
    .B(_17_),
    .Y(_28_)
  );
  OR2X2 _76_ (
    .A(_16_),
    .B(_10_),
    .Y(_29_)
  );
  INVX1 _77_ (
    .A(_29_),
    .Y(_30_)
  );
  NAND2X1 _78_ (
    .A(\tCPIPE1s<0> ),
    .B(_10_),
    .Y(_31_)
  );
  AND2X2 _79_ (
    .A(_15_),
    .B(\tCPIPE1s<3> ),
    .Y(_32_)
  );
  AND2X2 _80_ (
    .A(_31_),
    .B(_32_),
    .Y(_33_)
  );
  OR2X2 _81_ (
    .A(_30_),
    .B(_33_),
    .Y(_34_)
  );
  OR2X2 _82_ (
    .A(\tbusA<31> ),
    .B(_29_),
    .Y(_35_)
  );
  AND2X2 _83_ (
    .A(_05_),
    .B(_18_),
    .Y(_36_)
  );
  AND2X2 _84_ (
    .A(_35_),
    .B(_36_),
    .Y(_37_)
  );
  AND2X2 _85_ (
    .A(_34_),
    .B(_37_),
    .Y(_38_)
  );
  OR2X2 _86_ (
    .A(_38_),
    .B(_28_),
    .Y(_39_)
  );
  AND2X2 _87_ (
    .A(_39_),
    .B(_08_),
    .Y(TAGtrap)
  );
  NOR3X1 _88_ (
    .A(_07_),
    .B(_00_),
    .C(_01_),
    .Y(trapinstr)
  );
  OR2X2 _89_ (
    .A(\tbusB<31> ),
    .B(\tbusB<30> ),
    .Y(_40_)
  );
  OR2X2 _90_ (
    .A(\tbusB<28> ),
    .B(\tbusB<29> ),
    .Y(_41_)
  );
  OAI21X1 _91_ (
    .A(_40_),
    .B(_41_),
    .C(tagcompare),
    .Y(_42_)
  );
  AOI21X1 _92_ (
    .A(_01_),
    .B(_42_),
    .C(_12_),
    .Y(_43_)
  );
  OAI21X1 _93_ (
    .A(\tbusA<31> ),
    .B(\tCPIPE1s<4> ),
    .C(_04_),
    .Y(_44_)
  );
  NOR3X1 _94_ (
    .A(_43_),
    .B(_09_),
    .C(_44_),
    .Y(GStrap)
  );
endmodule
