/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module c8(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, u, v
, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0
, r0, s0, t0, u0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  input a;
  input a0;
  input b;
  input b0;
  input c;
  input c0;
  input d;
  output d0;
  input e;
  output e0;
  input f;
  output f0;
  input g;
  output g0;
  input h;
  output h0;
  input i;
  output i0;
  input j;
  output j0;
  input k;
  output k0;
  input l;
  output l0;
  input m;
  output m0;
  input n;
  output n0;
  input o;
  output o0;
  input p;
  output p0;
  input q;
  output q0;
  input r;
  output r0;
  input s;
  output s0;
  output t0;
  input u;
  output u0;
  input v;
  input w;
  input x;
  input y;
  input z;
  INVX1 _059_ (
    .A(u),
    .Y(_011_)
  );
  OR2X2 _060_ (
    .A(x),
    .B(w),
    .Y(_012_)
  );
  NOR3X1 _061_ (
    .A(_011_),
    .B(v),
    .C(_012_),
    .Y(_013_)
  );
  OR2X2 _062_ (
    .A(z),
    .B(y),
    .Y(_014_)
  );
  NOR3X1 _063_ (
    .A(_014_),
    .B(b0),
    .C(a0),
    .Y(_015_)
  );
  AND2X2 _064_ (
    .A(_013_),
    .B(_015_),
    .Y(_016_)
  );
  OR2X2 _065_ (
    .A(r),
    .B(_016_),
    .Y(_017_)
  );
  INVX1 _066_ (
    .A(q),
    .Y(_018_)
  );
  INVX1 _067_ (
    .A(c0),
    .Y(_019_)
  );
  AOI21X1 _068_ (
    .A(r),
    .B(_019_),
    .C(_018_),
    .Y(_020_)
  );
  AND2X2 _069_ (
    .A(_017_),
    .B(_020_),
    .Y(u0)
  );
  OR2X2 _070_ (
    .A(r),
    .B(u),
    .Y(_021_)
  );
  OR2X2 _071_ (
    .A(v),
    .B(_021_),
    .Y(_022_)
  );
  OR2X2 _072_ (
    .A(_012_),
    .B(_022_),
    .Y(_023_)
  );
  OR2X2 _073_ (
    .A(_014_),
    .B(_023_),
    .Y(_024_)
  );
  OR2X2 _074_ (
    .A(a0),
    .B(_024_),
    .Y(_025_)
  );
  AND2X2 _075_ (
    .A(_025_),
    .B(b0),
    .Y(_026_)
  );
  NOR2X1 _076_ (
    .A(b0),
    .B(a0),
    .Y(_027_)
  );
  INVX1 _077_ (
    .A(_014_),
    .Y(_028_)
  );
  NOR3X1 _078_ (
    .A(_012_),
    .B(v),
    .C(_021_),
    .Y(_029_)
  );
  AND2X2 _079_ (
    .A(_029_),
    .B(_028_),
    .Y(_030_)
  );
  AND2X2 _080_ (
    .A(_030_),
    .B(_027_),
    .Y(_031_)
  );
  OR2X2 _081_ (
    .A(_018_),
    .B(_031_),
    .Y(_032_)
  );
  OR2X2 _082_ (
    .A(_026_),
    .B(_032_),
    .Y(_033_)
  );
  NAND2X1 _083_ (
    .A(s),
    .B(h),
    .Y(_034_)
  );
  INVX1 _084_ (
    .A(s),
    .Y(_035_)
  );
  NAND2X1 _085_ (
    .A(p),
    .B(_035_),
    .Y(_036_)
  );
  NAND3X1 _086_ (
    .A(_036_),
    .B(_018_),
    .C(_034_),
    .Y(_037_)
  );
  AND2X2 _087_ (
    .A(_033_),
    .B(_037_),
    .Y(t0)
  );
  XOR2X1 _088_ (
    .A(a0),
    .B(_024_),
    .Y(_038_)
  );
  OR2X2 _089_ (
    .A(g),
    .B(_035_),
    .Y(_039_)
  );
  OR2X2 _090_ (
    .A(s),
    .B(o),
    .Y(_040_)
  );
  NAND3X1 _091_ (
    .A(_039_),
    .B(_018_),
    .C(_040_),
    .Y(_041_)
  );
  OAI21X1 _092_ (
    .A(_018_),
    .B(_038_),
    .C(_041_),
    .Y(s0)
  );
  OR2X2 _093_ (
    .A(y),
    .B(_023_),
    .Y(_042_)
  );
  AND2X2 _094_ (
    .A(_042_),
    .B(z),
    .Y(_043_)
  );
  OR2X2 _095_ (
    .A(_030_),
    .B(_043_),
    .Y(_044_)
  );
  AND2X2 _096_ (
    .A(_044_),
    .B(q),
    .Y(_045_)
  );
  INVX1 _097_ (
    .A(f),
    .Y(_046_)
  );
  OAI21X1 _098_ (
    .A(s),
    .B(n),
    .C(_018_),
    .Y(_047_)
  );
  AOI21X1 _099_ (
    .A(s),
    .B(_046_),
    .C(_047_),
    .Y(_048_)
  );
  OR2X2 _100_ (
    .A(_045_),
    .B(_048_),
    .Y(r0)
  );
  XOR2X1 _101_ (
    .A(y),
    .B(_023_),
    .Y(_049_)
  );
  OR2X2 _102_ (
    .A(e),
    .B(_035_),
    .Y(_050_)
  );
  OR2X2 _103_ (
    .A(s),
    .B(m),
    .Y(_051_)
  );
  NAND3X1 _104_ (
    .A(_050_),
    .B(_018_),
    .C(_051_),
    .Y(_052_)
  );
  OAI21X1 _105_ (
    .A(_018_),
    .B(_049_),
    .C(_052_),
    .Y(q0)
  );
  OAI21X1 _106_ (
    .A(w),
    .B(_022_),
    .C(x),
    .Y(_053_)
  );
  AOI21X1 _107_ (
    .A(_023_),
    .B(_053_),
    .C(_018_),
    .Y(_054_)
  );
  INVX1 _108_ (
    .A(d),
    .Y(_055_)
  );
  OAI21X1 _109_ (
    .A(s),
    .B(l),
    .C(_018_),
    .Y(_056_)
  );
  AOI21X1 _110_ (
    .A(s),
    .B(_055_),
    .C(_056_),
    .Y(_057_)
  );
  OR2X2 _111_ (
    .A(_057_),
    .B(_054_),
    .Y(p0)
  );
  XOR2X1 _112_ (
    .A(w),
    .B(_022_),
    .Y(_058_)
  );
  OR2X2 _113_ (
    .A(_018_),
    .B(_058_),
    .Y(_000_)
  );
  NOR2X1 _114_ (
    .A(_035_),
    .B(c),
    .Y(_001_)
  );
  OAI21X1 _115_ (
    .A(s),
    .B(k),
    .C(_018_),
    .Y(_002_)
  );
  OAI21X1 _116_ (
    .A(_001_),
    .B(_002_),
    .C(_000_),
    .Y(o0)
  );
  NAND2X1 _117_ (
    .A(s),
    .B(b),
    .Y(_003_)
  );
  AOI21X1 _118_ (
    .A(j),
    .B(_035_),
    .C(q),
    .Y(_004_)
  );
  AOI21X1 _119_ (
    .A(v),
    .B(_021_),
    .C(_018_),
    .Y(_005_)
  );
  AOI22X1 _120_ (
    .A(_003_),
    .B(_004_),
    .C(_022_),
    .D(_005_),
    .Y(n0)
  );
  NAND2X1 _121_ (
    .A(r),
    .B(u),
    .Y(_006_)
  );
  AOI21X1 _122_ (
    .A(_021_),
    .B(_006_),
    .C(_018_),
    .Y(_007_)
  );
  INVX1 _123_ (
    .A(a),
    .Y(_008_)
  );
  OAI21X1 _124_ (
    .A(s),
    .B(i),
    .C(_018_),
    .Y(_009_)
  );
  AOI21X1 _125_ (
    .A(s),
    .B(_008_),
    .C(_009_),
    .Y(_010_)
  );
  OR2X2 _126_ (
    .A(_007_),
    .B(_010_),
    .Y(m0)
  );
  MUX2X1 _127_ (
    .A(p),
    .B(b0),
    .S(c0),
    .Y(k0)
  );
  MUX2X1 _128_ (
    .A(o),
    .B(a0),
    .S(c0),
    .Y(j0)
  );
  MUX2X1 _129_ (
    .A(n),
    .B(z),
    .S(c0),
    .Y(i0)
  );
  MUX2X1 _130_ (
    .A(m),
    .B(y),
    .S(c0),
    .Y(h0)
  );
  MUX2X1 _131_ (
    .A(l),
    .B(x),
    .S(c0),
    .Y(g0)
  );
  MUX2X1 _132_ (
    .A(k),
    .B(w),
    .S(c0),
    .Y(f0)
  );
  MUX2X1 _133_ (
    .A(j),
    .B(v),
    .S(c0),
    .Y(e0)
  );
  MUX2X1 _134_ (
    .A(i),
    .B(u),
    .S(c0),
    .Y(d0)
  );
  assign l0 = c0;
endmodule
