/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module t(\1GAT(0) , \2GAT(1) , \3GAT(2) , \6GAT(3) , \7GAT(4) , \22GAT(10) , \23GAT(9) );
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input \1GAT(0) ;
  output \22GAT(10) ;
  output \23GAT(9) ;
  input \2GAT(1) ;
  input \3GAT(2) ;
  input \6GAT(3) ;
  input \7GAT(4) ;
  NAND2X1 _4_ (
    .A(\3GAT(2) ),
    .B(\6GAT(3) ),
    .Y(_2_)
  );
  AND2X2 _5_ (
    .A(_2_),
    .B(\2GAT(1) ),
    .Y(_3_)
  );
  AND2X2 _6_ (
    .A(_2_),
    .B(\7GAT(4) ),
    .Y(_0_)
  );
  OR2X2 _7_ (
    .A(_3_),
    .B(_0_),
    .Y(\23GAT(9) )
  );
  AND2X2 _8_ (
    .A(\1GAT(0) ),
    .B(\3GAT(2) ),
    .Y(_1_)
  );
  OR2X2 _9_ (
    .A(_1_),
    .B(_3_),
    .Y(\22GAT(10) )
  );
endmodule
