/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module ryy6(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, \v16.0 );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input v0;
  input v1;
  input v10;
  input v11;
  input v12;
  input v13;
  input v14;
  input v15;
  output \v16.0 ;
  input v2;
  input v3;
  input v4;
  input v5;
  input v6;
  input v7;
  input v8;
  input v9;
  INVX1 _14_ (
    .A(v2),
    .Y(_00_)
  );
  INVX1 _15_ (
    .A(v1),
    .Y(_01_)
  );
  INVX1 _16_ (
    .A(v9),
    .Y(_02_)
  );
  AOI22X1 _17_ (
    .A(v7),
    .B(v8),
    .C(v10),
    .D(v11),
    .Y(_03_)
  );
  OR2X2 _18_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  AND2X2 _19_ (
    .A(_04_),
    .B(_01_),
    .Y(_05_)
  );
  OR2X2 _20_ (
    .A(_00_),
    .B(_05_),
    .Y(_06_)
  );
  NAND2X1 _21_ (
    .A(v12),
    .B(v13),
    .Y(_07_)
  );
  NAND2X1 _22_ (
    .A(v14),
    .B(v15),
    .Y(_08_)
  );
  OR2X2 _23_ (
    .A(_07_),
    .B(_08_),
    .Y(_09_)
  );
  NAND2X1 _24_ (
    .A(v3),
    .B(v4),
    .Y(_10_)
  );
  AOI22X1 _25_ (
    .A(v5),
    .B(v6),
    .C(v0),
    .D(v1),
    .Y(_11_)
  );
  AND2X2 _26_ (
    .A(_11_),
    .B(_10_),
    .Y(_12_)
  );
  AND2X2 _27_ (
    .A(_12_),
    .B(_09_),
    .Y(_13_)
  );
  AND2X2 _28_ (
    .A(_06_),
    .B(_13_),
    .Y(\v16.0 )
  );
endmodule
