/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module z4ml(\1 , \2 , \3 , \4 , \5 , \6 , \7 , \24 , \25 , \26 , \27 );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  input \1 ;
  input \2 ;
  output \24 ;
  output \25 ;
  output \26 ;
  output \27 ;
  input \3 ;
  input \4 ;
  input \5 ;
  input \6 ;
  input \7 ;
  OR2X2 _13_ (
    .A(\7 ),
    .B(\4 ),
    .Y(_00_)
  );
  NOR2X1 _14_ (
    .A(_00_),
    .B(\1 ),
    .Y(_01_)
  );
  AND2X2 _15_ (
    .A(\7 ),
    .B(\4 ),
    .Y(_02_)
  );
  AND2X2 _16_ (
    .A(_00_),
    .B(\1 ),
    .Y(_03_)
  );
  OR2X2 _17_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  NAND3X1 _18_ (
    .A(\1 ),
    .B(\7 ),
    .C(\4 ),
    .Y(_05_)
  );
  AOI21X1 _19_ (
    .A(_04_),
    .B(_05_),
    .C(_01_),
    .Y(\27 )
  );
  XOR2X1 _20_ (
    .A(\6 ),
    .B(\3 ),
    .Y(_06_)
  );
  XOR2X1 _21_ (
    .A(_06_),
    .B(_04_),
    .Y(\26 )
  );
  XNOR2X1 _22_ (
    .A(\2 ),
    .B(\5 ),
    .Y(_07_)
  );
  AND2X2 _23_ (
    .A(\6 ),
    .B(\3 ),
    .Y(_08_)
  );
  AND2X2 _24_ (
    .A(_04_),
    .B(_06_),
    .Y(_09_)
  );
  OR2X2 _25_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  XNOR2X1 _26_ (
    .A(_07_),
    .B(_10_),
    .Y(\25 )
  );
  OR2X2 _27_ (
    .A(\2 ),
    .B(\5 ),
    .Y(_11_)
  );
  OR2X2 _28_ (
    .A(_07_),
    .B(_10_),
    .Y(_12_)
  );
  AND2X2 _29_ (
    .A(_12_),
    .B(_11_),
    .Y(\24 )
  );
endmodule
