/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module newtpla1(\CPIPE1s<6> , \CPIPE1s<0> , \CPIPE1s<1> , \CPIPE1s<2> , \CPIPE1s<3> , \CPIPE1s<4> , \CPIPE1s<5> , \CPIPE1s<7> , \AIprocessed<31> , \AIprocessed<30> , shiftAbus31, shiftAbus30);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  input \AIprocessed<30> ;
  input \AIprocessed<31> ;
  input \CPIPE1s<0> ;
  input \CPIPE1s<1> ;
  input \CPIPE1s<2> ;
  input \CPIPE1s<3> ;
  input \CPIPE1s<4> ;
  input \CPIPE1s<5> ;
  input \CPIPE1s<6> ;
  input \CPIPE1s<7> ;
  output shiftAbus30;
  output shiftAbus31;
  NOR2X1 _12_ (
    .A(\CPIPE1s<2> ),
    .B(\CPIPE1s<0> ),
    .Y(_00_)
  );
  NOR2X1 _13_ (
    .A(\CPIPE1s<4> ),
    .B(\CPIPE1s<3> ),
    .Y(_01_)
  );
  AND2X2 _14_ (
    .A(\CPIPE1s<5> ),
    .B(\CPIPE1s<7> ),
    .Y(_02_)
  );
  AND2X2 _15_ (
    .A(_01_),
    .B(_02_),
    .Y(_03_)
  );
  AND2X2 _16_ (
    .A(_03_),
    .B(_00_),
    .Y(_04_)
  );
  INVX1 _17_ (
    .A(\CPIPE1s<6> ),
    .Y(_05_)
  );
  AND2X2 _18_ (
    .A(\CPIPE1s<1> ),
    .B(\AIprocessed<30> ),
    .Y(_06_)
  );
  OR2X2 _19_ (
    .A(_06_),
    .B(_05_),
    .Y(_07_)
  );
  OR2X2 _20_ (
    .A(\AIprocessed<31> ),
    .B(\CPIPE1s<6> ),
    .Y(_08_)
  );
  AND2X2 _21_ (
    .A(_07_),
    .B(_08_),
    .Y(_09_)
  );
  AND2X2 _22_ (
    .A(_04_),
    .B(_09_),
    .Y(shiftAbus30)
  );
  OR2X2 _23_ (
    .A(\CPIPE1s<6> ),
    .B(\CPIPE1s<1> ),
    .Y(_10_)
  );
  AND2X2 _24_ (
    .A(_10_),
    .B(\AIprocessed<31> ),
    .Y(_11_)
  );
  AND2X2 _25_ (
    .A(_04_),
    .B(_11_),
    .Y(shiftAbus31)
  );
endmodule
