/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module newill(\CPIPE1s<9> , \CPIPE1s<0> , \CPIPE1s<1> , \CPIPE1s<2> , \CPIPE1s<3> , \CPIPE1s<4> , \CPIPE1s<5> , \CPIPE1s<7> , pillegalopc);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  input \CPIPE1s<0> ;
  input \CPIPE1s<1> ;
  input \CPIPE1s<2> ;
  input \CPIPE1s<3> ;
  input \CPIPE1s<4> ;
  input \CPIPE1s<5> ;
  input \CPIPE1s<7> ;
  input \CPIPE1s<9> ;
  output pillegalopc;
  INVX1 _22_ (
    .A(\CPIPE1s<2> ),
    .Y(_00_)
  );
  NAND2X1 _23_ (
    .A(\CPIPE1s<5> ),
    .B(\CPIPE1s<1> ),
    .Y(_01_)
  );
  OR2X2 _24_ (
    .A(\CPIPE1s<3> ),
    .B(_01_),
    .Y(_02_)
  );
  OR2X2 _25_ (
    .A(\CPIPE1s<5> ),
    .B(\CPIPE1s<1> ),
    .Y(_03_)
  );
  AND2X2 _26_ (
    .A(_03_),
    .B(\CPIPE1s<0> ),
    .Y(_04_)
  );
  AND2X2 _27_ (
    .A(_02_),
    .B(_04_),
    .Y(_05_)
  );
  OR2X2 _28_ (
    .A(_00_),
    .B(_05_),
    .Y(_06_)
  );
  AND2X2 _29_ (
    .A(\CPIPE1s<5> ),
    .B(\CPIPE1s<2> ),
    .Y(_07_)
  );
  AND2X2 _30_ (
    .A(\CPIPE1s<5> ),
    .B(\CPIPE1s<1> ),
    .Y(_08_)
  );
  INVX1 _31_ (
    .A(\CPIPE1s<3> ),
    .Y(_09_)
  );
  OR2X2 _32_ (
    .A(\CPIPE1s<4> ),
    .B(_09_),
    .Y(_10_)
  );
  OR2X2 _33_ (
    .A(_08_),
    .B(_10_),
    .Y(_11_)
  );
  OR2X2 _34_ (
    .A(_07_),
    .B(_11_),
    .Y(_12_)
  );
  INVX1 _35_ (
    .A(\CPIPE1s<0> ),
    .Y(_13_)
  );
  OAI21X1 _36_ (
    .A(\CPIPE1s<4> ),
    .B(_13_),
    .C(\CPIPE1s<5> ),
    .Y(_14_)
  );
  INVX1 _37_ (
    .A(\CPIPE1s<4> ),
    .Y(_15_)
  );
  AND2X2 _38_ (
    .A(\CPIPE1s<0> ),
    .B(\CPIPE1s<3> ),
    .Y(_16_)
  );
  OR2X2 _39_ (
    .A(_16_),
    .B(_15_),
    .Y(_17_)
  );
  AND2X2 _40_ (
    .A(_17_),
    .B(\CPIPE1s<7> ),
    .Y(_18_)
  );
  AND2X2 _41_ (
    .A(_14_),
    .B(_18_),
    .Y(_19_)
  );
  AND2X2 _42_ (
    .A(_19_),
    .B(_12_),
    .Y(_20_)
  );
  AND2X2 _43_ (
    .A(_20_),
    .B(_06_),
    .Y(_21_)
  );
  OR2X2 _44_ (
    .A(\CPIPE1s<9> ),
    .B(_21_),
    .Y(pillegalopc)
  );
endmodule
