/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module con1(f, b, c, d, a, h, g, f0, f1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  input a;
  input b;
  input c;
  input d;
  input f;
  output f0;
  output f1;
  input g;
  input h;
  INVX1 _18_ (
    .A(f),
    .Y(_00_)
  );
  AND2X2 _19_ (
    .A(a),
    .B(d),
    .Y(_01_)
  );
  AND2X2 _20_ (
    .A(a),
    .B(b),
    .Y(_02_)
  );
  NOR3X1 _21_ (
    .A(_00_),
    .B(_01_),
    .C(_02_),
    .Y(_03_)
  );
  INVX1 _22_ (
    .A(g),
    .Y(_04_)
  );
  OR2X2 _23_ (
    .A(_02_),
    .B(_04_),
    .Y(_05_)
  );
  AND2X2 _24_ (
    .A(_05_),
    .B(_00_),
    .Y(_06_)
  );
  NOR2X1 _25_ (
    .A(a),
    .B(b),
    .Y(_07_)
  );
  OR2X2 _26_ (
    .A(_07_),
    .B(_06_),
    .Y(_08_)
  );
  OR2X2 _27_ (
    .A(_03_),
    .B(_08_),
    .Y(f1)
  );
  INVX1 _28_ (
    .A(b),
    .Y(_09_)
  );
  OR2X2 _29_ (
    .A(c),
    .B(_09_),
    .Y(_10_)
  );
  INVX1 _30_ (
    .A(c),
    .Y(_11_)
  );
  OR2X2 _31_ (
    .A(f),
    .B(_11_),
    .Y(_12_)
  );
  AND2X2 _32_ (
    .A(_12_),
    .B(d),
    .Y(_13_)
  );
  AND2X2 _33_ (
    .A(_13_),
    .B(_10_),
    .Y(_14_)
  );
  AND2X2 _34_ (
    .A(_00_),
    .B(h),
    .Y(_15_)
  );
  OR2X2 _35_ (
    .A(a),
    .B(_15_),
    .Y(_16_)
  );
  AND2X2 _36_ (
    .A(_16_),
    .B(b),
    .Y(_17_)
  );
  OR2X2 _37_ (
    .A(_14_),
    .B(_17_),
    .Y(f0)
  );
endmodule
