/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module decod(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u
);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  input a;
  input b;
  input c;
  input d;
  input e;
  output f;
  output g;
  output h;
  output i;
  output j;
  output k;
  output l;
  output m;
  output n;
  output o;
  output p;
  output q;
  output r;
  output s;
  output t;
  output u;
  NOR3X1 _18_ (
    .A(b),
    .B(d),
    .C(c),
    .Y(_00_)
  );
  INVX1 _19_ (
    .A(a),
    .Y(_01_)
  );
  AND2X2 _20_ (
    .A(_01_),
    .B(e),
    .Y(_02_)
  );
  AND2X2 _21_ (
    .A(_00_),
    .B(_02_),
    .Y(u)
  );
  INVX1 _22_ (
    .A(b),
    .Y(_03_)
  );
  INVX1 _23_ (
    .A(c),
    .Y(_04_)
  );
  AND2X2 _24_ (
    .A(_04_),
    .B(d),
    .Y(_05_)
  );
  AND2X2 _25_ (
    .A(_05_),
    .B(_03_),
    .Y(_06_)
  );
  AND2X2 _26_ (
    .A(_06_),
    .B(_02_),
    .Y(t)
  );
  INVX1 _27_ (
    .A(d),
    .Y(_07_)
  );
  AND2X2 _28_ (
    .A(_07_),
    .B(c),
    .Y(_08_)
  );
  AND2X2 _29_ (
    .A(_08_),
    .B(_03_),
    .Y(_09_)
  );
  AND2X2 _30_ (
    .A(_09_),
    .B(_02_),
    .Y(s)
  );
  AND2X2 _31_ (
    .A(d),
    .B(c),
    .Y(_10_)
  );
  AND2X2 _32_ (
    .A(_03_),
    .B(_10_),
    .Y(_11_)
  );
  AND2X2 _33_ (
    .A(_11_),
    .B(_02_),
    .Y(r)
  );
  NOR2X1 _34_ (
    .A(d),
    .B(c),
    .Y(_12_)
  );
  AND2X2 _35_ (
    .A(_12_),
    .B(b),
    .Y(_13_)
  );
  AND2X2 _36_ (
    .A(_13_),
    .B(_02_),
    .Y(q)
  );
  AND2X2 _37_ (
    .A(_05_),
    .B(b),
    .Y(_14_)
  );
  AND2X2 _38_ (
    .A(_14_),
    .B(_02_),
    .Y(p)
  );
  AND2X2 _39_ (
    .A(_08_),
    .B(b),
    .Y(_15_)
  );
  AND2X2 _40_ (
    .A(_15_),
    .B(_02_),
    .Y(o)
  );
  AND2X2 _41_ (
    .A(_10_),
    .B(b),
    .Y(_16_)
  );
  AND2X2 _42_ (
    .A(_02_),
    .B(_16_),
    .Y(n)
  );
  AND2X2 _43_ (
    .A(e),
    .B(a),
    .Y(_17_)
  );
  AND2X2 _44_ (
    .A(_00_),
    .B(_17_),
    .Y(m)
  );
  AND2X2 _45_ (
    .A(_06_),
    .B(_17_),
    .Y(l)
  );
  AND2X2 _46_ (
    .A(_09_),
    .B(_17_),
    .Y(k)
  );
  AND2X2 _47_ (
    .A(_11_),
    .B(_17_),
    .Y(j)
  );
  AND2X2 _48_ (
    .A(_13_),
    .B(_17_),
    .Y(i)
  );
  AND2X2 _49_ (
    .A(_14_),
    .B(_17_),
    .Y(h)
  );
  AND2X2 _50_ (
    .A(_15_),
    .B(_17_),
    .Y(g)
  );
  AND2X2 _51_ (
    .A(_16_),
    .B(_17_),
    .Y(f)
  );
endmodule
