/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module newbyte(EX_INSpass, byteEX, s1, s0, phi3, ex3, ex2, ex1, ex0, ins3, ins2, ins1, ins0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input EX_INSpass;
  input byteEX;
  output ex0;
  output ex1;
  output ex2;
  output ex3;
  output ins0;
  output ins1;
  output ins2;
  output ins3;
  input phi3;
  input s0;
  input s1;
  INVX1 _11_ (
    .A(s0),
    .Y(_00_)
  );
  AND2X2 _12_ (
    .A(_00_),
    .B(phi3),
    .Y(_01_)
  );
  NOR3X1 _13_ (
    .A(s1),
    .B(byteEX),
    .C(EX_INSpass),
    .Y(_02_)
  );
  AND2X2 _14_ (
    .A(_02_),
    .B(_01_),
    .Y(ins0)
  );
  AND2X2 _15_ (
    .A(phi3),
    .B(s0),
    .Y(_03_)
  );
  AND2X2 _16_ (
    .A(_02_),
    .B(_03_),
    .Y(ins1)
  );
  NOR2X1 _17_ (
    .A(byteEX),
    .B(EX_INSpass),
    .Y(_04_)
  );
  AND2X2 _18_ (
    .A(_04_),
    .B(s1),
    .Y(_05_)
  );
  AND2X2 _19_ (
    .A(_05_),
    .B(_01_),
    .Y(ins2)
  );
  AND2X2 _20_ (
    .A(_05_),
    .B(_03_),
    .Y(ins3)
  );
  INVX1 _21_ (
    .A(s1),
    .Y(_06_)
  );
  INVX1 _22_ (
    .A(EX_INSpass),
    .Y(_07_)
  );
  AND2X2 _23_ (
    .A(_07_),
    .B(byteEX),
    .Y(_08_)
  );
  AND2X2 _24_ (
    .A(_08_),
    .B(_06_),
    .Y(_09_)
  );
  AND2X2 _25_ (
    .A(_09_),
    .B(_01_),
    .Y(ex0)
  );
  AND2X2 _26_ (
    .A(_09_),
    .B(_03_),
    .Y(ex1)
  );
  AND2X2 _27_ (
    .A(_08_),
    .B(s1),
    .Y(_10_)
  );
  AND2X2 _28_ (
    .A(_10_),
    .B(_01_),
    .Y(ex2)
  );
  AND2X2 _29_ (
    .A(_10_),
    .B(_03_),
    .Y(ex3)
  );
endmodule
