/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module misg(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20
, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, v35, v36, v37, v38, v39, v40, v41
, v42, v43, v44, v45, v46, v47, v48, v49, v50, v51, v52, v53, v54, v55, \v56.0 , \v56.1 , \v56.2 , \v56.3 , \v56.4 , \v56.5 , \v56.6 
, \v56.7 , \v56.8 , \v56.9 , \v56.10 , \v56.11 , \v56.12 , \v56.13 , \v56.14 , \v56.15 , \v56.16 , \v56.17 , \v56.18 , \v56.19 , \v56.20 , \v56.21 , \v56.22 );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  input v0;
  input v1;
  input v10;
  input v11;
  input v12;
  input v13;
  input v14;
  input v15;
  input v16;
  input v17;
  input v18;
  input v19;
  input v2;
  input v20;
  input v21;
  input v22;
  input v23;
  input v24;
  input v25;
  input v26;
  input v27;
  input v28;
  input v29;
  input v3;
  input v30;
  input v31;
  input v32;
  input v33;
  input v34;
  input v35;
  input v36;
  input v37;
  input v38;
  input v39;
  input v4;
  input v40;
  input v41;
  input v42;
  input v43;
  input v44;
  input v45;
  input v46;
  input v47;
  input v48;
  input v49;
  input v5;
  input v50;
  input v51;
  input v52;
  input v53;
  input v54;
  input v55;
  output \v56.0 ;
  output \v56.1 ;
  output \v56.10 ;
  output \v56.11 ;
  output \v56.12 ;
  output \v56.13 ;
  output \v56.14 ;
  output \v56.15 ;
  output \v56.16 ;
  output \v56.17 ;
  output \v56.18 ;
  output \v56.19 ;
  output \v56.2 ;
  output \v56.20 ;
  output \v56.21 ;
  output \v56.22 ;
  output \v56.3 ;
  output \v56.4 ;
  output \v56.5 ;
  output \v56.6 ;
  output \v56.7 ;
  output \v56.8 ;
  output \v56.9 ;
  input v6;
  input v7;
  input v8;
  input v9;
  INVX1 _25_ (
    .A(v55),
    .Y(\v56.21 )
  );
  INVX1 _26_ (
    .A(v52),
    .Y(\v56.17 )
  );
  INVX1 _27_ (
    .A(v51),
    .Y(\v56.16 )
  );
  INVX1 _28_ (
    .A(v12),
    .Y(\v56.7 )
  );
  INVX1 _29_ (
    .A(v17),
    .Y(\v56.6 )
  );
  INVX1 _30_ (
    .A(v16),
    .Y(\v56.5 )
  );
  INVX1 _31_ (
    .A(v15),
    .Y(\v56.4 )
  );
  INVX1 _32_ (
    .A(v48),
    .Y(\v56.1 )
  );
  NAND3X1 _33_ (
    .A(v54),
    .B(v20),
    .C(v33),
    .Y(_14_)
  );
  NAND2X1 _34_ (
    .A(v32),
    .B(_14_),
    .Y(\v56.22 )
  );
  AND2X2 _35_ (
    .A(v53),
    .B(v43),
    .Y(_15_)
  );
  AND2X2 _36_ (
    .A(v34),
    .B(v54),
    .Y(_16_)
  );
  AND2X2 _37_ (
    .A(_16_),
    .B(v35),
    .Y(_17_)
  );
  OR2X2 _38_ (
    .A(_15_),
    .B(_17_),
    .Y(_18_)
  );
  AND2X2 _39_ (
    .A(_18_),
    .B(v36),
    .Y(_19_)
  );
  AND2X2 _40_ (
    .A(v40),
    .B(v45),
    .Y(_20_)
  );
  AND2X2 _41_ (
    .A(v38),
    .B(v44),
    .Y(_21_)
  );
  OR2X2 _42_ (
    .A(_20_),
    .B(_21_),
    .Y(_22_)
  );
  AND2X2 _43_ (
    .A(_22_),
    .B(v53),
    .Y(_23_)
  );
  AND2X2 _44_ (
    .A(v37),
    .B(v38),
    .Y(_24_)
  );
  AND2X2 _45_ (
    .A(v39),
    .B(v40),
    .Y(_00_)
  );
  OR2X2 _46_ (
    .A(_24_),
    .B(_00_),
    .Y(_01_)
  );
  AND2X2 _47_ (
    .A(_01_),
    .B(_16_),
    .Y(_02_)
  );
  OR2X2 _48_ (
    .A(_23_),
    .B(_02_),
    .Y(_03_)
  );
  AND2X2 _49_ (
    .A(v32),
    .B(v47),
    .Y(_04_)
  );
  AND2X2 _50_ (
    .A(_04_),
    .B(v49),
    .Y(_05_)
  );
  OAI21X1 _51_ (
    .A(_19_),
    .B(_03_),
    .C(_05_),
    .Y(\v56.20 )
  );
  NAND2X1 _52_ (
    .A(v46),
    .B(_14_),
    .Y(\v56.19 )
  );
  NAND2X1 _53_ (
    .A(v42),
    .B(v41),
    .Y(\v56.18 )
  );
  OR2X2 _54_ (
    .A(v30),
    .B(v31),
    .Y(\v56.15 )
  );
  INVX1 _55_ (
    .A(v49),
    .Y(_06_)
  );
  INVX1 _56_ (
    .A(v27),
    .Y(_07_)
  );
  OAI21X1 _57_ (
    .A(v50),
    .B(_06_),
    .C(_07_),
    .Y(\v56.14 )
  );
  NAND2X1 _58_ (
    .A(v29),
    .B(_07_),
    .Y(\v56.13 )
  );
  NAND3X1 _59_ (
    .A(\v56.6 ),
    .B(v28),
    .C(_07_),
    .Y(\v56.12 )
  );
  NAND2X1 _60_ (
    .A(v26),
    .B(v25),
    .Y(\v56.11 )
  );
  AND2X2 _61_ (
    .A(v18),
    .B(v19),
    .Y(_08_)
  );
  AND2X2 _62_ (
    .A(_08_),
    .B(v20),
    .Y(\v56.10 )
  );
  NAND2X1 _63_ (
    .A(v24),
    .B(v23),
    .Y(\v56.9 )
  );
  INVX1 _64_ (
    .A(v10),
    .Y(_09_)
  );
  AND2X2 _65_ (
    .A(v49),
    .B(v22),
    .Y(_10_)
  );
  NAND3X1 _66_ (
    .A(_09_),
    .B(v21),
    .C(_10_),
    .Y(\v56.8 )
  );
  NAND2X1 _67_ (
    .A(v14),
    .B(v8),
    .Y(\v56.3 )
  );
  NAND2X1 _68_ (
    .A(v11),
    .B(v13),
    .Y(_11_)
  );
  NAND3X1 _69_ (
    .A(_11_),
    .B(_09_),
    .C(v9),
    .Y(\v56.2 )
  );
  AOI22X1 _70_ (
    .A(v6),
    .B(v7),
    .C(v4),
    .D(v5),
    .Y(_12_)
  );
  AOI22X1 _71_ (
    .A(v2),
    .B(v3),
    .C(v0),
    .D(v1),
    .Y(_13_)
  );
  NAND2X1 _72_ (
    .A(_12_),
    .B(_13_),
    .Y(\v56.0 )
  );
endmodule
