/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module xor5(d, c, b, a, e, xor5);
  wire _0_;
  wire _1_;
  wire _2_;
  input a;
  input b;
  input c;
  input d;
  input e;
  output xor5;
  XNOR2X1 _3_ (
    .A(b),
    .B(d),
    .Y(_0_)
  );
  XOR2X1 _4_ (
    .A(e),
    .B(_0_),
    .Y(_1_)
  );
  XNOR2X1 _5_ (
    .A(c),
    .B(a),
    .Y(_2_)
  );
  XOR2X1 _6_ (
    .A(_2_),
    .B(_1_),
    .Y(xor5)
  );
endmodule
