/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module majority(a, b, c, d, e, f);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input a;
  input b;
  input c;
  input d;
  input e;
  output f;
  OR2X2 _07_ (
    .A(c),
    .B(e),
    .Y(_04_)
  );
  AND2X2 _08_ (
    .A(b),
    .B(a),
    .Y(_05_)
  );
  AND2X2 _09_ (
    .A(_05_),
    .B(_04_),
    .Y(_06_)
  );
  OR2X2 _10_ (
    .A(b),
    .B(a),
    .Y(_00_)
  );
  AND2X2 _11_ (
    .A(c),
    .B(e),
    .Y(_01_)
  );
  AND2X2 _12_ (
    .A(_01_),
    .B(_00_),
    .Y(_02_)
  );
  OR2X2 _13_ (
    .A(d),
    .B(_02_),
    .Y(_03_)
  );
  OR2X2 _14_ (
    .A(_06_),
    .B(_03_),
    .Y(f)
  );
endmodule
