/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module misex1(dmpst3, dmpst2, dmpst1, dmpst0, xskip, yskip, page, rmwB, dmnst3B, dmnst2B, dmnst1B, dmnst0B, adctlp2B, adctlp1B, adctlp0B);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  output adctlp0B;
  output adctlp1B;
  output adctlp2B;
  output dmnst0B;
  output dmnst1B;
  output dmnst2B;
  output dmnst3B;
  input dmpst0;
  input dmpst1;
  input dmpst2;
  input dmpst3;
  input page;
  input rmwB;
  input xskip;
  input yskip;
  INVX1 _049_ (
    .A(dmpst2),
    .Y(_000_)
  );
  INVX1 _050_ (
    .A(yskip),
    .Y(_001_)
  );
  INVX1 _051_ (
    .A(dmpst0),
    .Y(_002_)
  );
  AND2X2 _052_ (
    .A(_002_),
    .B(dmpst1),
    .Y(_003_)
  );
  AND2X2 _053_ (
    .A(_003_),
    .B(_001_),
    .Y(_004_)
  );
  XOR2X1 _054_ (
    .A(dmpst1),
    .B(dmpst0),
    .Y(_005_)
  );
  AND2X2 _055_ (
    .A(_005_),
    .B(dmpst3),
    .Y(_006_)
  );
  OR2X2 _056_ (
    .A(_006_),
    .B(_004_),
    .Y(_007_)
  );
  AND2X2 _057_ (
    .A(_007_),
    .B(_000_),
    .Y(_008_)
  );
  INVX1 _058_ (
    .A(dmpst3),
    .Y(_009_)
  );
  AND2X2 _059_ (
    .A(_009_),
    .B(dmpst2),
    .Y(_010_)
  );
  AND2X2 _060_ (
    .A(_010_),
    .B(dmpst0),
    .Y(_011_)
  );
  INVX1 _061_ (
    .A(xskip),
    .Y(_012_)
  );
  INVX1 _062_ (
    .A(dmpst1),
    .Y(_013_)
  );
  AND2X2 _063_ (
    .A(_010_),
    .B(_013_),
    .Y(_014_)
  );
  AND2X2 _064_ (
    .A(_014_),
    .B(_012_),
    .Y(_015_)
  );
  OR2X2 _065_ (
    .A(_011_),
    .B(_015_),
    .Y(_016_)
  );
  OR2X2 _066_ (
    .A(_008_),
    .B(_016_),
    .Y(adctlp0B)
  );
  AND2X2 _067_ (
    .A(_009_),
    .B(yskip),
    .Y(_017_)
  );
  AND2X2 _068_ (
    .A(_017_),
    .B(dmpst1),
    .Y(_018_)
  );
  OR2X2 _069_ (
    .A(_006_),
    .B(_018_),
    .Y(_019_)
  );
  AND2X2 _070_ (
    .A(_019_),
    .B(_000_),
    .Y(_020_)
  );
  AND2X2 _071_ (
    .A(_002_),
    .B(page),
    .Y(_021_)
  );
  OR2X2 _072_ (
    .A(dmpst2),
    .B(dmpst1),
    .Y(_022_)
  );
  OR2X2 _073_ (
    .A(_022_),
    .B(_021_),
    .Y(_023_)
  );
  OR2X2 _074_ (
    .A(dmpst0),
    .B(_013_),
    .Y(_024_)
  );
  AND2X2 _075_ (
    .A(_024_),
    .B(_009_),
    .Y(_025_)
  );
  AND2X2 _076_ (
    .A(_023_),
    .B(_025_),
    .Y(_026_)
  );
  OR2X2 _077_ (
    .A(_026_),
    .B(_020_),
    .Y(adctlp1B)
  );
  NAND2X1 _078_ (
    .A(_000_),
    .B(_005_),
    .Y(_027_)
  );
  XNOR2X1 _079_ (
    .A(_025_),
    .B(_027_),
    .Y(adctlp2B)
  );
  OR2X2 _080_ (
    .A(xskip),
    .B(dmpst0),
    .Y(_028_)
  );
  NAND2X1 _081_ (
    .A(rmwB),
    .B(_028_),
    .Y(_029_)
  );
  AND2X2 _082_ (
    .A(_029_),
    .B(_014_),
    .Y(_030_)
  );
  OR2X2 _083_ (
    .A(dmpst3),
    .B(_001_),
    .Y(_031_)
  );
  AND2X2 _084_ (
    .A(_003_),
    .B(_000_),
    .Y(_032_)
  );
  AND2X2 _085_ (
    .A(_032_),
    .B(_031_),
    .Y(_033_)
  );
  OR2X2 _086_ (
    .A(_033_),
    .B(_030_),
    .Y(dmnst0B)
  );
  AND2X2 _087_ (
    .A(_024_),
    .B(_010_),
    .Y(_034_)
  );
  AND2X2 _088_ (
    .A(_034_),
    .B(_028_),
    .Y(_035_)
  );
  AND2X2 _089_ (
    .A(_013_),
    .B(dmpst0),
    .Y(_036_)
  );
  AND2X2 _090_ (
    .A(_000_),
    .B(dmpst3),
    .Y(_037_)
  );
  AND2X2 _091_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  NOR3X1 _092_ (
    .A(dmpst2),
    .B(dmpst3),
    .C(dmpst0),
    .Y(_039_)
  );
  MUX2X1 _093_ (
    .A(yskip),
    .B(page),
    .S(dmpst1),
    .Y(_040_)
  );
  AND2X2 _094_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  OR2X2 _095_ (
    .A(_038_),
    .B(_041_),
    .Y(_042_)
  );
  OR2X2 _096_ (
    .A(_035_),
    .B(_042_),
    .Y(dmnst1B)
  );
  OR2X2 _097_ (
    .A(yskip),
    .B(_024_),
    .Y(_043_)
  );
  AOI21X1 _098_ (
    .A(dmpst2),
    .B(dmpst1),
    .C(dmpst3),
    .Y(_044_)
  );
  AND2X2 _099_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  AND2X2 _100_ (
    .A(_045_),
    .B(_023_),
    .Y(_046_)
  );
  OR2X2 _101_ (
    .A(_038_),
    .B(_046_),
    .Y(dmnst2B)
  );
  AND2X2 _102_ (
    .A(_037_),
    .B(_002_),
    .Y(_047_)
  );
  OR2X2 _103_ (
    .A(_011_),
    .B(_047_),
    .Y(_048_)
  );
  AND2X2 _104_ (
    .A(_048_),
    .B(dmpst1),
    .Y(dmnst3B)
  );
endmodule
