/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module alu1(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, \v12.0 , \v12.1 , \v12.2 , \v12.3 , \v12.4 , \v12.5 , \v12.6 , \v12.7 );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  input v0;
  input v1;
  input v10;
  input v11;
  output \v12.0 ;
  output \v12.1 ;
  output \v12.2 ;
  output \v12.3 ;
  output \v12.4 ;
  output \v12.5 ;
  output \v12.6 ;
  output \v12.7 ;
  input v2;
  input v3;
  input v4;
  input v5;
  input v6;
  input v7;
  input v8;
  input v9;
  INVX1 _19_ (
    .A(v8),
    .Y(_00_)
  );
  INVX1 _20_ (
    .A(v3),
    .Y(_01_)
  );
  AND2X2 _21_ (
    .A(_01_),
    .B(v7),
    .Y(_02_)
  );
  AND2X2 _22_ (
    .A(_02_),
    .B(_00_),
    .Y(\v12.7 )
  );
  INVX1 _23_ (
    .A(v9),
    .Y(_03_)
  );
  OR2X2 _24_ (
    .A(v6),
    .B(_03_),
    .Y(_04_)
  );
  AOI21X1 _25_ (
    .A(v8),
    .B(v6),
    .C(v2),
    .Y(_05_)
  );
  AND2X2 _26_ (
    .A(_04_),
    .B(_05_),
    .Y(\v12.6 )
  );
  OR2X2 _27_ (
    .A(v5),
    .B(_03_),
    .Y(_06_)
  );
  AOI21X1 _28_ (
    .A(v8),
    .B(v5),
    .C(v1),
    .Y(_07_)
  );
  AND2X2 _29_ (
    .A(_06_),
    .B(_07_),
    .Y(\v12.5 )
  );
  OR2X2 _30_ (
    .A(v4),
    .B(_03_),
    .Y(_08_)
  );
  AOI21X1 _31_ (
    .A(v8),
    .B(v4),
    .C(v0),
    .Y(_09_)
  );
  AND2X2 _32_ (
    .A(_08_),
    .B(_09_),
    .Y(\v12.4 )
  );
  INVX1 _33_ (
    .A(v11),
    .Y(_10_)
  );
  AND2X2 _34_ (
    .A(_10_),
    .B(v7),
    .Y(_11_)
  );
  OAI21X1 _35_ (
    .A(v7),
    .B(v10),
    .C(v3),
    .Y(_12_)
  );
  OR2X2 _36_ (
    .A(_12_),
    .B(_11_),
    .Y(\v12.3 )
  );
  AND2X2 _37_ (
    .A(_10_),
    .B(v6),
    .Y(_13_)
  );
  OAI21X1 _38_ (
    .A(v6),
    .B(v10),
    .C(v2),
    .Y(_14_)
  );
  OR2X2 _39_ (
    .A(_14_),
    .B(_13_),
    .Y(\v12.2 )
  );
  AND2X2 _40_ (
    .A(_10_),
    .B(v5),
    .Y(_15_)
  );
  OAI21X1 _41_ (
    .A(v5),
    .B(v10),
    .C(v1),
    .Y(_16_)
  );
  OR2X2 _42_ (
    .A(_16_),
    .B(_15_),
    .Y(\v12.1 )
  );
  AND2X2 _43_ (
    .A(_10_),
    .B(v4),
    .Y(_17_)
  );
  OAI21X1 _44_ (
    .A(v4),
    .B(v10),
    .C(v0),
    .Y(_18_)
  );
  OR2X2 _45_ (
    .A(_18_),
    .B(_17_),
    .Y(\v12.0 )
  );
endmodule
