/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module ctrl(\opcode[0] , \opcode[1] , \opcode[2] , \opcode[3] , \opcode[4] , \op_ext[0] , \op_ext[1] , \sel_reg_dst[0] , \sel_reg_dst[1] , \sel_alu_opB[0] , \sel_alu_opB[1] , \alu_op[0] , \alu_op[1] , \alu_op[2] , \alu_op_ext[0] , \alu_op_ext[1] , \alu_op_ext[2] , \alu_op_ext[3] , halt, reg_write, sel_pc_opA
, sel_pc_opB, beqz, bnez, bgez, bltz, jump, Cin, invA, invB, sign, mem_write, sel_wb);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  output Cin;
  output \alu_op[0] ;
  output \alu_op[1] ;
  output \alu_op[2] ;
  output \alu_op_ext[0] ;
  output \alu_op_ext[1] ;
  output \alu_op_ext[2] ;
  output \alu_op_ext[3] ;
  output beqz;
  output bgez;
  output bltz;
  output bnez;
  output halt;
  output invA;
  output invB;
  output jump;
  output mem_write;
  input \op_ext[0] ;
  input \op_ext[1] ;
  input \opcode[0] ;
  input \opcode[1] ;
  input \opcode[2] ;
  input \opcode[3] ;
  input \opcode[4] ;
  output reg_write;
  output \sel_alu_opB[0] ;
  output \sel_alu_opB[1] ;
  output sel_pc_opA;
  output sel_pc_opB;
  output \sel_reg_dst[0] ;
  output \sel_reg_dst[1] ;
  output sel_wb;
  output sign;
  INVX1 _075_ (
    .A(\opcode[1] ),
    .Y(_023_)
  );
  NAND2X1 _076_ (
    .A(\opcode[0] ),
    .B(_023_),
    .Y(_024_)
  );
  INVX1 _077_ (
    .A(\opcode[2] ),
    .Y(_025_)
  );
  INVX1 _078_ (
    .A(\opcode[3] ),
    .Y(_026_)
  );
  NAND3X1 _079_ (
    .A(_025_),
    .B(\opcode[4] ),
    .C(_026_),
    .Y(_027_)
  );
  NOR2X1 _080_ (
    .A(_027_),
    .B(_024_),
    .Y(sel_wb)
  );
  INVX1 _081_ (
    .A(\opcode[0] ),
    .Y(_028_)
  );
  NOR2X1 _082_ (
    .A(_028_),
    .B(\opcode[1] ),
    .Y(_029_)
  );
  OR2X2 _083_ (
    .A(\opcode[0] ),
    .B(_023_),
    .Y(_030_)
  );
  INVX1 _084_ (
    .A(_030_),
    .Y(_031_)
  );
  NOR3X1 _085_ (
    .A(_031_),
    .B(_029_),
    .C(_027_),
    .Y(mem_write)
  );
  INVX1 _086_ (
    .A(\op_ext[1] ),
    .Y(_032_)
  );
  INVX1 _087_ (
    .A(\op_ext[0] ),
    .Y(_033_)
  );
  AND2X2 _088_ (
    .A(_033_),
    .B(\opcode[4] ),
    .Y(_034_)
  );
  NAND3X1 _089_ (
    .A(\opcode[0] ),
    .B(\opcode[3] ),
    .C(\opcode[1] ),
    .Y(_035_)
  );
  OR2X2 _090_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  OR2X2 _091_ (
    .A(\opcode[4] ),
    .B(_026_),
    .Y(_037_)
  );
  AND2X2 _092_ (
    .A(_037_),
    .B(_025_),
    .Y(_038_)
  );
  AOI22X1 _093_ (
    .A(_032_),
    .B(_038_),
    .C(_025_),
    .D(_036_),
    .Y(_039_)
  );
  AND2X2 _094_ (
    .A(\opcode[0] ),
    .B(\opcode[1] ),
    .Y(_040_)
  );
  NAND2X1 _095_ (
    .A(\opcode[3] ),
    .B(\opcode[4] ),
    .Y(_041_)
  );
  OAI21X1 _096_ (
    .A(_040_),
    .B(_041_),
    .C(\opcode[2] ),
    .Y(_042_)
  );
  AND2X2 _097_ (
    .A(_039_),
    .B(_042_),
    .Y(invB)
  );
  INVX1 _098_ (
    .A(\opcode[4] ),
    .Y(_043_)
  );
  AND2X2 _099_ (
    .A(_043_),
    .B(\opcode[3] ),
    .Y(_044_)
  );
  AND2X2 _100_ (
    .A(_029_),
    .B(_044_),
    .Y(_045_)
  );
  NAND2X1 _101_ (
    .A(\opcode[0] ),
    .B(\opcode[1] ),
    .Y(_046_)
  );
  NAND3X1 _102_ (
    .A(\opcode[3] ),
    .B(\opcode[4] ),
    .C(\op_ext[0] ),
    .Y(_047_)
  );
  NOR3X1 _103_ (
    .A(_047_),
    .B(\op_ext[1] ),
    .C(_046_),
    .Y(_048_)
  );
  OR2X2 _104_ (
    .A(_045_),
    .B(_048_),
    .Y(_049_)
  );
  AND2X2 _105_ (
    .A(_049_),
    .B(_025_),
    .Y(invA)
  );
  AND2X2 _106_ (
    .A(_036_),
    .B(_025_),
    .Y(_050_)
  );
  OAI21X1 _107_ (
    .A(_024_),
    .B(_037_),
    .C(_050_),
    .Y(_051_)
  );
  AND2X2 _108_ (
    .A(_051_),
    .B(_042_),
    .Y(Cin)
  );
  NAND2X1 _109_ (
    .A(\opcode[2] ),
    .B(_044_),
    .Y(_052_)
  );
  NOR2X1 _110_ (
    .A(_052_),
    .B(_030_),
    .Y(bltz)
  );
  NOR2X1 _111_ (
    .A(_052_),
    .B(_046_),
    .Y(bgez)
  );
  NOR2X1 _112_ (
    .A(_052_),
    .B(_024_),
    .Y(bnez)
  );
  OR2X2 _113_ (
    .A(\opcode[0] ),
    .B(\opcode[1] ),
    .Y(_053_)
  );
  NOR2X1 _114_ (
    .A(_052_),
    .B(_053_),
    .Y(beqz)
  );
  OR2X2 _115_ (
    .A(\opcode[3] ),
    .B(\opcode[4] ),
    .Y(_054_)
  );
  INVX1 _116_ (
    .A(_054_),
    .Y(_055_)
  );
  NAND2X1 _117_ (
    .A(\opcode[2] ),
    .B(_055_),
    .Y(_056_)
  );
  INVX1 _118_ (
    .A(_056_),
    .Y(jump)
  );
  NOR2X1 _119_ (
    .A(_056_),
    .B(\opcode[0] ),
    .Y(sel_pc_opB)
  );
  NOR2X1 _120_ (
    .A(_056_),
    .B(_028_),
    .Y(sel_pc_opA)
  );
  NAND2X1 _121_ (
    .A(_054_),
    .B(_025_),
    .Y(_057_)
  );
  NOR2X1 _122_ (
    .A(_053_),
    .B(\opcode[3] ),
    .Y(_058_)
  );
  NOR2X1 _123_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  NAND2X1 _124_ (
    .A(_023_),
    .B(_043_),
    .Y(_060_)
  );
  NOR2X1 _125_ (
    .A(_044_),
    .B(_025_),
    .Y(_061_)
  );
  AND2X2 _126_ (
    .A(_061_),
    .B(_060_),
    .Y(_062_)
  );
  OR2X2 _127_ (
    .A(_062_),
    .B(_059_),
    .Y(reg_write)
  );
  NOR3X1 _128_ (
    .A(_053_),
    .B(\opcode[2] ),
    .C(_054_),
    .Y(halt)
  );
  AND2X2 _129_ (
    .A(_026_),
    .B(\opcode[4] ),
    .Y(_063_)
  );
  OR2X2 _130_ (
    .A(_025_),
    .B(_063_),
    .Y(_064_)
  );
  AND2X2 _131_ (
    .A(_064_),
    .B(\opcode[1] ),
    .Y(_065_)
  );
  OAI21X1 _132_ (
    .A(_028_),
    .B(_043_),
    .C(_026_),
    .Y(_066_)
  );
  AND2X2 _133_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  AND2X2 _134_ (
    .A(\opcode[3] ),
    .B(\opcode[4] ),
    .Y(_068_)
  );
  OAI21X1 _135_ (
    .A(\opcode[1] ),
    .B(_068_),
    .C(_025_),
    .Y(_069_)
  );
  NOR2X1 _136_ (
    .A(_026_),
    .B(\opcode[2] ),
    .Y(_070_)
  );
  OR2X2 _137_ (
    .A(_063_),
    .B(_070_),
    .Y(_071_)
  );
  AND2X2 _138_ (
    .A(_071_),
    .B(_069_),
    .Y(_072_)
  );
  OR2X2 _139_ (
    .A(_067_),
    .B(_072_),
    .Y(\alu_op_ext[3] )
  );
  NOR3X1 _140_ (
    .A(_025_),
    .B(_054_),
    .C(_023_),
    .Y(_073_)
  );
  AOI21X1 _141_ (
    .A(_023_),
    .B(_041_),
    .C(\opcode[2] ),
    .Y(_074_)
  );
  OR2X2 _142_ (
    .A(_023_),
    .B(_063_),
    .Y(_000_)
  );
  AND2X2 _143_ (
    .A(_000_),
    .B(_046_),
    .Y(_001_)
  );
  AND2X2 _144_ (
    .A(_074_),
    .B(_001_),
    .Y(_002_)
  );
  OR2X2 _145_ (
    .A(_073_),
    .B(_002_),
    .Y(\alu_op_ext[2] )
  );
  AND2X2 _146_ (
    .A(_063_),
    .B(_025_),
    .Y(_003_)
  );
  AND2X2 _147_ (
    .A(_031_),
    .B(_003_),
    .Y(_004_)
  );
  NOR3X1 _148_ (
    .A(_000_),
    .B(_025_),
    .C(_044_),
    .Y(_005_)
  );
  OR2X2 _149_ (
    .A(_004_),
    .B(_005_),
    .Y(\alu_op_ext[1] )
  );
  NAND3X1 _150_ (
    .A(_055_),
    .B(\opcode[2] ),
    .C(\opcode[1] ),
    .Y(_006_)
  );
  NAND3X1 _151_ (
    .A(_068_),
    .B(\opcode[2] ),
    .C(\opcode[0] ),
    .Y(_007_)
  );
  INVX1 _152_ (
    .A(_053_),
    .Y(_008_)
  );
  NAND3X1 _153_ (
    .A(_008_),
    .B(_025_),
    .C(_068_),
    .Y(_009_)
  );
  NAND3X1 _154_ (
    .A(_006_),
    .B(_007_),
    .C(_009_),
    .Y(\alu_op_ext[0] )
  );
  NOR2X1 _155_ (
    .A(_041_),
    .B(_040_),
    .Y(_010_)
  );
  NAND2X1 _156_ (
    .A(\opcode[2] ),
    .B(_068_),
    .Y(_011_)
  );
  OAI21X1 _157_ (
    .A(_057_),
    .B(_010_),
    .C(_011_),
    .Y(\alu_op[2] )
  );
  OAI21X1 _158_ (
    .A(_032_),
    .B(_026_),
    .C(_038_),
    .Y(_012_)
  );
  AND2X2 _159_ (
    .A(_012_),
    .B(_065_),
    .Y(\alu_op[1] )
  );
  AND2X2 _160_ (
    .A(_038_),
    .B(_032_),
    .Y(_013_)
  );
  OR2X2 _161_ (
    .A(_047_),
    .B(_030_),
    .Y(_014_)
  );
  OAI21X1 _162_ (
    .A(_013_),
    .B(_050_),
    .C(_014_),
    .Y(_015_)
  );
  AND2X2 _163_ (
    .A(_063_),
    .B(\opcode[0] ),
    .Y(_016_)
  );
  OR2X2 _164_ (
    .A(_025_),
    .B(_016_),
    .Y(_017_)
  );
  AND2X2 _165_ (
    .A(_015_),
    .B(_017_),
    .Y(\alu_op[0] )
  );
  NAND3X1 _166_ (
    .A(_070_),
    .B(_053_),
    .C(_060_),
    .Y(_018_)
  );
  AND2X2 _167_ (
    .A(_018_),
    .B(_071_),
    .Y(\sel_alu_opB[1] )
  );
  AND2X2 _168_ (
    .A(_074_),
    .B(_024_),
    .Y(_019_)
  );
  OR2X2 _169_ (
    .A(_044_),
    .B(_001_),
    .Y(_020_)
  );
  AND2X2 _170_ (
    .A(_019_),
    .B(_020_),
    .Y(\sel_alu_opB[0] )
  );
  AND2X2 _171_ (
    .A(_019_),
    .B(_000_),
    .Y(_021_)
  );
  OR2X2 _172_ (
    .A(_073_),
    .B(_021_),
    .Y(\sel_reg_dst[1] )
  );
  OAI21X1 _173_ (
    .A(\opcode[2] ),
    .B(_053_),
    .C(_068_),
    .Y(_022_)
  );
  NAND2X1 _174_ (
    .A(_022_),
    .B(_006_),
    .Y(\sel_reg_dst[0] )
  );
  assign sign = 1'h1;
endmodule
