/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module tcon(a, b, c, d, e, f, g, h, i, k, l, m, n, o, p, q, r, s, t, u, v
, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input a;
  output a0;
  input b;
  output b0;
  input c;
  output c0;
  input d;
  output d0;
  input e;
  output e0;
  input f;
  output f0;
  input g;
  output g0;
  input h;
  output h0;
  input i;
  input k;
  input l;
  input m;
  input n;
  input o;
  input p;
  input q;
  input r;
  output s;
  output t;
  output u;
  output v;
  output w;
  output x;
  output y;
  output z;
  OR2X2 _17_ (
    .A(i),
    .B(r),
    .Y(_00_)
  );
  INVX1 _18_ (
    .A(i),
    .Y(_01_)
  );
  OR2X2 _19_ (
    .A(h),
    .B(_01_),
    .Y(_02_)
  );
  AND2X2 _20_ (
    .A(_02_),
    .B(_00_),
    .Y(h0)
  );
  OR2X2 _21_ (
    .A(i),
    .B(q),
    .Y(_03_)
  );
  OR2X2 _22_ (
    .A(g),
    .B(_01_),
    .Y(_04_)
  );
  AND2X2 _23_ (
    .A(_04_),
    .B(_03_),
    .Y(g0)
  );
  OR2X2 _24_ (
    .A(i),
    .B(p),
    .Y(_05_)
  );
  OR2X2 _25_ (
    .A(f),
    .B(_01_),
    .Y(_06_)
  );
  AND2X2 _26_ (
    .A(_06_),
    .B(_05_),
    .Y(f0)
  );
  OR2X2 _27_ (
    .A(i),
    .B(o),
    .Y(_07_)
  );
  OR2X2 _28_ (
    .A(e),
    .B(_01_),
    .Y(_08_)
  );
  AND2X2 _29_ (
    .A(_08_),
    .B(_07_),
    .Y(e0)
  );
  OR2X2 _30_ (
    .A(i),
    .B(n),
    .Y(_09_)
  );
  OR2X2 _31_ (
    .A(d),
    .B(_01_),
    .Y(_10_)
  );
  AND2X2 _32_ (
    .A(_10_),
    .B(_09_),
    .Y(d0)
  );
  OR2X2 _33_ (
    .A(i),
    .B(m),
    .Y(_11_)
  );
  OR2X2 _34_ (
    .A(c),
    .B(_01_),
    .Y(_12_)
  );
  AND2X2 _35_ (
    .A(_12_),
    .B(_11_),
    .Y(c0)
  );
  OR2X2 _36_ (
    .A(i),
    .B(l),
    .Y(_13_)
  );
  OR2X2 _37_ (
    .A(b),
    .B(_01_),
    .Y(_14_)
  );
  AND2X2 _38_ (
    .A(_14_),
    .B(_13_),
    .Y(b0)
  );
  OR2X2 _39_ (
    .A(i),
    .B(k),
    .Y(_15_)
  );
  OR2X2 _40_ (
    .A(a),
    .B(_01_),
    .Y(_16_)
  );
  AND2X2 _41_ (
    .A(_16_),
    .B(_15_),
    .Y(a0)
  );
  assign z = r;
  assign y = q;
  assign x = p;
  assign w = o;
  assign v = n;
  assign u = m;
  assign t = l;
  assign s = k;
endmodule
