/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module cm82a(a, b, c, d, e, f, g, h);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  input a;
  input b;
  input c;
  input d;
  input e;
  output f;
  output g;
  output h;
  OR2X2 _09_ (
    .A(b),
    .B(c),
    .Y(_08_)
  );
  AND2X2 _10_ (
    .A(b),
    .B(c),
    .Y(_00_)
  );
  OR2X2 _11_ (
    .A(a),
    .B(_00_),
    .Y(_01_)
  );
  AND2X2 _12_ (
    .A(_01_),
    .B(_08_),
    .Y(_02_)
  );
  OR2X2 _13_ (
    .A(d),
    .B(e),
    .Y(_03_)
  );
  AND2X2 _14_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  AND2X2 _15_ (
    .A(d),
    .B(e),
    .Y(_05_)
  );
  OR2X2 _16_ (
    .A(_05_),
    .B(_04_),
    .Y(h)
  );
  XOR2X1 _17_ (
    .A(d),
    .B(e),
    .Y(_06_)
  );
  XOR2X1 _18_ (
    .A(_06_),
    .B(_02_),
    .Y(g)
  );
  XNOR2X1 _19_ (
    .A(b),
    .B(c),
    .Y(_07_)
  );
  XNOR2X1 _20_ (
    .A(a),
    .B(_07_),
    .Y(f)
  );
endmodule
