/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module c880(G1gat, G8gat, G13gat, G17gat, G26gat, G29gat, G36gat, G42gat, G51gat, G55gat, G59gat, G68gat, G72gat, G73gat, G74gat, G75gat, G80gat, G85gat, G86gat, G87gat, G88gat
, G89gat, G90gat, G91gat, G96gat, G101gat, G106gat, G111gat, G116gat, G121gat, G126gat, G130gat, G135gat, G138gat, G143gat, G146gat, G149gat, G152gat, G153gat, G156gat, G159gat, G165gat
, G171gat, G177gat, G183gat, G189gat, G195gat, G201gat, G207gat, G210gat, G219gat, G228gat, G237gat, G246gat, G255gat, G259gat, G260gat, G261gat, G267gat, G268gat, G388gat, G389gat, G390gat
, G391gat, G418gat, G419gat, G420gat, G421gat, G422gat, G423gat, G446gat, G447gat, G448gat, G449gat, G450gat, G767gat, G768gat, G850gat, G863gat, G864gat, G865gat, G866gat, G874gat, G878gat
, G879gat, G880gat);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  input G101gat;
  input G106gat;
  input G111gat;
  input G116gat;
  input G121gat;
  input G126gat;
  input G130gat;
  input G135gat;
  input G138gat;
  input G13gat;
  input G143gat;
  input G146gat;
  input G149gat;
  input G152gat;
  input G153gat;
  input G156gat;
  input G159gat;
  input G165gat;
  input G171gat;
  input G177gat;
  input G17gat;
  input G183gat;
  input G189gat;
  input G195gat;
  input G1gat;
  input G201gat;
  input G207gat;
  input G210gat;
  input G219gat;
  input G228gat;
  input G237gat;
  input G246gat;
  input G255gat;
  input G259gat;
  input G260gat;
  input G261gat;
  input G267gat;
  input G268gat;
  input G26gat;
  input G29gat;
  input G36gat;
  output G388gat;
  output G389gat;
  output G390gat;
  output G391gat;
  output G418gat;
  output G419gat;
  output G420gat;
  output G421gat;
  output G422gat;
  output G423gat;
  input G42gat;
  output G446gat;
  output G447gat;
  output G448gat;
  output G449gat;
  output G450gat;
  input G51gat;
  input G55gat;
  input G59gat;
  input G68gat;
  input G72gat;
  input G73gat;
  input G74gat;
  input G75gat;
  output G767gat;
  output G768gat;
  input G80gat;
  output G850gat;
  input G85gat;
  output G863gat;
  output G864gat;
  output G865gat;
  output G866gat;
  input G86gat;
  output G874gat;
  output G878gat;
  output G879gat;
  input G87gat;
  output G880gat;
  input G88gat;
  input G89gat;
  input G8gat;
  input G90gat;
  input G91gat;
  input G96gat;
  AND2X2 _251_ (
    .A(G1gat),
    .B(G26gat),
    .Y(_239_)
  );
  AND2X2 _252_ (
    .A(_239_),
    .B(G51gat),
    .Y(G447gat)
  );
  OR2X2 _253_ (
    .A(G17gat),
    .B(G42gat),
    .Y(_240_)
  );
  AND2X2 _254_ (
    .A(G59gat),
    .B(G156gat),
    .Y(_241_)
  );
  NAND2X1 _255_ (
    .A(G17gat),
    .B(G42gat),
    .Y(_242_)
  );
  AND2X2 _256_ (
    .A(_242_),
    .B(_241_),
    .Y(_243_)
  );
  AND2X2 _257_ (
    .A(_243_),
    .B(_240_),
    .Y(_244_)
  );
  AND2X2 _258_ (
    .A(_244_),
    .B(G447gat),
    .Y(_245_)
  );
  NAND3X1 _259_ (
    .A(G42gat),
    .B(G59gat),
    .C(G75gat),
    .Y(_246_)
  );
  AND2X2 _260_ (
    .A(G8gat),
    .B(G1gat),
    .Y(_247_)
  );
  AND2X2 _261_ (
    .A(G17gat),
    .B(G51gat),
    .Y(_248_)
  );
  AND2X2 _262_ (
    .A(_247_),
    .B(_248_),
    .Y(_249_)
  );
  AND2X2 _263_ (
    .A(_249_),
    .B(_246_),
    .Y(_250_)
  );
  OR2X2 _264_ (
    .A(_250_),
    .B(_245_),
    .Y(_000_)
  );
  AND2X2 _265_ (
    .A(_000_),
    .B(G101gat),
    .Y(_001_)
  );
  INVX1 _266_ (
    .A(G149gat),
    .Y(_002_)
  );
  NAND2X1 _267_ (
    .A(G59gat),
    .B(G156gat),
    .Y(_003_)
  );
  NAND3X1 _268_ (
    .A(_003_),
    .B(G55gat),
    .C(G447gat),
    .Y(_004_)
  );
  INVX1 _269_ (
    .A(G17gat),
    .Y(_005_)
  );
  AND2X2 _270_ (
    .A(G29gat),
    .B(G75gat),
    .Y(_006_)
  );
  NAND3X1 _271_ (
    .A(G447gat),
    .B(G80gat),
    .C(_006_),
    .Y(_007_)
  );
  NOR3X1 _272_ (
    .A(_007_),
    .B(G268gat),
    .C(_005_),
    .Y(_008_)
  );
  AOI21X1 _273_ (
    .A(G138gat),
    .B(G17gat),
    .C(_008_),
    .Y(_009_)
  );
  OAI21X1 _274_ (
    .A(_002_),
    .B(_004_),
    .C(_009_),
    .Y(_010_)
  );
  OR2X2 _275_ (
    .A(_001_),
    .B(_010_),
    .Y(_011_)
  );
  XOR2X1 _276_ (
    .A(G171gat),
    .B(_011_),
    .Y(_012_)
  );
  INVX1 _277_ (
    .A(_012_),
    .Y(_013_)
  );
  NAND2X1 _278_ (
    .A(G106gat),
    .B(_000_),
    .Y(_014_)
  );
  INVX1 _279_ (
    .A(_004_),
    .Y(_015_)
  );
  NAND2X1 _280_ (
    .A(G153gat),
    .B(_015_),
    .Y(_016_)
  );
  AOI21X1 _281_ (
    .A(G138gat),
    .B(G152gat),
    .C(_008_),
    .Y(_017_)
  );
  NAND3X1 _282_ (
    .A(_017_),
    .B(_014_),
    .C(_016_),
    .Y(_018_)
  );
  NAND2X1 _283_ (
    .A(G177gat),
    .B(_018_),
    .Y(_019_)
  );
  NAND3X1 _284_ (
    .A(G51gat),
    .B(G1gat),
    .C(G26gat),
    .Y(_020_)
  );
  OR2X2 _285_ (
    .A(_241_),
    .B(_020_),
    .Y(_021_)
  );
  OAI21X1 _286_ (
    .A(_005_),
    .B(_021_),
    .C(G1gat),
    .Y(_022_)
  );
  AND2X2 _287_ (
    .A(_022_),
    .B(G143gat),
    .Y(_023_)
  );
  INVX1 _288_ (
    .A(G111gat),
    .Y(_024_)
  );
  INVX1 _289_ (
    .A(_240_),
    .Y(_025_)
  );
  AND2X2 _290_ (
    .A(G17gat),
    .B(G42gat),
    .Y(_026_)
  );
  OR2X2 _291_ (
    .A(_026_),
    .B(_003_),
    .Y(_027_)
  );
  OR2X2 _292_ (
    .A(_025_),
    .B(_027_),
    .Y(_028_)
  );
  OR2X2 _293_ (
    .A(_020_),
    .B(_028_),
    .Y(_029_)
  );
  AND2X2 _294_ (
    .A(G59gat),
    .B(G75gat),
    .Y(_030_)
  );
  AND2X2 _295_ (
    .A(_030_),
    .B(G42gat),
    .Y(_031_)
  );
  NAND3X1 _296_ (
    .A(_247_),
    .B(G17gat),
    .C(G51gat),
    .Y(_032_)
  );
  OR2X2 _297_ (
    .A(_031_),
    .B(_032_),
    .Y(_033_)
  );
  AND2X2 _298_ (
    .A(_029_),
    .B(_033_),
    .Y(_034_)
  );
  INVX1 _299_ (
    .A(G55gat),
    .Y(_035_)
  );
  OR2X2 _300_ (
    .A(G268gat),
    .B(_035_),
    .Y(_036_)
  );
  OR2X2 _301_ (
    .A(_036_),
    .B(_007_),
    .Y(_037_)
  );
  OAI21X1 _302_ (
    .A(_024_),
    .B(_034_),
    .C(_037_),
    .Y(_038_)
  );
  OR2X2 _303_ (
    .A(_023_),
    .B(_038_),
    .Y(_039_)
  );
  NAND2X1 _304_ (
    .A(G183gat),
    .B(_039_),
    .Y(_040_)
  );
  NOR2X1 _305_ (
    .A(_039_),
    .B(G183gat),
    .Y(_041_)
  );
  INVX1 _306_ (
    .A(G146gat),
    .Y(_042_)
  );
  NAND3X1 _307_ (
    .A(_003_),
    .B(G17gat),
    .C(G447gat),
    .Y(_043_)
  );
  AND2X2 _308_ (
    .A(_043_),
    .B(G1gat),
    .Y(_044_)
  );
  NOR2X1 _309_ (
    .A(_044_),
    .B(_042_),
    .Y(_045_)
  );
  INVX1 _310_ (
    .A(G116gat),
    .Y(_046_)
  );
  OAI21X1 _311_ (
    .A(_046_),
    .B(_034_),
    .C(_037_),
    .Y(_047_)
  );
  OR2X2 _312_ (
    .A(_045_),
    .B(_047_),
    .Y(_048_)
  );
  OR2X2 _313_ (
    .A(G189gat),
    .B(_048_),
    .Y(_049_)
  );
  INVX1 _314_ (
    .A(_049_),
    .Y(_050_)
  );
  INVX1 _315_ (
    .A(G195gat),
    .Y(_051_)
  );
  NAND2X1 _316_ (
    .A(G149gat),
    .B(_022_),
    .Y(_052_)
  );
  NAND2X1 _317_ (
    .A(G80gat),
    .B(_006_),
    .Y(_053_)
  );
  NOR3X1 _318_ (
    .A(_053_),
    .B(_020_),
    .C(_036_),
    .Y(_054_)
  );
  AOI21X1 _319_ (
    .A(G121gat),
    .B(_000_),
    .C(_054_),
    .Y(_055_)
  );
  AND2X2 _320_ (
    .A(_055_),
    .B(_052_),
    .Y(_056_)
  );
  OR2X2 _321_ (
    .A(_051_),
    .B(_056_),
    .Y(_057_)
  );
  AND2X2 _322_ (
    .A(_056_),
    .B(_051_),
    .Y(_058_)
  );
  INVX1 _323_ (
    .A(G201gat),
    .Y(_059_)
  );
  INVX1 _324_ (
    .A(G153gat),
    .Y(_060_)
  );
  OR2X2 _325_ (
    .A(_060_),
    .B(_044_),
    .Y(_061_)
  );
  INVX1 _326_ (
    .A(G126gat),
    .Y(_062_)
  );
  OR2X2 _327_ (
    .A(_062_),
    .B(_034_),
    .Y(_063_)
  );
  AND2X2 _328_ (
    .A(_063_),
    .B(_037_),
    .Y(_064_)
  );
  AND2X2 _329_ (
    .A(_064_),
    .B(_061_),
    .Y(_065_)
  );
  OR2X2 _330_ (
    .A(_059_),
    .B(_065_),
    .Y(_066_)
  );
  INVX1 _331_ (
    .A(G261gat),
    .Y(_067_)
  );
  AND2X2 _332_ (
    .A(_065_),
    .B(_059_),
    .Y(_068_)
  );
  OR2X2 _333_ (
    .A(_067_),
    .B(_068_),
    .Y(_069_)
  );
  AND2X2 _334_ (
    .A(_069_),
    .B(_066_),
    .Y(_070_)
  );
  OR2X2 _335_ (
    .A(_058_),
    .B(_070_),
    .Y(_071_)
  );
  AND2X2 _336_ (
    .A(_071_),
    .B(_057_),
    .Y(_072_)
  );
  OR2X2 _337_ (
    .A(_050_),
    .B(_072_),
    .Y(_073_)
  );
  NAND2X1 _338_ (
    .A(G189gat),
    .B(_048_),
    .Y(_074_)
  );
  AND2X2 _339_ (
    .A(_073_),
    .B(_074_),
    .Y(_075_)
  );
  OR2X2 _340_ (
    .A(_041_),
    .B(_075_),
    .Y(_076_)
  );
  AND2X2 _341_ (
    .A(_076_),
    .B(_040_),
    .Y(_077_)
  );
  XOR2X1 _342_ (
    .A(G177gat),
    .B(_018_),
    .Y(_078_)
  );
  INVX1 _343_ (
    .A(_078_),
    .Y(_079_)
  );
  OR2X2 _344_ (
    .A(_079_),
    .B(_077_),
    .Y(_080_)
  );
  AND2X2 _345_ (
    .A(_080_),
    .B(_019_),
    .Y(_081_)
  );
  NAND2X1 _346_ (
    .A(_013_),
    .B(_081_),
    .Y(_082_)
  );
  OR2X2 _347_ (
    .A(_013_),
    .B(_081_),
    .Y(_083_)
  );
  NAND3X1 _348_ (
    .A(_082_),
    .B(G219gat),
    .C(_083_),
    .Y(_084_)
  );
  AND2X2 _349_ (
    .A(G171gat),
    .B(G237gat),
    .Y(_085_)
  );
  OAI21X1 _350_ (
    .A(G246gat),
    .B(_085_),
    .C(_011_),
    .Y(_086_)
  );
  NAND3X1 _351_ (
    .A(_247_),
    .B(G55gat),
    .C(G13gat),
    .Y(_087_)
  );
  INVX1 _352_ (
    .A(_087_),
    .Y(_088_)
  );
  NAND3X1 _353_ (
    .A(_088_),
    .B(G59gat),
    .C(G68gat),
    .Y(_089_)
  );
  NAND3X1 _354_ (
    .A(G73gat),
    .B(G42gat),
    .C(G72gat),
    .Y(_090_)
  );
  NOR2X1 _355_ (
    .A(_089_),
    .B(_090_),
    .Y(_091_)
  );
  AOI22X1 _356_ (
    .A(G96gat),
    .B(G210gat),
    .C(_091_),
    .D(G171gat),
    .Y(_092_)
  );
  NAND2X1 _357_ (
    .A(_092_),
    .B(_086_),
    .Y(_093_)
  );
  AOI21X1 _358_ (
    .A(G228gat),
    .B(_012_),
    .C(_093_),
    .Y(_094_)
  );
  NAND2X1 _359_ (
    .A(_094_),
    .B(_084_),
    .Y(G880gat)
  );
  AND2X2 _360_ (
    .A(_000_),
    .B(G96gat),
    .Y(_095_)
  );
  AOI21X1 _361_ (
    .A(G138gat),
    .B(G51gat),
    .C(_008_),
    .Y(_096_)
  );
  OAI21X1 _362_ (
    .A(_042_),
    .B(_004_),
    .C(_096_),
    .Y(_097_)
  );
  OR2X2 _363_ (
    .A(_095_),
    .B(_097_),
    .Y(_098_)
  );
  NAND2X1 _364_ (
    .A(G165gat),
    .B(_098_),
    .Y(_099_)
  );
  OR2X2 _365_ (
    .A(G165gat),
    .B(_098_),
    .Y(_100_)
  );
  AND2X2 _366_ (
    .A(_099_),
    .B(_100_),
    .Y(_101_)
  );
  INVX1 _367_ (
    .A(_101_),
    .Y(_102_)
  );
  NAND2X1 _368_ (
    .A(G171gat),
    .B(_011_),
    .Y(_103_)
  );
  AND2X2 _369_ (
    .A(_083_),
    .B(_103_),
    .Y(_104_)
  );
  NAND2X1 _370_ (
    .A(_102_),
    .B(_104_),
    .Y(_105_)
  );
  INVX1 _371_ (
    .A(G219gat),
    .Y(_106_)
  );
  INVX1 _372_ (
    .A(_103_),
    .Y(_107_)
  );
  INVX1 _373_ (
    .A(_019_),
    .Y(_108_)
  );
  INVX1 _374_ (
    .A(_040_),
    .Y(_109_)
  );
  INVX1 _375_ (
    .A(_041_),
    .Y(_110_)
  );
  NOR2X1 _376_ (
    .A(_044_),
    .B(_002_),
    .Y(_111_)
  );
  INVX1 _377_ (
    .A(G121gat),
    .Y(_112_)
  );
  OAI21X1 _378_ (
    .A(_112_),
    .B(_034_),
    .C(_037_),
    .Y(_113_)
  );
  OR2X2 _379_ (
    .A(_111_),
    .B(_113_),
    .Y(_114_)
  );
  AND2X2 _380_ (
    .A(_114_),
    .B(G195gat),
    .Y(_115_)
  );
  OR2X2 _381_ (
    .A(G195gat),
    .B(_114_),
    .Y(_116_)
  );
  AND2X2 _382_ (
    .A(_022_),
    .B(G153gat),
    .Y(_117_)
  );
  AND2X2 _383_ (
    .A(_000_),
    .B(G126gat),
    .Y(_118_)
  );
  OR2X2 _384_ (
    .A(_054_),
    .B(_118_),
    .Y(_119_)
  );
  OR2X2 _385_ (
    .A(_117_),
    .B(_119_),
    .Y(_120_)
  );
  AND2X2 _386_ (
    .A(_120_),
    .B(G201gat),
    .Y(_121_)
  );
  OR2X2 _387_ (
    .A(G201gat),
    .B(_120_),
    .Y(_122_)
  );
  AND2X2 _388_ (
    .A(_122_),
    .B(G261gat),
    .Y(_123_)
  );
  OR2X2 _389_ (
    .A(_121_),
    .B(_123_),
    .Y(_124_)
  );
  AND2X2 _390_ (
    .A(_124_),
    .B(_116_),
    .Y(_125_)
  );
  OR2X2 _391_ (
    .A(_115_),
    .B(_125_),
    .Y(_126_)
  );
  AND2X2 _392_ (
    .A(_126_),
    .B(_049_),
    .Y(_127_)
  );
  INVX1 _393_ (
    .A(_074_),
    .Y(_128_)
  );
  OR2X2 _394_ (
    .A(_128_),
    .B(_127_),
    .Y(_129_)
  );
  AND2X2 _395_ (
    .A(_129_),
    .B(_110_),
    .Y(_130_)
  );
  OR2X2 _396_ (
    .A(_109_),
    .B(_130_),
    .Y(_131_)
  );
  AND2X2 _397_ (
    .A(_131_),
    .B(_078_),
    .Y(_132_)
  );
  OR2X2 _398_ (
    .A(_108_),
    .B(_132_),
    .Y(_133_)
  );
  AND2X2 _399_ (
    .A(_133_),
    .B(_012_),
    .Y(_134_)
  );
  OR2X2 _400_ (
    .A(_107_),
    .B(_134_),
    .Y(_135_)
  );
  AND2X2 _401_ (
    .A(_135_),
    .B(_101_),
    .Y(_136_)
  );
  NOR2X1 _402_ (
    .A(_136_),
    .B(_106_),
    .Y(_137_)
  );
  AND2X2 _403_ (
    .A(_137_),
    .B(_105_),
    .Y(_138_)
  );
  NAND2X1 _404_ (
    .A(G228gat),
    .B(_101_),
    .Y(_139_)
  );
  AND2X2 _405_ (
    .A(G237gat),
    .B(G165gat),
    .Y(_140_)
  );
  OAI21X1 _406_ (
    .A(G246gat),
    .B(_140_),
    .C(_098_),
    .Y(_141_)
  );
  AOI22X1 _407_ (
    .A(G210gat),
    .B(G91gat),
    .C(_091_),
    .D(G165gat),
    .Y(_142_)
  );
  NAND3X1 _408_ (
    .A(_139_),
    .B(_141_),
    .C(_142_),
    .Y(_143_)
  );
  OR2X2 _409_ (
    .A(_143_),
    .B(_138_),
    .Y(G879gat)
  );
  AND2X2 _410_ (
    .A(_000_),
    .B(G91gat),
    .Y(_144_)
  );
  INVX1 _411_ (
    .A(G143gat),
    .Y(_145_)
  );
  AOI21X1 _412_ (
    .A(G138gat),
    .B(G8gat),
    .C(_008_),
    .Y(_146_)
  );
  OAI21X1 _413_ (
    .A(_145_),
    .B(_004_),
    .C(_146_),
    .Y(_147_)
  );
  OR2X2 _414_ (
    .A(_144_),
    .B(_147_),
    .Y(_148_)
  );
  XOR2X1 _415_ (
    .A(G159gat),
    .B(_148_),
    .Y(_149_)
  );
  INVX1 _416_ (
    .A(_099_),
    .Y(_150_)
  );
  OR2X2 _417_ (
    .A(_150_),
    .B(_136_),
    .Y(_151_)
  );
  OR2X2 _418_ (
    .A(_149_),
    .B(_151_),
    .Y(_152_)
  );
  INVX1 _419_ (
    .A(_149_),
    .Y(_153_)
  );
  OR2X2 _420_ (
    .A(_102_),
    .B(_104_),
    .Y(_154_)
  );
  AND2X2 _421_ (
    .A(_154_),
    .B(_099_),
    .Y(_155_)
  );
  OR2X2 _422_ (
    .A(_153_),
    .B(_155_),
    .Y(_156_)
  );
  AND2X2 _423_ (
    .A(_156_),
    .B(G219gat),
    .Y(_157_)
  );
  AND2X2 _424_ (
    .A(_157_),
    .B(_152_),
    .Y(_158_)
  );
  NAND2X1 _425_ (
    .A(G228gat),
    .B(_149_),
    .Y(_159_)
  );
  AND2X2 _426_ (
    .A(G237gat),
    .B(G159gat),
    .Y(_160_)
  );
  OAI21X1 _427_ (
    .A(G246gat),
    .B(_160_),
    .C(_148_),
    .Y(_161_)
  );
  AOI22X1 _428_ (
    .A(G210gat),
    .B(G268gat),
    .C(_091_),
    .D(G159gat),
    .Y(_162_)
  );
  NAND3X1 _429_ (
    .A(_159_),
    .B(_161_),
    .C(_162_),
    .Y(_163_)
  );
  OR2X2 _430_ (
    .A(_163_),
    .B(_158_),
    .Y(G878gat)
  );
  NAND2X1 _431_ (
    .A(_079_),
    .B(_077_),
    .Y(_164_)
  );
  NAND3X1 _432_ (
    .A(_164_),
    .B(G219gat),
    .C(_080_),
    .Y(_165_)
  );
  AND2X2 _433_ (
    .A(_018_),
    .B(G237gat),
    .Y(_166_)
  );
  OAI21X1 _434_ (
    .A(_091_),
    .B(_166_),
    .C(G177gat),
    .Y(_167_)
  );
  AOI22X1 _435_ (
    .A(G210gat),
    .B(G101gat),
    .C(_018_),
    .D(G246gat),
    .Y(_168_)
  );
  NAND2X1 _436_ (
    .A(_168_),
    .B(_167_),
    .Y(_169_)
  );
  AOI21X1 _437_ (
    .A(G228gat),
    .B(_078_),
    .C(_169_),
    .Y(_170_)
  );
  NAND2X1 _438_ (
    .A(_170_),
    .B(_165_),
    .Y(G874gat)
  );
  NAND2X1 _439_ (
    .A(G159gat),
    .B(_148_),
    .Y(_171_)
  );
  NAND2X1 _440_ (
    .A(_171_),
    .B(_156_),
    .Y(G866gat)
  );
  OAI21X1 _441_ (
    .A(G237gat),
    .B(_057_),
    .C(_116_),
    .Y(_172_)
  );
  OAI21X1 _442_ (
    .A(_106_),
    .B(_070_),
    .C(_172_),
    .Y(_173_)
  );
  INVX1 _443_ (
    .A(G228gat),
    .Y(_174_)
  );
  NAND2X1 _444_ (
    .A(G219gat),
    .B(_071_),
    .Y(_175_)
  );
  NAND3X1 _445_ (
    .A(_175_),
    .B(_174_),
    .C(_057_),
    .Y(_176_)
  );
  NAND2X1 _446_ (
    .A(_173_),
    .B(_176_),
    .Y(_177_)
  );
  NAND2X1 _447_ (
    .A(G246gat),
    .B(_114_),
    .Y(_178_)
  );
  NAND2X1 _448_ (
    .A(G195gat),
    .B(_091_),
    .Y(_179_)
  );
  AOI22X1 _449_ (
    .A(G210gat),
    .B(G116gat),
    .C(G255gat),
    .D(G260gat),
    .Y(_180_)
  );
  AND2X2 _450_ (
    .A(_179_),
    .B(_180_),
    .Y(_181_)
  );
  NAND3X1 _451_ (
    .A(_177_),
    .B(_178_),
    .C(_181_),
    .Y(G865gat)
  );
  OAI21X1 _452_ (
    .A(G237gat),
    .B(_074_),
    .C(_049_),
    .Y(_182_)
  );
  NAND2X1 _453_ (
    .A(G219gat),
    .B(_126_),
    .Y(_183_)
  );
  NAND2X1 _454_ (
    .A(_182_),
    .B(_183_),
    .Y(_184_)
  );
  OAI21X1 _455_ (
    .A(_106_),
    .B(_127_),
    .C(_174_),
    .Y(_185_)
  );
  OAI21X1 _456_ (
    .A(_128_),
    .B(_185_),
    .C(_184_),
    .Y(_186_)
  );
  NAND2X1 _457_ (
    .A(G189gat),
    .B(_091_),
    .Y(_187_)
  );
  AOI22X1 _458_ (
    .A(G210gat),
    .B(G111gat),
    .C(G255gat),
    .D(G259gat),
    .Y(_188_)
  );
  NAND2X1 _459_ (
    .A(_188_),
    .B(_187_),
    .Y(_189_)
  );
  AOI21X1 _460_ (
    .A(G246gat),
    .B(_048_),
    .C(_189_),
    .Y(_190_)
  );
  NAND2X1 _461_ (
    .A(_190_),
    .B(_186_),
    .Y(G864gat)
  );
  NOR2X1 _462_ (
    .A(_109_),
    .B(_041_),
    .Y(_191_)
  );
  NAND2X1 _463_ (
    .A(_174_),
    .B(_128_),
    .Y(_192_)
  );
  NAND3X1 _464_ (
    .A(_185_),
    .B(_192_),
    .C(_191_),
    .Y(_193_)
  );
  NOR2X1 _465_ (
    .A(_191_),
    .B(_106_),
    .Y(_194_)
  );
  INVX1 _466_ (
    .A(G183gat),
    .Y(_195_)
  );
  AOI21X1 _467_ (
    .A(G237gat),
    .B(_039_),
    .C(_091_),
    .Y(_196_)
  );
  AOI22X1 _468_ (
    .A(G210gat),
    .B(G106gat),
    .C(_039_),
    .D(G246gat),
    .Y(_197_)
  );
  OAI21X1 _469_ (
    .A(_195_),
    .B(_196_),
    .C(_197_),
    .Y(_198_)
  );
  AOI21X1 _470_ (
    .A(_129_),
    .B(_194_),
    .C(_198_),
    .Y(_199_)
  );
  NAND2X1 _471_ (
    .A(_193_),
    .B(_199_),
    .Y(G863gat)
  );
  NOR2X1 _472_ (
    .A(_068_),
    .B(_121_),
    .Y(_200_)
  );
  XOR2X1 _473_ (
    .A(G261gat),
    .B(_200_),
    .Y(_201_)
  );
  NAND2X1 _474_ (
    .A(G219gat),
    .B(_201_),
    .Y(_202_)
  );
  NAND2X1 _475_ (
    .A(G228gat),
    .B(_200_),
    .Y(_203_)
  );
  NAND2X1 _476_ (
    .A(G237gat),
    .B(_120_),
    .Y(_204_)
  );
  OAI21X1 _477_ (
    .A(_089_),
    .B(_090_),
    .C(_204_),
    .Y(_205_)
  );
  NAND2X1 _478_ (
    .A(G246gat),
    .B(_120_),
    .Y(_206_)
  );
  AOI22X1 _479_ (
    .A(G210gat),
    .B(G121gat),
    .C(G255gat),
    .D(G267gat),
    .Y(_207_)
  );
  NAND2X1 _480_ (
    .A(_207_),
    .B(_206_),
    .Y(_208_)
  );
  AOI21X1 _481_ (
    .A(G201gat),
    .B(_205_),
    .C(_208_),
    .Y(_209_)
  );
  NAND3X1 _482_ (
    .A(_202_),
    .B(_203_),
    .C(_209_),
    .Y(G850gat)
  );
  XNOR2X1 _483_ (
    .A(G165gat),
    .B(G159gat),
    .Y(_210_)
  );
  XOR2X1 _484_ (
    .A(G130gat),
    .B(_210_),
    .Y(_211_)
  );
  XOR2X1 _485_ (
    .A(G171gat),
    .B(G177gat),
    .Y(_212_)
  );
  XOR2X1 _486_ (
    .A(_212_),
    .B(_211_),
    .Y(_213_)
  );
  XNOR2X1 _487_ (
    .A(G189gat),
    .B(G207gat),
    .Y(_214_)
  );
  XOR2X1 _488_ (
    .A(G183gat),
    .B(_214_),
    .Y(_215_)
  );
  XNOR2X1 _489_ (
    .A(G195gat),
    .B(G201gat),
    .Y(_216_)
  );
  XOR2X1 _490_ (
    .A(_216_),
    .B(_215_),
    .Y(_217_)
  );
  XNOR2X1 _491_ (
    .A(_213_),
    .B(_217_),
    .Y(G768gat)
  );
  XNOR2X1 _492_ (
    .A(G116gat),
    .B(G135gat),
    .Y(_218_)
  );
  XNOR2X1 _493_ (
    .A(G96gat),
    .B(G101gat),
    .Y(_219_)
  );
  XNOR2X1 _494_ (
    .A(_218_),
    .B(_219_),
    .Y(_220_)
  );
  XNOR2X1 _495_ (
    .A(G106gat),
    .B(G130gat),
    .Y(_221_)
  );
  XOR2X1 _496_ (
    .A(_221_),
    .B(_220_),
    .Y(_222_)
  );
  XNOR2X1 _497_ (
    .A(G121gat),
    .B(G126gat),
    .Y(_223_)
  );
  XOR2X1 _498_ (
    .A(_223_),
    .B(_222_),
    .Y(_224_)
  );
  XNOR2X1 _499_ (
    .A(G91gat),
    .B(G111gat),
    .Y(_225_)
  );
  XOR2X1 _500_ (
    .A(_225_),
    .B(_224_),
    .Y(G767gat)
  );
  INVX1 _501_ (
    .A(G89gat),
    .Y(_226_)
  );
  INVX1 _502_ (
    .A(G88gat),
    .Y(_227_)
  );
  INVX1 _503_ (
    .A(G87gat),
    .Y(_228_)
  );
  AOI21X1 _504_ (
    .A(_227_),
    .B(_228_),
    .C(_226_),
    .Y(G450gat)
  );
  INVX1 _505_ (
    .A(G74gat),
    .Y(_229_)
  );
  NOR2X1 _506_ (
    .A(_089_),
    .B(_229_),
    .Y(G449gat)
  );
  NAND2X1 _507_ (
    .A(G68gat),
    .B(G29gat),
    .Y(_230_)
  );
  NOR2X1 _508_ (
    .A(_087_),
    .B(_230_),
    .Y(G448gat)
  );
  NAND3X1 _509_ (
    .A(G42gat),
    .B(G29gat),
    .C(G36gat),
    .Y(_231_)
  );
  INVX1 _510_ (
    .A(_231_),
    .Y(G390gat)
  );
  INVX1 _511_ (
    .A(G13gat),
    .Y(_232_)
  );
  INVX1 _512_ (
    .A(_239_),
    .Y(_233_)
  );
  NOR3X1 _513_ (
    .A(_233_),
    .B(_005_),
    .C(_232_),
    .Y(_234_)
  );
  NAND2X1 _514_ (
    .A(G390gat),
    .B(_234_),
    .Y(G446gat)
  );
  INVX1 _515_ (
    .A(G90gat),
    .Y(_235_)
  );
  AOI21X1 _516_ (
    .A(_227_),
    .B(_228_),
    .C(_235_),
    .Y(G423gat)
  );
  NAND3X1 _517_ (
    .A(G42gat),
    .B(G59gat),
    .C(G36gat),
    .Y(G422gat)
  );
  NAND3X1 _518_ (
    .A(G80gat),
    .B(G59gat),
    .C(G36gat),
    .Y(G421gat)
  );
  NAND2X1 _519_ (
    .A(G80gat),
    .B(_030_),
    .Y(G420gat)
  );
  NAND2X1 _520_ (
    .A(_231_),
    .B(_234_),
    .Y(G419gat)
  );
  INVX1 _521_ (
    .A(_247_),
    .Y(_236_)
  );
  NOR3X1 _522_ (
    .A(_236_),
    .B(_005_),
    .C(_232_),
    .Y(G418gat)
  );
  AND2X2 _523_ (
    .A(G85gat),
    .B(G86gat),
    .Y(G391gat)
  );
  INVX1 _524_ (
    .A(G80gat),
    .Y(_237_)
  );
  NAND2X1 _525_ (
    .A(G29gat),
    .B(G36gat),
    .Y(_238_)
  );
  NOR2X1 _526_ (
    .A(_238_),
    .B(_237_),
    .Y(G389gat)
  );
  AND2X2 _527_ (
    .A(_006_),
    .B(G42gat),
    .Y(G388gat)
  );
endmodule
