/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module newcpla2(\CPIPE2s<0> , \CPIPE2s<1> , \CPIPE2s<2> , \CPIPE2s<3> , \CPIPE2s<4> , \CPIPE2s<5> , \CPIPE2s<7> , writeRFaccess2, lastPCtobusD1, busDtobusB2, busDtobusA2, DSTtobusD2, nillonreturn, pLOADwrite, opc2load, DSTvalid, pbusDtoINA);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  input \CPIPE2s<0> ;
  input \CPIPE2s<1> ;
  input \CPIPE2s<2> ;
  input \CPIPE2s<3> ;
  input \CPIPE2s<4> ;
  input \CPIPE2s<5> ;
  input \CPIPE2s<7> ;
  output DSTtobusD2;
  output DSTvalid;
  output busDtobusA2;
  output busDtobusB2;
  output lastPCtobusD1;
  output nillonreturn;
  output opc2load;
  output pLOADwrite;
  output pbusDtoINA;
  output writeRFaccess2;
  NAND2X1 _43_ (
    .A(\CPIPE2s<7> ),
    .B(\CPIPE2s<4> ),
    .Y(_00_)
  );
  INVX1 _44_ (
    .A(\CPIPE2s<5> ),
    .Y(_01_)
  );
  NAND2X1 _45_ (
    .A(\CPIPE2s<3> ),
    .B(_01_),
    .Y(_02_)
  );
  OR2X2 _46_ (
    .A(\CPIPE2s<0> ),
    .B(_02_),
    .Y(_03_)
  );
  OR2X2 _47_ (
    .A(\CPIPE2s<2> ),
    .B(\CPIPE2s<1> ),
    .Y(_04_)
  );
  OR2X2 _48_ (
    .A(\CPIPE2s<0> ),
    .B(_04_),
    .Y(_05_)
  );
  INVX1 _49_ (
    .A(\CPIPE2s<2> ),
    .Y(_06_)
  );
  NOR2X1 _50_ (
    .A(_06_),
    .B(\CPIPE2s<1> ),
    .Y(_07_)
  );
  AOI22X1 _51_ (
    .A(\CPIPE2s<5> ),
    .B(_05_),
    .C(_07_),
    .D(\CPIPE2s<3> ),
    .Y(_08_)
  );
  AOI21X1 _52_ (
    .A(_03_),
    .B(_08_),
    .C(_00_),
    .Y(pbusDtoINA)
  );
  INVX1 _53_ (
    .A(\CPIPE2s<7> ),
    .Y(_09_)
  );
  INVX1 _54_ (
    .A(\CPIPE2s<4> ),
    .Y(_10_)
  );
  INVX1 _55_ (
    .A(\CPIPE2s<3> ),
    .Y(_11_)
  );
  NAND2X1 _56_ (
    .A(\CPIPE2s<2> ),
    .B(_11_),
    .Y(_12_)
  );
  NAND2X1 _57_ (
    .A(_10_),
    .B(_12_),
    .Y(_13_)
  );
  NOR2X1 _58_ (
    .A(_01_),
    .B(\CPIPE2s<3> ),
    .Y(_14_)
  );
  AND2X2 _59_ (
    .A(_01_),
    .B(\CPIPE2s<3> ),
    .Y(_15_)
  );
  OR2X2 _60_ (
    .A(_10_),
    .B(_15_),
    .Y(_16_)
  );
  AND2X2 _61_ (
    .A(_16_),
    .B(\CPIPE2s<0> ),
    .Y(_17_)
  );
  AND2X2 _62_ (
    .A(_06_),
    .B(\CPIPE2s<4> ),
    .Y(_18_)
  );
  OR2X2 _63_ (
    .A(\CPIPE2s<1> ),
    .B(_18_),
    .Y(_19_)
  );
  AOI21X1 _64_ (
    .A(_19_),
    .B(_17_),
    .C(_14_),
    .Y(_20_)
  );
  AOI21X1 _65_ (
    .A(_13_),
    .B(_20_),
    .C(_09_),
    .Y(DSTvalid)
  );
  INVX1 _66_ (
    .A(_14_),
    .Y(_21_)
  );
  NOR2X1 _67_ (
    .A(_21_),
    .B(_00_),
    .Y(pLOADwrite)
  );
  NOR3X1 _68_ (
    .A(_21_),
    .B(_00_),
    .C(_05_),
    .Y(opc2load)
  );
  NAND2X1 _69_ (
    .A(\CPIPE2s<1> ),
    .B(\CPIPE2s<7> ),
    .Y(_22_)
  );
  NOR3X1 _70_ (
    .A(_02_),
    .B(\CPIPE2s<4> ),
    .C(_22_),
    .Y(nillonreturn)
  );
  NAND2X1 _71_ (
    .A(\CPIPE2s<0> ),
    .B(_10_),
    .Y(_23_)
  );
  OR2X2 _72_ (
    .A(_12_),
    .B(_23_),
    .Y(_24_)
  );
  NAND2X1 _73_ (
    .A(_01_),
    .B(_22_),
    .Y(_25_)
  );
  AOI21X1 _74_ (
    .A(\CPIPE2s<7> ),
    .B(_24_),
    .C(_25_),
    .Y(lastPCtobusD1)
  );
  NAND3X1 _75_ (
    .A(_11_),
    .B(\CPIPE2s<2> ),
    .C(\CPIPE2s<5> ),
    .Y(_26_)
  );
  AOI21X1 _76_ (
    .A(_26_),
    .B(_02_),
    .C(_22_),
    .Y(_27_)
  );
  OAI21X1 _77_ (
    .A(_04_),
    .B(_11_),
    .C(\CPIPE2s<0> ),
    .Y(_28_)
  );
  AND2X2 _78_ (
    .A(_28_),
    .B(\CPIPE2s<5> ),
    .Y(_29_)
  );
  AND2X2 _79_ (
    .A(_29_),
    .B(\CPIPE2s<7> ),
    .Y(_30_)
  );
  OR2X2 _80_ (
    .A(_30_),
    .B(_27_),
    .Y(_31_)
  );
  AND2X2 _81_ (
    .A(_31_),
    .B(_10_),
    .Y(DSTtobusD2)
  );
  OR2X2 _82_ (
    .A(lastPCtobusD1),
    .B(DSTtobusD2),
    .Y(busDtobusA2)
  );
  AOI21X1 _83_ (
    .A(\CPIPE2s<2> ),
    .B(_01_),
    .C(\CPIPE2s<4> ),
    .Y(_32_)
  );
  OR2X2 _84_ (
    .A(_32_),
    .B(_14_),
    .Y(_33_)
  );
  AND2X2 _85_ (
    .A(_33_),
    .B(_02_),
    .Y(_34_)
  );
  AND2X2 _86_ (
    .A(_15_),
    .B(_10_),
    .Y(_35_)
  );
  OR2X2 _87_ (
    .A(\CPIPE2s<0> ),
    .B(_35_),
    .Y(_36_)
  );
  AND2X2 _88_ (
    .A(_16_),
    .B(\CPIPE2s<1> ),
    .Y(_37_)
  );
  AND2X2 _89_ (
    .A(_36_),
    .B(_37_),
    .Y(_38_)
  );
  AND2X2 _90_ (
    .A(_17_),
    .B(_18_),
    .Y(_39_)
  );
  OR2X2 _91_ (
    .A(_39_),
    .B(_38_),
    .Y(_40_)
  );
  OR2X2 _92_ (
    .A(_34_),
    .B(_40_),
    .Y(_41_)
  );
  AND2X2 _93_ (
    .A(_41_),
    .B(\CPIPE2s<7> ),
    .Y(_42_)
  );
  OR2X2 _94_ (
    .A(lastPCtobusD1),
    .B(_42_),
    .Y(writeRFaccess2)
  );
  assign busDtobusB2 = busDtobusA2;
endmodule
