/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module wim(v0, v1, v2, v3, \v4.0 , \v4.1 , \v4.2 , \v4.3 , \v4.4 , \v4.5 , \v4.6 );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input v0;
  input v1;
  input v2;
  input v3;
  output \v4.0 ;
  output \v4.1 ;
  output \v4.2 ;
  output \v4.3 ;
  output \v4.4 ;
  output \v4.5 ;
  output \v4.6 ;
  OR2X2 _17_ (
    .A(v2),
    .B(v1),
    .Y(_00_)
  );
  INVX1 _18_ (
    .A(v0),
    .Y(_01_)
  );
  AND2X2 _19_ (
    .A(_01_),
    .B(v3),
    .Y(_02_)
  );
  OR2X2 _20_ (
    .A(_00_),
    .B(_02_),
    .Y(_03_)
  );
  INVX1 _21_ (
    .A(_03_),
    .Y(_04_)
  );
  OR2X2 _22_ (
    .A(v2),
    .B(v3),
    .Y(_05_)
  );
  NAND2X1 _23_ (
    .A(v2),
    .B(v3),
    .Y(_06_)
  );
  AND2X2 _24_ (
    .A(_06_),
    .B(v1),
    .Y(_07_)
  );
  AND2X2 _25_ (
    .A(_07_),
    .B(_05_),
    .Y(_08_)
  );
  INVX1 _26_ (
    .A(v1),
    .Y(_09_)
  );
  AND2X2 _27_ (
    .A(_09_),
    .B(v2),
    .Y(_10_)
  );
  OR2X2 _28_ (
    .A(_10_),
    .B(_08_),
    .Y(_11_)
  );
  AND2X2 _29_ (
    .A(_11_),
    .B(_01_),
    .Y(_12_)
  );
  OR2X2 _30_ (
    .A(_04_),
    .B(_12_),
    .Y(\v4.6 )
  );
  INVX1 _31_ (
    .A(_02_),
    .Y(_13_)
  );
  NAND2X1 _32_ (
    .A(v1),
    .B(_01_),
    .Y(_14_)
  );
  NAND3X1 _33_ (
    .A(_13_),
    .B(_00_),
    .C(_14_),
    .Y(\v4.5 )
  );
  XOR2X1 _34_ (
    .A(v0),
    .B(_00_),
    .Y(\v4.4 )
  );
  NAND2X1 _35_ (
    .A(v2),
    .B(_01_),
    .Y(_15_)
  );
  AOI21X1 _36_ (
    .A(_00_),
    .B(_15_),
    .C(v3),
    .Y(\v4.3 )
  );
  AOI21X1 _37_ (
    .A(v0),
    .B(_00_),
    .C(_08_),
    .Y(\v4.2 )
  );
  AND2X2 _38_ (
    .A(v2),
    .B(v3),
    .Y(_16_)
  );
  AOI21X1 _39_ (
    .A(_03_),
    .B(_14_),
    .C(_16_),
    .Y(\v4.1 )
  );
  NAND3X1 _40_ (
    .A(_14_),
    .B(_03_),
    .C(_15_),
    .Y(\v4.0 )
  );
endmodule
