/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module newapla2(\DST2s<0> , \DST2s<1> , \DST2s<2> , \DST2s<3> , \DST2s<4> , DSTvalid, writetoSHA1, writetoSHB1, writetoPSW1, writetoCWP1, pwritetoTB, pwritetoSWP, pwritetoPC);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  input \DST2s<0> ;
  input \DST2s<1> ;
  input \DST2s<2> ;
  input \DST2s<3> ;
  input \DST2s<4> ;
  input DSTvalid;
  output pwritetoPC;
  output pwritetoSWP;
  output pwritetoTB;
  output writetoCWP1;
  output writetoPSW1;
  output writetoSHA1;
  output writetoSHB1;
  INVX1 _12_ (
    .A(\DST2s<2> ),
    .Y(_00_)
  );
  INVX1 _13_ (
    .A(\DST2s<3> ),
    .Y(_01_)
  );
  AND2X2 _14_ (
    .A(_01_),
    .B(\DST2s<4> ),
    .Y(_02_)
  );
  AND2X2 _15_ (
    .A(_02_),
    .B(DSTvalid),
    .Y(_03_)
  );
  AND2X2 _16_ (
    .A(_03_),
    .B(_00_),
    .Y(_04_)
  );
  INVX1 _17_ (
    .A(\DST2s<1> ),
    .Y(_05_)
  );
  AND2X2 _18_ (
    .A(_05_),
    .B(\DST2s<0> ),
    .Y(_06_)
  );
  AND2X2 _19_ (
    .A(_04_),
    .B(_06_),
    .Y(pwritetoPC)
  );
  AND2X2 _20_ (
    .A(_03_),
    .B(\DST2s<2> ),
    .Y(_07_)
  );
  NOR2X1 _21_ (
    .A(\DST2s<1> ),
    .B(\DST2s<0> ),
    .Y(_08_)
  );
  AND2X2 _22_ (
    .A(_07_),
    .B(_08_),
    .Y(pwritetoSWP)
  );
  AND2X2 _23_ (
    .A(_07_),
    .B(_06_),
    .Y(pwritetoTB)
  );
  INVX1 _24_ (
    .A(\DST2s<0> ),
    .Y(_09_)
  );
  AND2X2 _25_ (
    .A(_09_),
    .B(\DST2s<1> ),
    .Y(_10_)
  );
  AND2X2 _26_ (
    .A(_07_),
    .B(_10_),
    .Y(writetoCWP1)
  );
  AND2X2 _27_ (
    .A(\DST2s<1> ),
    .B(\DST2s<0> ),
    .Y(_11_)
  );
  AND2X2 _28_ (
    .A(_07_),
    .B(_11_),
    .Y(writetoPSW1)
  );
  AND2X2 _29_ (
    .A(_04_),
    .B(_10_),
    .Y(writetoSHB1)
  );
  AND2X2 _30_ (
    .A(_04_),
    .B(_11_),
    .Y(writetoSHA1)
  );
endmodule
