/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module newxcpla1(\CPIPE1s<0> , \CPIPE1s<1> , \CPIPE1s<2> , \CPIPE1s<3> , \CPIPE1s<4> , \CPIPE1s<5> , \CPIPE1s<7> , \CPIPE1s<8> , RESET, selaluSUM, aluCINbar1, aluselSR, selaluAND, selaluOR, selaluXOR, selBIbar, storeSXT, pbusLtoINB, RD_WR, predecodeEA, pSTOREwrite
, pLOADLtobusL, pSXTtobusL, byteEX, \.p , \43 , \--------1 , \00000000000000000010000 , \---0--11- , \00000000100001000000000 , \---1111-- , \10000000000010010000000 );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  output \--------1 ;
  output \---0--11- ;
  output \---1111-- ;
  output \.p ;
  output \00000000000000000010000 ;
  output \00000000100001000000000 ;
  output \10000000000010010000000 ;
  output \43 ;
  input \CPIPE1s<0> ;
  input \CPIPE1s<1> ;
  input \CPIPE1s<2> ;
  input \CPIPE1s<3> ;
  input \CPIPE1s<4> ;
  input \CPIPE1s<5> ;
  input \CPIPE1s<7> ;
  input \CPIPE1s<8> ;
  output RD_WR;
  input RESET;
  output aluCINbar1;
  output aluselSR;
  output byteEX;
  output pLOADLtobusL;
  output pSTOREwrite;
  output pSXTtobusL;
  output pbusLtoINB;
  output predecodeEA;
  output selBIbar;
  output selaluAND;
  output selaluOR;
  output selaluSUM;
  output selaluXOR;
  output storeSXT;
  INVX1 _066_ (
    .A(\CPIPE1s<2> ),
    .Y(_012_)
  );
  OR2X2 _067_ (
    .A(\CPIPE1s<1> ),
    .B(_012_),
    .Y(_013_)
  );
  INVX1 _068_ (
    .A(\CPIPE1s<3> ),
    .Y(_014_)
  );
  OR2X2 _069_ (
    .A(\CPIPE1s<5> ),
    .B(_014_),
    .Y(_015_)
  );
  NAND2X1 _070_ (
    .A(\CPIPE1s<4> ),
    .B(\CPIPE1s<7> ),
    .Y(_016_)
  );
  OR2X2 _071_ (
    .A(RESET),
    .B(_016_),
    .Y(_017_)
  );
  NOR3X1 _072_ (
    .A(_017_),
    .B(_013_),
    .C(_015_),
    .Y(\10000000000010010000000 )
  );
  INVX1 _073_ (
    .A(_017_),
    .Y(_018_)
  );
  INVX1 _074_ (
    .A(\CPIPE1s<5> ),
    .Y(_019_)
  );
  AND2X2 _075_ (
    .A(_019_),
    .B(\CPIPE1s<3> ),
    .Y(_020_)
  );
  INVX1 _076_ (
    .A(\CPIPE1s<0> ),
    .Y(_021_)
  );
  AND2X2 _077_ (
    .A(_021_),
    .B(\CPIPE1s<1> ),
    .Y(_022_)
  );
  AND2X2 _078_ (
    .A(_022_),
    .B(\CPIPE1s<2> ),
    .Y(_023_)
  );
  AND2X2 _079_ (
    .A(_023_),
    .B(_020_),
    .Y(_024_)
  );
  NOR2X1 _080_ (
    .A(_019_),
    .B(\CPIPE1s<3> ),
    .Y(_025_)
  );
  OR2X2 _081_ (
    .A(\CPIPE1s<0> ),
    .B(\CPIPE1s<2> ),
    .Y(_026_)
  );
  OR2X2 _082_ (
    .A(\CPIPE1s<1> ),
    .B(_026_),
    .Y(_027_)
  );
  AND2X2 _083_ (
    .A(_025_),
    .B(_027_),
    .Y(_028_)
  );
  OR2X2 _084_ (
    .A(_024_),
    .B(_028_),
    .Y(_029_)
  );
  AND2X2 _085_ (
    .A(_029_),
    .B(_018_),
    .Y(\---1111-- )
  );
  NOR3X1 _086_ (
    .A(_017_),
    .B(_015_),
    .C(_027_),
    .Y(\00000000100001000000000 )
  );
  AND2X2 _087_ (
    .A(_027_),
    .B(\CPIPE1s<3> ),
    .Y(_030_)
  );
  AOI21X1 _088_ (
    .A(_019_),
    .B(_026_),
    .C(_017_),
    .Y(_031_)
  );
  AND2X2 _089_ (
    .A(_031_),
    .B(_030_),
    .Y(\---0--11- )
  );
  AND2X2 _090_ (
    .A(\CPIPE1s<4> ),
    .B(\CPIPE1s<7> ),
    .Y(_032_)
  );
  AOI22X1 _091_ (
    .A(\CPIPE1s<7> ),
    .B(_019_),
    .C(_027_),
    .D(_032_),
    .Y(_033_)
  );
  AND2X2 _092_ (
    .A(_014_),
    .B(\CPIPE1s<4> ),
    .Y(_034_)
  );
  OR2X2 _093_ (
    .A(_021_),
    .B(_034_),
    .Y(_035_)
  );
  OR2X2 _094_ (
    .A(_013_),
    .B(_035_),
    .Y(_036_)
  );
  AND2X2 _095_ (
    .A(\CPIPE1s<0> ),
    .B(\CPIPE1s<4> ),
    .Y(_037_)
  );
  OR2X2 _096_ (
    .A(_037_),
    .B(_014_),
    .Y(_038_)
  );
  AND2X2 _097_ (
    .A(_038_),
    .B(_019_),
    .Y(_039_)
  );
  AND2X2 _098_ (
    .A(_036_),
    .B(_039_),
    .Y(_040_)
  );
  OR2X2 _099_ (
    .A(_033_),
    .B(_040_),
    .Y(\00000000000000000010000 )
  );
  AND2X2 _100_ (
    .A(\CPIPE1s<5> ),
    .B(\CPIPE1s<3> ),
    .Y(_041_)
  );
  AND2X2 _101_ (
    .A(_012_),
    .B(_041_),
    .Y(_042_)
  );
  OR2X2 _102_ (
    .A(\CPIPE1s<0> ),
    .B(_042_),
    .Y(_043_)
  );
  INVX1 _103_ (
    .A(\CPIPE1s<4> ),
    .Y(_044_)
  );
  OR2X2 _104_ (
    .A(\CPIPE1s<3> ),
    .B(_012_),
    .Y(_045_)
  );
  AND2X2 _105_ (
    .A(_045_),
    .B(_044_),
    .Y(_046_)
  );
  AND2X2 _106_ (
    .A(_043_),
    .B(_046_),
    .Y(_047_)
  );
  INVX1 _107_ (
    .A(\CPIPE1s<1> ),
    .Y(_048_)
  );
  AND2X2 _108_ (
    .A(_048_),
    .B(\CPIPE1s<0> ),
    .Y(_049_)
  );
  NAND2X1 _109_ (
    .A(\CPIPE1s<5> ),
    .B(\CPIPE1s<7> ),
    .Y(_050_)
  );
  OR2X2 _110_ (
    .A(_050_),
    .B(_034_),
    .Y(_051_)
  );
  OR2X2 _111_ (
    .A(_049_),
    .B(_051_),
    .Y(_052_)
  );
  OR2X2 _112_ (
    .A(_052_),
    .B(_047_),
    .Y(selaluSUM)
  );
  AND2X2 _113_ (
    .A(_044_),
    .B(\CPIPE1s<7> ),
    .Y(_053_)
  );
  AND2X2 _114_ (
    .A(_025_),
    .B(_053_),
    .Y(_054_)
  );
  OR2X2 _115_ (
    .A(_054_),
    .B(selaluSUM),
    .Y(\.p )
  );
  INVX1 _116_ (
    .A(_041_),
    .Y(_055_)
  );
  NAND2X1 _117_ (
    .A(\CPIPE1s<7> ),
    .B(_044_),
    .Y(_056_)
  );
  NAND3X1 _118_ (
    .A(_021_),
    .B(\CPIPE1s<2> ),
    .C(_048_),
    .Y(_057_)
  );
  NOR3X1 _119_ (
    .A(_057_),
    .B(_055_),
    .C(_056_),
    .Y(byteEX)
  );
  NAND3X1 _120_ (
    .A(_032_),
    .B(\CPIPE1s<5> ),
    .C(\CPIPE1s<3> ),
    .Y(RD_WR)
  );
  NOR2X1 _121_ (
    .A(RD_WR),
    .B(_027_),
    .Y(pSTOREwrite)
  );
  NOR2X1 _122_ (
    .A(_015_),
    .B(_016_),
    .Y(_058_)
  );
  AOI21X1 _123_ (
    .A(\CPIPE1s<0> ),
    .B(_012_),
    .C(\CPIPE1s<1> ),
    .Y(_059_)
  );
  AND2X2 _124_ (
    .A(_058_),
    .B(_059_),
    .Y(predecodeEA)
  );
  NAND2X1 _125_ (
    .A(\CPIPE1s<5> ),
    .B(_032_),
    .Y(\--------1 )
  );
  INVX1 _126_ (
    .A(\CPIPE1s<8> ),
    .Y(_060_)
  );
  OAI21X1 _127_ (
    .A(_019_),
    .B(_044_),
    .C(\CPIPE1s<7> ),
    .Y(_061_)
  );
  NOR2X1 _128_ (
    .A(_061_),
    .B(_060_),
    .Y(pSXTtobusL)
  );
  OAI21X1 _129_ (
    .A(_060_),
    .B(_061_),
    .C(\CPIPE1s<7> ),
    .Y(pbusLtoINB)
  );
  NOR3X1 _130_ (
    .A(_015_),
    .B(_016_),
    .C(_026_),
    .Y(storeSXT)
  );
  OR2X2 _131_ (
    .A(\CPIPE1s<4> ),
    .B(_042_),
    .Y(_062_)
  );
  AND2X2 _132_ (
    .A(_062_),
    .B(_022_),
    .Y(_063_)
  );
  OR2X2 _133_ (
    .A(_026_),
    .B(_019_),
    .Y(_064_)
  );
  AND2X2 _134_ (
    .A(_015_),
    .B(\CPIPE1s<4> ),
    .Y(_065_)
  );
  AND2X2 _135_ (
    .A(_065_),
    .B(_064_),
    .Y(_000_)
  );
  OR2X2 _136_ (
    .A(_000_),
    .B(_063_),
    .Y(_001_)
  );
  AND2X2 _137_ (
    .A(_001_),
    .B(\CPIPE1s<7> ),
    .Y(selBIbar)
  );
  NAND2X1 _138_ (
    .A(\CPIPE1s<5> ),
    .B(_014_),
    .Y(_002_)
  );
  NOR3X1 _139_ (
    .A(_002_),
    .B(_056_),
    .C(_057_),
    .Y(selaluXOR)
  );
  NAND3X1 _140_ (
    .A(\CPIPE1s<0> ),
    .B(\CPIPE1s<1> ),
    .C(\CPIPE1s<2> ),
    .Y(_003_)
  );
  NOR3X1 _141_ (
    .A(_002_),
    .B(_003_),
    .C(_056_),
    .Y(selaluOR)
  );
  AND2X2 _142_ (
    .A(_054_),
    .B(_023_),
    .Y(selaluAND)
  );
  INVX1 _143_ (
    .A(_026_),
    .Y(_004_)
  );
  AND2X2 _144_ (
    .A(_054_),
    .B(_004_),
    .Y(aluselSR)
  );
  NAND2X1 _145_ (
    .A(\CPIPE1s<1> ),
    .B(_021_),
    .Y(_005_)
  );
  AOI21X1 _146_ (
    .A(_041_),
    .B(_012_),
    .C(\CPIPE1s<4> ),
    .Y(_006_)
  );
  OR2X2 _147_ (
    .A(_005_),
    .B(_006_),
    .Y(_007_)
  );
  AND2X2 _148_ (
    .A(_004_),
    .B(\CPIPE1s<5> ),
    .Y(_008_)
  );
  OR2X2 _149_ (
    .A(_044_),
    .B(_020_),
    .Y(_009_)
  );
  OR2X2 _150_ (
    .A(_009_),
    .B(_008_),
    .Y(_010_)
  );
  AND2X2 _151_ (
    .A(_007_),
    .B(_010_),
    .Y(_011_)
  );
  AND2X2 _152_ (
    .A(_011_),
    .B(\CPIPE1s<7> ),
    .Y(aluCINbar1)
  );
  assign \43  = \--------1 ;
  assign pLOADLtobusL = 1'h0;
endmodule
