/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module pcler8(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u
, v, w, x, y, z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0
, q0, r0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  input a;
  input a0;
  input b;
  output b0;
  input c;
  output c0;
  input d;
  output d0;
  input e;
  output e0;
  input f;
  output f0;
  input g;
  output g0;
  input h;
  output h0;
  input i;
  output i0;
  input j;
  output j0;
  input k;
  output k0;
  input l;
  output l0;
  input m;
  output m0;
  input n;
  output n0;
  input o;
  output o0;
  input p;
  output p0;
  input q;
  output q0;
  input r;
  output r0;
  input s;
  input t;
  input u;
  input v;
  input w;
  input x;
  input y;
  input z;
  AND2X2 _049_ (
    .A(h),
    .B(i),
    .Y(j0)
  );
  INVX1 _050_ (
    .A(s),
    .Y(_008_)
  );
  AND2X2 _051_ (
    .A(u),
    .B(t),
    .Y(_009_)
  );
  AND2X2 _052_ (
    .A(_009_),
    .B(v),
    .Y(_010_)
  );
  AND2X2 _053_ (
    .A(_010_),
    .B(w),
    .Y(_011_)
  );
  AND2X2 _054_ (
    .A(_011_),
    .B(x),
    .Y(_012_)
  );
  AND2X2 _055_ (
    .A(_012_),
    .B(y),
    .Y(_013_)
  );
  AND2X2 _056_ (
    .A(_013_),
    .B(z),
    .Y(_014_)
  );
  NAND3X1 _057_ (
    .A(_014_),
    .B(a0),
    .C(_008_),
    .Y(_015_)
  );
  INVX1 _058_ (
    .A(j),
    .Y(_016_)
  );
  NOR3X1 _059_ (
    .A(_016_),
    .B(i),
    .C(k),
    .Y(_017_)
  );
  OR2X2 _060_ (
    .A(a0),
    .B(_014_),
    .Y(_018_)
  );
  AND2X2 _061_ (
    .A(_018_),
    .B(_017_),
    .Y(_019_)
  );
  AND2X2 _062_ (
    .A(_015_),
    .B(_019_),
    .Y(_020_)
  );
  OR2X2 _063_ (
    .A(j0),
    .B(_020_),
    .Y(r0)
  );
  AND2X2 _064_ (
    .A(_014_),
    .B(a0),
    .Y(_021_)
  );
  AND2X2 _065_ (
    .A(_021_),
    .B(_017_),
    .Y(b0)
  );
  AND2X2 _066_ (
    .A(b0),
    .B(r),
    .Y(_022_)
  );
  AND2X2 _067_ (
    .A(i),
    .B(g),
    .Y(i0)
  );
  OR2X2 _068_ (
    .A(z),
    .B(_013_),
    .Y(_023_)
  );
  NAND3X1 _069_ (
    .A(_012_),
    .B(z),
    .C(y),
    .Y(_024_)
  );
  AND2X2 _070_ (
    .A(_024_),
    .B(_017_),
    .Y(_025_)
  );
  AND2X2 _071_ (
    .A(_025_),
    .B(_023_),
    .Y(_026_)
  );
  OR2X2 _072_ (
    .A(i0),
    .B(_026_),
    .Y(_027_)
  );
  OR2X2 _073_ (
    .A(_022_),
    .B(_027_),
    .Y(q0)
  );
  AND2X2 _074_ (
    .A(b0),
    .B(q),
    .Y(_028_)
  );
  AND2X2 _075_ (
    .A(i),
    .B(f),
    .Y(h0)
  );
  OR2X2 _076_ (
    .A(y),
    .B(_012_),
    .Y(_029_)
  );
  INVX1 _077_ (
    .A(i),
    .Y(_030_)
  );
  INVX1 _078_ (
    .A(k),
    .Y(_031_)
  );
  NAND3X1 _079_ (
    .A(_030_),
    .B(j),
    .C(_031_),
    .Y(_032_)
  );
  AOI21X1 _080_ (
    .A(y),
    .B(_012_),
    .C(_032_),
    .Y(_033_)
  );
  AND2X2 _081_ (
    .A(_033_),
    .B(_029_),
    .Y(_034_)
  );
  OR2X2 _082_ (
    .A(h0),
    .B(_034_),
    .Y(_035_)
  );
  OR2X2 _083_ (
    .A(_028_),
    .B(_035_),
    .Y(p0)
  );
  AND2X2 _084_ (
    .A(b0),
    .B(p),
    .Y(_036_)
  );
  NAND2X1 _085_ (
    .A(i),
    .B(e),
    .Y(_037_)
  );
  NOR2X1 _086_ (
    .A(_011_),
    .B(x),
    .Y(_038_)
  );
  OR2X2 _087_ (
    .A(_012_),
    .B(_032_),
    .Y(_039_)
  );
  OAI21X1 _088_ (
    .A(_039_),
    .B(_038_),
    .C(_037_),
    .Y(_040_)
  );
  OR2X2 _089_ (
    .A(_036_),
    .B(_040_),
    .Y(o0)
  );
  INVX1 _090_ (
    .A(_037_),
    .Y(g0)
  );
  AND2X2 _091_ (
    .A(b0),
    .B(o),
    .Y(_041_)
  );
  AND2X2 _092_ (
    .A(i),
    .B(d),
    .Y(f0)
  );
  NOR2X1 _093_ (
    .A(_010_),
    .B(w),
    .Y(_042_)
  );
  NOR3X1 _094_ (
    .A(_042_),
    .B(_011_),
    .C(_032_),
    .Y(_043_)
  );
  OR2X2 _095_ (
    .A(f0),
    .B(_043_),
    .Y(_044_)
  );
  OR2X2 _096_ (
    .A(_041_),
    .B(_044_),
    .Y(n0)
  );
  AND2X2 _097_ (
    .A(b0),
    .B(n),
    .Y(_045_)
  );
  AND2X2 _098_ (
    .A(i),
    .B(c),
    .Y(e0)
  );
  NOR2X1 _099_ (
    .A(_009_),
    .B(v),
    .Y(_046_)
  );
  NOR3X1 _100_ (
    .A(_032_),
    .B(_010_),
    .C(_046_),
    .Y(_047_)
  );
  OR2X2 _101_ (
    .A(e0),
    .B(_047_),
    .Y(_048_)
  );
  OR2X2 _102_ (
    .A(_048_),
    .B(_045_),
    .Y(m0)
  );
  AND2X2 _103_ (
    .A(i),
    .B(b),
    .Y(d0)
  );
  XOR2X1 _104_ (
    .A(u),
    .B(t),
    .Y(_000_)
  );
  AND2X2 _105_ (
    .A(_021_),
    .B(m),
    .Y(_001_)
  );
  OR2X2 _106_ (
    .A(_000_),
    .B(_001_),
    .Y(_002_)
  );
  AND2X2 _107_ (
    .A(_002_),
    .B(_017_),
    .Y(_003_)
  );
  OR2X2 _108_ (
    .A(d0),
    .B(_003_),
    .Y(l0)
  );
  AND2X2 _109_ (
    .A(i),
    .B(a),
    .Y(c0)
  );
  INVX1 _110_ (
    .A(t),
    .Y(_004_)
  );
  AND2X2 _111_ (
    .A(_021_),
    .B(l),
    .Y(_005_)
  );
  OR2X2 _112_ (
    .A(_004_),
    .B(_005_),
    .Y(_006_)
  );
  AND2X2 _113_ (
    .A(_006_),
    .B(_017_),
    .Y(_007_)
  );
  OR2X2 _114_ (
    .A(c0),
    .B(_007_),
    .Y(k0)
  );
endmodule
