/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module pm1(a, b, c, d, e, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v
, w, x, y, z, a0, b0, c0, d0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  input a;
  output a0;
  input b;
  output b0;
  input c;
  output c0;
  input d;
  output d0;
  input e;
  input g;
  input h;
  input i;
  input j;
  input k;
  input l;
  input m;
  input n;
  input o;
  input p;
  input q;
  output r;
  output s;
  output t;
  output u;
  output v;
  output w;
  output x;
  output y;
  output z;
  INVX1 _22_ (
    .A(q),
    .Y(y)
  );
  INVX1 _23_ (
    .A(o),
    .Y(w)
  );
  INVX1 _24_ (
    .A(p),
    .Y(v)
  );
  INVX1 _25_ (
    .A(l),
    .Y(_00_)
  );
  AND2X2 _26_ (
    .A(_00_),
    .B(a),
    .Y(_01_)
  );
  AND2X2 _27_ (
    .A(_01_),
    .B(m),
    .Y(_02_)
  );
  INVX1 _28_ (
    .A(n),
    .Y(_03_)
  );
  NOR2X1 _29_ (
    .A(_03_),
    .B(k),
    .Y(_04_)
  );
  AND2X2 _30_ (
    .A(_04_),
    .B(_02_),
    .Y(d0)
  );
  NOR2X1 _31_ (
    .A(n),
    .B(b),
    .Y(_05_)
  );
  AND2X2 _32_ (
    .A(_02_),
    .B(_05_),
    .Y(_06_)
  );
  NAND3X1 _33_ (
    .A(e),
    .B(c),
    .C(d),
    .Y(_07_)
  );
  AND2X2 _34_ (
    .A(n),
    .B(k),
    .Y(_08_)
  );
  AND2X2 _35_ (
    .A(_08_),
    .B(m),
    .Y(_09_)
  );
  AND2X2 _36_ (
    .A(_01_),
    .B(_09_),
    .Y(_10_)
  );
  AND2X2 _37_ (
    .A(_10_),
    .B(_07_),
    .Y(b0)
  );
  AND2X2 _38_ (
    .A(b0),
    .B(b),
    .Y(_11_)
  );
  OR2X2 _39_ (
    .A(_06_),
    .B(_11_),
    .Y(c0)
  );
  NAND2X1 _40_ (
    .A(m),
    .B(_03_),
    .Y(_12_)
  );
  INVX1 _41_ (
    .A(m),
    .Y(_13_)
  );
  NAND2X1 _42_ (
    .A(n),
    .B(_13_),
    .Y(s)
  );
  AND2X2 _43_ (
    .A(s),
    .B(_01_),
    .Y(_14_)
  );
  AND2X2 _44_ (
    .A(_14_),
    .B(_12_),
    .Y(a0)
  );
  INVX1 _45_ (
    .A(_08_),
    .Y(_15_)
  );
  OAI21X1 _46_ (
    .A(_07_),
    .B(_15_),
    .C(_02_),
    .Y(z)
  );
  NOR2X1 _47_ (
    .A(_03_),
    .B(m),
    .Y(_16_)
  );
  OR2X2 _48_ (
    .A(_07_),
    .B(_16_),
    .Y(_17_)
  );
  AND2X2 _49_ (
    .A(k),
    .B(b),
    .Y(_18_)
  );
  AND2X2 _50_ (
    .A(_17_),
    .B(_18_),
    .Y(x)
  );
  AND2X2 _51_ (
    .A(g),
    .B(h),
    .Y(_19_)
  );
  NAND3X1 _52_ (
    .A(_19_),
    .B(i),
    .C(j),
    .Y(_20_)
  );
  NAND2X1 _53_ (
    .A(_09_),
    .B(_20_),
    .Y(u)
  );
  INVX1 _54_ (
    .A(_09_),
    .Y(_21_)
  );
  OR2X2 _55_ (
    .A(_20_),
    .B(_21_),
    .Y(t)
  );
  NAND2X1 _56_ (
    .A(_13_),
    .B(_05_),
    .Y(r)
  );
endmodule
