/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module cm138a(a, b, c, d, e, f, g, h, i, j, k, l, m, n);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input a;
  input b;
  input c;
  input d;
  input e;
  input f;
  output g;
  output h;
  output i;
  output j;
  output k;
  output l;
  output m;
  output n;
  AND2X2 _11_ (
    .A(a),
    .B(b),
    .Y(_00_)
  );
  INVX1 _12_ (
    .A(f),
    .Y(_01_)
  );
  INVX1 _13_ (
    .A(e),
    .Y(_02_)
  );
  AND2X2 _14_ (
    .A(_02_),
    .B(d),
    .Y(_03_)
  );
  AND2X2 _15_ (
    .A(_03_),
    .B(_01_),
    .Y(_04_)
  );
  NAND3X1 _16_ (
    .A(_04_),
    .B(c),
    .C(_00_),
    .Y(n)
  );
  INVX1 _17_ (
    .A(a),
    .Y(_05_)
  );
  AND2X2 _18_ (
    .A(_05_),
    .B(b),
    .Y(_06_)
  );
  NAND3X1 _19_ (
    .A(_04_),
    .B(c),
    .C(_06_),
    .Y(m)
  );
  INVX1 _20_ (
    .A(b),
    .Y(_07_)
  );
  AND2X2 _21_ (
    .A(_07_),
    .B(a),
    .Y(_08_)
  );
  NAND3X1 _22_ (
    .A(_04_),
    .B(c),
    .C(_08_),
    .Y(l)
  );
  NOR2X1 _23_ (
    .A(a),
    .B(b),
    .Y(_09_)
  );
  NAND3X1 _24_ (
    .A(_04_),
    .B(c),
    .C(_09_),
    .Y(k)
  );
  INVX1 _25_ (
    .A(c),
    .Y(_10_)
  );
  NAND3X1 _26_ (
    .A(_04_),
    .B(_10_),
    .C(_00_),
    .Y(j)
  );
  NAND3X1 _27_ (
    .A(_04_),
    .B(_10_),
    .C(_06_),
    .Y(i)
  );
  NAND3X1 _28_ (
    .A(_04_),
    .B(_10_),
    .C(_08_),
    .Y(h)
  );
  NAND3X1 _29_ (
    .A(_04_),
    .B(_10_),
    .C(_09_),
    .Y(g)
  );
endmodule
