/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module cm151a(a, b, c, d, e, f, g, h, i, j, k, l, m, n);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  input a;
  input b;
  input c;
  input d;
  input e;
  input f;
  input g;
  input h;
  input i;
  input j;
  input k;
  input l;
  output m;
  output n;
  INVX1 _19_ (
    .A(l),
    .Y(_00_)
  );
  INVX1 _20_ (
    .A(j),
    .Y(_01_)
  );
  MUX2X1 _21_ (
    .A(g),
    .B(c),
    .S(k),
    .Y(_02_)
  );
  OR2X2 _22_ (
    .A(i),
    .B(_02_),
    .Y(_03_)
  );
  INVX1 _23_ (
    .A(i),
    .Y(_04_)
  );
  MUX2X1 _24_ (
    .A(h),
    .B(d),
    .S(k),
    .Y(_05_)
  );
  OR2X2 _25_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  AOI21X1 _26_ (
    .A(_03_),
    .B(_06_),
    .C(_01_),
    .Y(_07_)
  );
  MUX2X1 _27_ (
    .A(f),
    .B(b),
    .S(k),
    .Y(_08_)
  );
  OR2X2 _28_ (
    .A(_04_),
    .B(_08_),
    .Y(_09_)
  );
  MUX2X1 _29_ (
    .A(e),
    .B(a),
    .S(k),
    .Y(_10_)
  );
  OR2X2 _30_ (
    .A(i),
    .B(_10_),
    .Y(_11_)
  );
  AOI21X1 _31_ (
    .A(_09_),
    .B(_11_),
    .C(j),
    .Y(_12_)
  );
  OR2X2 _32_ (
    .A(_07_),
    .B(_12_),
    .Y(_13_)
  );
  AND2X2 _33_ (
    .A(_13_),
    .B(_00_),
    .Y(m)
  );
  AND2X2 _34_ (
    .A(_03_),
    .B(_06_),
    .Y(_14_)
  );
  OR2X2 _35_ (
    .A(_01_),
    .B(_14_),
    .Y(_15_)
  );
  AND2X2 _36_ (
    .A(_09_),
    .B(_11_),
    .Y(_16_)
  );
  OR2X2 _37_ (
    .A(j),
    .B(_16_),
    .Y(_17_)
  );
  AND2X2 _38_ (
    .A(_15_),
    .B(_17_),
    .Y(_18_)
  );
  OR2X2 _39_ (
    .A(l),
    .B(_18_),
    .Y(n)
  );
endmodule
