/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module cm85a(a, b, c, d, e, f, g, h, i, j, k, l, m, n);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  input a;
  input b;
  input c;
  input d;
  input e;
  input f;
  input g;
  input h;
  input i;
  input j;
  input k;
  output l;
  output m;
  output n;
  INVX1 _39_ (
    .A(g),
    .Y(_00_)
  );
  OR2X2 _40_ (
    .A(f),
    .B(_00_),
    .Y(_01_)
  );
  INVX1 _41_ (
    .A(e),
    .Y(_02_)
  );
  OR2X2 _42_ (
    .A(d),
    .B(_02_),
    .Y(_03_)
  );
  AND2X2 _43_ (
    .A(_01_),
    .B(_03_),
    .Y(_04_)
  );
  INVX1 _44_ (
    .A(d),
    .Y(_05_)
  );
  OR2X2 _45_ (
    .A(e),
    .B(_05_),
    .Y(_06_)
  );
  INVX1 _46_ (
    .A(f),
    .Y(_07_)
  );
  OR2X2 _47_ (
    .A(g),
    .B(_07_),
    .Y(_08_)
  );
  AND2X2 _48_ (
    .A(_06_),
    .B(_08_),
    .Y(_09_)
  );
  AND2X2 _49_ (
    .A(_09_),
    .B(b),
    .Y(_10_)
  );
  AND2X2 _50_ (
    .A(_10_),
    .B(_04_),
    .Y(_11_)
  );
  XNOR2X1 _51_ (
    .A(h),
    .B(i),
    .Y(_12_)
  );
  AND2X2 _52_ (
    .A(_11_),
    .B(_12_),
    .Y(_13_)
  );
  INVX1 _53_ (
    .A(k),
    .Y(_14_)
  );
  AND2X2 _54_ (
    .A(_14_),
    .B(j),
    .Y(_15_)
  );
  AND2X2 _55_ (
    .A(_13_),
    .B(_15_),
    .Y(_16_)
  );
  INVX1 _56_ (
    .A(h),
    .Y(_17_)
  );
  NOR2X1 _57_ (
    .A(_17_),
    .B(i),
    .Y(_18_)
  );
  AND2X2 _58_ (
    .A(_11_),
    .B(_18_),
    .Y(_19_)
  );
  AND2X2 _59_ (
    .A(_02_),
    .B(d),
    .Y(_20_)
  );
  AND2X2 _60_ (
    .A(_00_),
    .B(f),
    .Y(_21_)
  );
  OR2X2 _61_ (
    .A(_20_),
    .B(_21_),
    .Y(_22_)
  );
  AND2X2 _62_ (
    .A(_03_),
    .B(b),
    .Y(_23_)
  );
  AND2X2 _63_ (
    .A(_22_),
    .B(_23_),
    .Y(_24_)
  );
  OR2X2 _64_ (
    .A(c),
    .B(_24_),
    .Y(_25_)
  );
  OR2X2 _65_ (
    .A(_25_),
    .B(_19_),
    .Y(_26_)
  );
  OR2X2 _66_ (
    .A(_16_),
    .B(_26_),
    .Y(n)
  );
  NOR2X1 _67_ (
    .A(_14_),
    .B(j),
    .Y(_27_)
  );
  NOR2X1 _68_ (
    .A(_27_),
    .B(_15_),
    .Y(_28_)
  );
  AND2X2 _69_ (
    .A(_28_),
    .B(_13_),
    .Y(m)
  );
  AND2X2 _70_ (
    .A(_13_),
    .B(_27_),
    .Y(_29_)
  );
  AND2X2 _71_ (
    .A(_17_),
    .B(i),
    .Y(_30_)
  );
  AND2X2 _72_ (
    .A(_11_),
    .B(_30_),
    .Y(_31_)
  );
  AND2X2 _73_ (
    .A(_07_),
    .B(g),
    .Y(_32_)
  );
  AND2X2 _74_ (
    .A(_05_),
    .B(e),
    .Y(_33_)
  );
  OR2X2 _75_ (
    .A(_32_),
    .B(_33_),
    .Y(_34_)
  );
  AND2X2 _76_ (
    .A(_06_),
    .B(b),
    .Y(_35_)
  );
  AND2X2 _77_ (
    .A(_34_),
    .B(_35_),
    .Y(_36_)
  );
  OR2X2 _78_ (
    .A(a),
    .B(_36_),
    .Y(_37_)
  );
  OR2X2 _79_ (
    .A(_37_),
    .B(_31_),
    .Y(_38_)
  );
  OR2X2 _80_ (
    .A(_29_),
    .B(_38_),
    .Y(l)
  );
endmodule
