/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module cm82a(a, b, c, d, e, f, g, h);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  input a;
  input b;
  input c;
  input d;
  input e;
  output f;
  output g;
  output h;
  AND2X2 _13_ (
    .A(d),
    .B(e),
    .Y(_12_)
  );
  OR2X2 _14_ (
    .A(c),
    .B(b),
    .Y(_00_)
  );
  AND2X2 _15_ (
    .A(c),
    .B(b),
    .Y(_01_)
  );
  OR2X2 _16_ (
    .A(a),
    .B(_01_),
    .Y(_02_)
  );
  AND2X2 _17_ (
    .A(_02_),
    .B(_00_),
    .Y(_03_)
  );
  XOR2X1 _18_ (
    .A(d),
    .B(e),
    .Y(_04_)
  );
  AND2X2 _19_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  OR2X2 _20_ (
    .A(_12_),
    .B(_05_),
    .Y(h)
  );
  XOR2X1 _21_ (
    .A(_04_),
    .B(_03_),
    .Y(g)
  );
  AND2X2 _22_ (
    .A(_01_),
    .B(a),
    .Y(_06_)
  );
  NOR2X1 _23_ (
    .A(c),
    .B(b),
    .Y(_07_)
  );
  AOI21X1 _24_ (
    .A(c),
    .B(b),
    .C(a),
    .Y(_08_)
  );
  OR2X2 _25_ (
    .A(_07_),
    .B(_08_),
    .Y(_09_)
  );
  OR2X2 _26_ (
    .A(a),
    .B(_00_),
    .Y(_10_)
  );
  AND2X2 _27_ (
    .A(_09_),
    .B(_10_),
    .Y(_11_)
  );
  OR2X2 _28_ (
    .A(_06_),
    .B(_11_),
    .Y(f)
  );
endmodule
