/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module misj(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20
, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, \v35.0 , \v35.1 , \v35.2 , \v35.3 , \v35.4 , \v35.5 , \v35.6 
, \v35.7 , \v35.8 , \v35.9 , \v35.10 , \v35.11 , \v35.12 , \v35.13 );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  input v0;
  input v1;
  input v10;
  input v11;
  input v12;
  input v13;
  input v14;
  input v15;
  input v16;
  input v17;
  input v18;
  input v19;
  input v2;
  input v20;
  input v21;
  input v22;
  input v23;
  input v24;
  input v25;
  input v26;
  input v27;
  input v28;
  input v29;
  input v3;
  input v30;
  input v31;
  input v32;
  input v33;
  input v34;
  output \v35.0 ;
  output \v35.1 ;
  output \v35.10 ;
  output \v35.11 ;
  output \v35.12 ;
  output \v35.13 ;
  output \v35.2 ;
  output \v35.3 ;
  output \v35.4 ;
  output \v35.5 ;
  output \v35.6 ;
  output \v35.7 ;
  output \v35.8 ;
  output \v35.9 ;
  input v4;
  input v5;
  input v6;
  input v7;
  input v8;
  input v9;
  INVX1 _20_ (
    .A(v15),
    .Y(\v35.7 )
  );
  INVX1 _21_ (
    .A(v5),
    .Y(\v35.2 )
  );
  AND2X2 _22_ (
    .A(v22),
    .B(v27),
    .Y(_00_)
  );
  NAND3X1 _23_ (
    .A(_00_),
    .B(v28),
    .C(v33),
    .Y(_01_)
  );
  NAND3X1 _24_ (
    .A(v32),
    .B(v30),
    .C(v31),
    .Y(_02_)
  );
  NAND3X1 _25_ (
    .A(v34),
    .B(v24),
    .C(v26),
    .Y(_03_)
  );
  OR2X2 _26_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  OR2X2 _27_ (
    .A(_04_),
    .B(_01_),
    .Y(\v35.10 )
  );
  INVX1 _28_ (
    .A(v29),
    .Y(_05_)
  );
  OR2X2 _29_ (
    .A(v25),
    .B(v23),
    .Y(_06_)
  );
  OR2X2 _30_ (
    .A(_06_),
    .B(_05_),
    .Y(_07_)
  );
  OR2X2 _31_ (
    .A(_02_),
    .B(_07_),
    .Y(_08_)
  );
  OR2X2 _32_ (
    .A(_01_),
    .B(_08_),
    .Y(\v35.9 )
  );
  NAND2X1 _33_ (
    .A(v21),
    .B(v6),
    .Y(\v35.8 )
  );
  INVX1 _34_ (
    .A(v20),
    .Y(_09_)
  );
  NOR2X1 _35_ (
    .A(v19),
    .B(v9),
    .Y(_10_)
  );
  NAND2X1 _36_ (
    .A(_09_),
    .B(_10_),
    .Y(\v35.6 )
  );
  NAND2X1 _37_ (
    .A(v18),
    .B(v17),
    .Y(\v35.5 )
  );
  AND2X2 _38_ (
    .A(v5),
    .B(v7),
    .Y(_11_)
  );
  AND2X2 _39_ (
    .A(v7),
    .B(v12),
    .Y(_12_)
  );
  AND2X2 _40_ (
    .A(v13),
    .B(v14),
    .Y(_13_)
  );
  AOI21X1 _41_ (
    .A(_12_),
    .B(_13_),
    .C(_11_),
    .Y(\v35.4 )
  );
  AND2X2 _42_ (
    .A(v7),
    .B(v10),
    .Y(_14_)
  );
  AOI21X1 _43_ (
    .A(v11),
    .B(_14_),
    .C(_11_),
    .Y(\v35.3 )
  );
  NAND2X1 _44_ (
    .A(v1),
    .B(v3),
    .Y(_15_)
  );
  NAND3X1 _45_ (
    .A(v15),
    .B(v16),
    .C(v4),
    .Y(_16_)
  );
  OR2X2 _46_ (
    .A(_15_),
    .B(_16_),
    .Y(_17_)
  );
  AND2X2 _47_ (
    .A(v7),
    .B(v8),
    .Y(_18_)
  );
  AND2X2 _48_ (
    .A(_17_),
    .B(_18_),
    .Y(\v35.11 )
  );
  OR2X2 _49_ (
    .A(_11_),
    .B(\v35.11 ),
    .Y(\v35.1 )
  );
  NAND2X1 _50_ (
    .A(v0),
    .B(v2),
    .Y(_19_)
  );
  NOR2X1 _51_ (
    .A(_15_),
    .B(_19_),
    .Y(\v35.0 )
  );
  assign \v35.13  = 1'h0;
  assign \v35.12  = 1'h0;
endmodule
