/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module x2dn(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20
, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, v35, v36, v37, v38, v39, v40, v41
, v42, v43, v44, v45, v46, v47, v48, v49, v50, v51, v52, v53, v54, v55, v56, v57, v58, v59, v60, v61, v62
, v63, v64, v65, v66, v67, v68, v69, v70, v71, v72, v73, v74, v75, v76, v77, v78, v79, v80, v81, \v82.0 , \v82.1 
, \v82.2 , \v82.3 , \v82.4 , \v82.5 , \v82.6 , \v82.7 , \v82.8 , \v82.9 , \v82.10 , \v82.11 , \v82.12 , \v82.13 , \v82.14 , \v82.15 , \v82.16 , \v82.17 , \v82.18 , \v82.19 , \v82.20 , \v82.21 , \v82.22 
, \v82.23 , \v82.24 , \v82.25 , \v82.26 , \v82.27 , \v82.28 , \v82.29 , \v82.30 , \v82.31 , \v82.32 , \v82.33 , \v82.34 , \v82.35 , \v82.36 , \v82.37 , \v82.38 , \v82.39 , \v82.40 , \v82.41 , \v82.42 , \v82.43 
, \v82.44 , \v82.45 , \v82.46 , \v82.47 , \v82.48 , \v82.49 , \v82.50 , \v82.51 , \v82.52 , \v82.53 , \v82.54 , \v82.55 );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  input v0;
  input v1;
  input v10;
  input v11;
  input v12;
  input v13;
  input v14;
  input v15;
  input v16;
  input v17;
  input v18;
  input v19;
  input v2;
  input v20;
  input v21;
  input v22;
  input v23;
  input v24;
  input v25;
  input v26;
  input v27;
  input v28;
  input v29;
  input v3;
  input v30;
  input v31;
  input v32;
  input v33;
  input v34;
  input v35;
  input v36;
  input v37;
  input v38;
  input v39;
  input v4;
  input v40;
  input v41;
  input v42;
  input v43;
  input v44;
  input v45;
  input v46;
  input v47;
  input v48;
  input v49;
  input v5;
  input v50;
  input v51;
  input v52;
  input v53;
  input v54;
  input v55;
  input v56;
  input v57;
  input v58;
  input v59;
  input v6;
  input v60;
  input v61;
  input v62;
  input v63;
  input v64;
  input v65;
  input v66;
  input v67;
  input v68;
  input v69;
  input v7;
  input v70;
  input v71;
  input v72;
  input v73;
  input v74;
  input v75;
  input v76;
  input v77;
  input v78;
  input v79;
  input v8;
  input v80;
  input v81;
  output \v82.0 ;
  output \v82.1 ;
  output \v82.10 ;
  output \v82.11 ;
  output \v82.12 ;
  output \v82.13 ;
  output \v82.14 ;
  output \v82.15 ;
  output \v82.16 ;
  output \v82.17 ;
  output \v82.18 ;
  output \v82.19 ;
  output \v82.2 ;
  output \v82.20 ;
  output \v82.21 ;
  output \v82.22 ;
  output \v82.23 ;
  output \v82.24 ;
  output \v82.25 ;
  output \v82.26 ;
  output \v82.27 ;
  output \v82.28 ;
  output \v82.29 ;
  output \v82.3 ;
  output \v82.30 ;
  output \v82.31 ;
  output \v82.32 ;
  output \v82.33 ;
  output \v82.34 ;
  output \v82.35 ;
  output \v82.36 ;
  output \v82.37 ;
  output \v82.38 ;
  output \v82.39 ;
  output \v82.4 ;
  output \v82.40 ;
  output \v82.41 ;
  output \v82.42 ;
  output \v82.43 ;
  output \v82.44 ;
  output \v82.45 ;
  output \v82.46 ;
  output \v82.47 ;
  output \v82.48 ;
  output \v82.49 ;
  output \v82.5 ;
  output \v82.50 ;
  output \v82.51 ;
  output \v82.52 ;
  output \v82.53 ;
  output \v82.54 ;
  output \v82.55 ;
  output \v82.6 ;
  output \v82.7 ;
  output \v82.8 ;
  output \v82.9 ;
  input v9;
  NAND3X1 _084_ (
    .A(v10),
    .B(v9),
    .C(v11),
    .Y(\v82.31 )
  );
  INVX1 _085_ (
    .A(\v82.31 ),
    .Y(\v82.20 )
  );
  INVX1 _086_ (
    .A(v4),
    .Y(\v82.8 )
  );
  NOR2X1 _087_ (
    .A(v77),
    .B(v76),
    .Y(_000_)
  );
  NOR2X1 _088_ (
    .A(_000_),
    .B(v79),
    .Y(_001_)
  );
  NOR3X1 _089_ (
    .A(v78),
    .B(v77),
    .C(v76),
    .Y(_002_)
  );
  INVX1 _090_ (
    .A(v81),
    .Y(_003_)
  );
  INVX1 _091_ (
    .A(v80),
    .Y(_004_)
  );
  NAND3X1 _092_ (
    .A(_003_),
    .B(v75),
    .C(_004_),
    .Y(_005_)
  );
  NOR3X1 _093_ (
    .A(_001_),
    .B(_002_),
    .C(_005_),
    .Y(\v82.55 )
  );
  OR2X2 _094_ (
    .A(v50),
    .B(v51),
    .Y(_006_)
  );
  AND2X2 _095_ (
    .A(_006_),
    .B(v58),
    .Y(\v82.53 )
  );
  INVX1 _096_ (
    .A(v71),
    .Y(_007_)
  );
  NOR2X1 _097_ (
    .A(v73),
    .B(v72),
    .Y(_008_)
  );
  NOR2X1 _098_ (
    .A(_008_),
    .B(v74),
    .Y(_009_)
  );
  NOR3X1 _099_ (
    .A(v70),
    .B(v73),
    .C(v72),
    .Y(_010_)
  );
  NOR3X1 _100_ (
    .A(_009_),
    .B(_007_),
    .C(_010_),
    .Y(\v82.50 )
  );
  NAND2X1 _101_ (
    .A(v48),
    .B(_006_),
    .Y(_011_)
  );
  NAND2X1 _102_ (
    .A(v69),
    .B(_011_),
    .Y(_012_)
  );
  NAND2X1 _103_ (
    .A(v67),
    .B(v68),
    .Y(_013_)
  );
  OAI21X1 _104_ (
    .A(_011_),
    .B(_013_),
    .C(_012_),
    .Y(\v82.49 )
  );
  INVX1 _105_ (
    .A(_011_),
    .Y(\v82.51 )
  );
  INVX1 _106_ (
    .A(_013_),
    .Y(\v82.48 )
  );
  INVX1 _107_ (
    .A(v49),
    .Y(_014_)
  );
  AND2X2 _108_ (
    .A(v50),
    .B(v51),
    .Y(\v82.54 )
  );
  AND2X2 _109_ (
    .A(\v82.54 ),
    .B(v57),
    .Y(_015_)
  );
  NOR2X1 _110_ (
    .A(v55),
    .B(v48),
    .Y(_016_)
  );
  AND2X2 _111_ (
    .A(_016_),
    .B(v58),
    .Y(_017_)
  );
  OR2X2 _112_ (
    .A(_015_),
    .B(_017_),
    .Y(_018_)
  );
  AND2X2 _113_ (
    .A(_018_),
    .B(_014_),
    .Y(_019_)
  );
  OR2X2 _114_ (
    .A(v30),
    .B(v27),
    .Y(_020_)
  );
  OR2X2 _115_ (
    .A(v36),
    .B(v33),
    .Y(_021_)
  );
  OR2X2 _116_ (
    .A(v42),
    .B(v39),
    .Y(_022_)
  );
  NOR3X1 _117_ (
    .A(_020_),
    .B(_021_),
    .C(_022_),
    .Y(_023_)
  );
  OR2X2 _118_ (
    .A(v63),
    .B(v64),
    .Y(_024_)
  );
  OR2X2 _119_ (
    .A(v65),
    .B(v66),
    .Y(_025_)
  );
  OR2X2 _120_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_)
  );
  OR2X2 _121_ (
    .A(v45),
    .B(v60),
    .Y(_027_)
  );
  OR2X2 _122_ (
    .A(v61),
    .B(v62),
    .Y(_028_)
  );
  NOR3X1 _123_ (
    .A(_026_),
    .B(_027_),
    .C(_028_),
    .Y(_029_)
  );
  AND2X2 _124_ (
    .A(_029_),
    .B(_023_),
    .Y(_030_)
  );
  AND2X2 _125_ (
    .A(_030_),
    .B(_019_),
    .Y(_031_)
  );
  INVX1 _126_ (
    .A(_006_),
    .Y(_032_)
  );
  AND2X2 _127_ (
    .A(_032_),
    .B(v53),
    .Y(_033_)
  );
  AND2X2 _128_ (
    .A(_006_),
    .B(v49),
    .Y(_034_)
  );
  AND2X2 _129_ (
    .A(_034_),
    .B(v56),
    .Y(_035_)
  );
  OR2X2 _130_ (
    .A(_035_),
    .B(_033_),
    .Y(_036_)
  );
  AND2X2 _131_ (
    .A(v61),
    .B(v62),
    .Y(_037_)
  );
  AND2X2 _132_ (
    .A(v64),
    .B(v66),
    .Y(_038_)
  );
  AND2X2 _133_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  AND2X2 _134_ (
    .A(v27),
    .B(v33),
    .Y(_040_)
  );
  AND2X2 _135_ (
    .A(v39),
    .B(v60),
    .Y(_041_)
  );
  AND2X2 _136_ (
    .A(_040_),
    .B(_041_),
    .Y(_042_)
  );
  AND2X2 _137_ (
    .A(_039_),
    .B(_042_),
    .Y(_043_)
  );
  AND2X2 _138_ (
    .A(v30),
    .B(v36),
    .Y(_044_)
  );
  AND2X2 _139_ (
    .A(v42),
    .B(v45),
    .Y(_045_)
  );
  AND2X2 _140_ (
    .A(v63),
    .B(v65),
    .Y(_046_)
  );
  AND2X2 _141_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  AND2X2 _142_ (
    .A(_047_),
    .B(_044_),
    .Y(_048_)
  );
  AND2X2 _143_ (
    .A(_043_),
    .B(_048_),
    .Y(_049_)
  );
  AND2X2 _144_ (
    .A(_049_),
    .B(_036_),
    .Y(_050_)
  );
  OR2X2 _145_ (
    .A(_050_),
    .B(_031_),
    .Y(_051_)
  );
  AND2X2 _146_ (
    .A(_034_),
    .B(v59),
    .Y(_052_)
  );
  AND2X2 _147_ (
    .A(_032_),
    .B(v57),
    .Y(_053_)
  );
  OR2X2 _148_ (
    .A(_052_),
    .B(_053_),
    .Y(_054_)
  );
  AND2X2 _149_ (
    .A(_030_),
    .B(_054_),
    .Y(_055_)
  );
  AND2X2 _150_ (
    .A(\v82.54 ),
    .B(v53),
    .Y(_056_)
  );
  AND2X2 _151_ (
    .A(_016_),
    .B(v54),
    .Y(_057_)
  );
  OR2X2 _152_ (
    .A(_056_),
    .B(_057_),
    .Y(_058_)
  );
  AND2X2 _153_ (
    .A(_058_),
    .B(_014_),
    .Y(_059_)
  );
  AND2X2 _154_ (
    .A(_049_),
    .B(_059_),
    .Y(_060_)
  );
  OR2X2 _155_ (
    .A(_055_),
    .B(_060_),
    .Y(_061_)
  );
  OR2X2 _156_ (
    .A(_051_),
    .B(_061_),
    .Y(\v82.47 )
  );
  OR2X2 _157_ (
    .A(_054_),
    .B(_019_),
    .Y(\v82.46 )
  );
  OR2X2 _158_ (
    .A(_036_),
    .B(_059_),
    .Y(\v82.45 )
  );
  AOI21X1 _159_ (
    .A(v52),
    .B(_006_),
    .C(v48),
    .Y(_062_)
  );
  MUX2X1 _160_ (
    .A(v49),
    .B(v53),
    .S(_011_),
    .Y(_063_)
  );
  NOR2X1 _161_ (
    .A(_063_),
    .B(_062_),
    .Y(\v82.44 )
  );
  XNOR2X1 _162_ (
    .A(v46),
    .B(v47),
    .Y(_064_)
  );
  XNOR2X1 _163_ (
    .A(v45),
    .B(_064_),
    .Y(\v82.43 )
  );
  XNOR2X1 _164_ (
    .A(v43),
    .B(v44),
    .Y(_065_)
  );
  XNOR2X1 _165_ (
    .A(v42),
    .B(_065_),
    .Y(\v82.42 )
  );
  XNOR2X1 _166_ (
    .A(v40),
    .B(v41),
    .Y(_066_)
  );
  XNOR2X1 _167_ (
    .A(v39),
    .B(_066_),
    .Y(\v82.41 )
  );
  XNOR2X1 _168_ (
    .A(v37),
    .B(v38),
    .Y(_067_)
  );
  XNOR2X1 _169_ (
    .A(v36),
    .B(_067_),
    .Y(\v82.40 )
  );
  XNOR2X1 _170_ (
    .A(v34),
    .B(v35),
    .Y(_068_)
  );
  XNOR2X1 _171_ (
    .A(v33),
    .B(_068_),
    .Y(\v82.39 )
  );
  XNOR2X1 _172_ (
    .A(v31),
    .B(v32),
    .Y(_069_)
  );
  XNOR2X1 _173_ (
    .A(v30),
    .B(_069_),
    .Y(\v82.38 )
  );
  XNOR2X1 _174_ (
    .A(v28),
    .B(v29),
    .Y(_070_)
  );
  XNOR2X1 _175_ (
    .A(v27),
    .B(_070_),
    .Y(\v82.37 )
  );
  NOR2X1 _176_ (
    .A(v24),
    .B(v23),
    .Y(_071_)
  );
  MUX2X1 _177_ (
    .A(v25),
    .B(v26),
    .S(_071_),
    .Y(\v82.36 )
  );
  INVX1 _178_ (
    .A(v20),
    .Y(_072_)
  );
  AOI21X1 _179_ (
    .A(v21),
    .B(v22),
    .C(_072_),
    .Y(\v82.35 )
  );
  INVX1 _180_ (
    .A(v9),
    .Y(_073_)
  );
  AOI21X1 _181_ (
    .A(v10),
    .B(v11),
    .C(_073_),
    .Y(\v82.32 )
  );
  INVX1 _182_ (
    .A(v10),
    .Y(_074_)
  );
  AOI21X1 _183_ (
    .A(v9),
    .B(v11),
    .C(_074_),
    .Y(\v82.33 )
  );
  OR2X2 _184_ (
    .A(\v82.32 ),
    .B(\v82.33 ),
    .Y(\v82.25 )
  );
  INVX1 _185_ (
    .A(v5),
    .Y(_075_)
  );
  AOI21X1 _186_ (
    .A(v3),
    .B(_075_),
    .C(\v82.8 ),
    .Y(\v82.9 )
  );
  NOR2X1 _187_ (
    .A(v4),
    .B(v5),
    .Y(_076_)
  );
  INVX1 _188_ (
    .A(_076_),
    .Y(_077_)
  );
  MUX2X1 _189_ (
    .A(_077_),
    .B(_075_),
    .S(v3),
    .Y(\v82.5 )
  );
  NAND3X1 _190_ (
    .A(_075_),
    .B(v4),
    .C(v3),
    .Y(\v82.4 )
  );
  INVX1 _191_ (
    .A(v3),
    .Y(_078_)
  );
  AOI21X1 _192_ (
    .A(_078_),
    .B(_076_),
    .C(v8),
    .Y(\v82.3 )
  );
  NOR3X1 _193_ (
    .A(v10),
    .B(v9),
    .C(v11),
    .Y(_079_)
  );
  INVX1 _194_ (
    .A(v0),
    .Y(_080_)
  );
  NOR2X1 _195_ (
    .A(v8),
    .B(v7),
    .Y(_081_)
  );
  NAND3X1 _196_ (
    .A(_081_),
    .B(v6),
    .C(_080_),
    .Y(_082_)
  );
  NOR3X1 _197_ (
    .A(_082_),
    .B(v1),
    .C(_079_),
    .Y(\v82.2 )
  );
  NOR2X1 _198_ (
    .A(v10),
    .B(v9),
    .Y(\v82.24 )
  );
  AOI21X1 _199_ (
    .A(_078_),
    .B(_076_),
    .C(_082_),
    .Y(\v82.1 )
  );
  INVX1 _200_ (
    .A(v2),
    .Y(_083_)
  );
  NOR3X1 _201_ (
    .A(_083_),
    .B(v1),
    .C(v0),
    .Y(\v82.0 )
  );
  assign \v82.52  = v54;
  assign \v82.34  = v11;
  assign \v82.30  = 1'h0;
  assign \v82.29  = \v82.20 ;
  assign \v82.28  = 1'h0;
  assign \v82.27  = \v82.20 ;
  assign \v82.26  = \v82.20 ;
  assign \v82.23  = 1'h0;
  assign \v82.22  = 1'h0;
  assign \v82.21  = 1'h0;
  assign \v82.19  = v19;
  assign \v82.18  = v18;
  assign \v82.17  = v17;
  assign \v82.16  = v16;
  assign \v82.15  = v15;
  assign \v82.14  = v14;
  assign \v82.13  = v13;
  assign \v82.12  = v12;
  assign \v82.11  = 1'h0;
  assign \v82.10  = 1'h0;
  assign \v82.7  = 1'h0;
  assign \v82.6  = 1'h0;
endmodule
