/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module pcle(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u
, v, w, x, y, z, a0, b0);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  input a;
  output a0;
  input b;
  output b0;
  input c;
  input d;
  input e;
  input f;
  input g;
  input h;
  input i;
  input j;
  input k;
  input l;
  input m;
  input n;
  input o;
  input p;
  input q;
  input r;
  input s;
  output t;
  output u;
  output v;
  output w;
  output x;
  output y;
  output z;
  AND2X2 _37_ (
    .A(h),
    .B(i),
    .Y(_00_)
  );
  AND2X2 _38_ (
    .A(m),
    .B(l),
    .Y(_01_)
  );
  AND2X2 _39_ (
    .A(_01_),
    .B(n),
    .Y(_02_)
  );
  AND2X2 _40_ (
    .A(_02_),
    .B(o),
    .Y(_03_)
  );
  AND2X2 _41_ (
    .A(_03_),
    .B(p),
    .Y(_04_)
  );
  AND2X2 _42_ (
    .A(_04_),
    .B(q),
    .Y(_05_)
  );
  AND2X2 _43_ (
    .A(_05_),
    .B(r),
    .Y(_06_)
  );
  OR2X2 _44_ (
    .A(s),
    .B(_06_),
    .Y(_07_)
  );
  INVX1 _45_ (
    .A(j),
    .Y(_08_)
  );
  NOR3X1 _46_ (
    .A(_08_),
    .B(i),
    .C(k),
    .Y(_09_)
  );
  NAND3X1 _47_ (
    .A(_05_),
    .B(s),
    .C(r),
    .Y(_10_)
  );
  AND2X2 _48_ (
    .A(_10_),
    .B(_09_),
    .Y(_11_)
  );
  AND2X2 _49_ (
    .A(_11_),
    .B(_07_),
    .Y(_12_)
  );
  OR2X2 _50_ (
    .A(_00_),
    .B(_12_),
    .Y(b0)
  );
  AND2X2 _51_ (
    .A(i),
    .B(g),
    .Y(_13_)
  );
  OR2X2 _52_ (
    .A(r),
    .B(_05_),
    .Y(_14_)
  );
  INVX1 _53_ (
    .A(i),
    .Y(_15_)
  );
  INVX1 _54_ (
    .A(k),
    .Y(_16_)
  );
  NAND3X1 _55_ (
    .A(_15_),
    .B(j),
    .C(_16_),
    .Y(_17_)
  );
  AOI21X1 _56_ (
    .A(r),
    .B(_05_),
    .C(_17_),
    .Y(_18_)
  );
  AND2X2 _57_ (
    .A(_18_),
    .B(_14_),
    .Y(_19_)
  );
  OR2X2 _58_ (
    .A(_13_),
    .B(_19_),
    .Y(a0)
  );
  NAND2X1 _59_ (
    .A(i),
    .B(f),
    .Y(_20_)
  );
  NOR2X1 _60_ (
    .A(_04_),
    .B(q),
    .Y(_21_)
  );
  OR2X2 _61_ (
    .A(_17_),
    .B(_05_),
    .Y(_22_)
  );
  OAI21X1 _62_ (
    .A(_22_),
    .B(_21_),
    .C(_20_),
    .Y(z)
  );
  NAND2X1 _63_ (
    .A(i),
    .B(e),
    .Y(_23_)
  );
  NOR2X1 _64_ (
    .A(_03_),
    .B(p),
    .Y(_24_)
  );
  OR2X2 _65_ (
    .A(_04_),
    .B(_17_),
    .Y(_25_)
  );
  OAI21X1 _66_ (
    .A(_25_),
    .B(_24_),
    .C(_23_),
    .Y(y)
  );
  NAND2X1 _67_ (
    .A(i),
    .B(d),
    .Y(_26_)
  );
  NOR2X1 _68_ (
    .A(_02_),
    .B(o),
    .Y(_27_)
  );
  OR2X2 _69_ (
    .A(_03_),
    .B(_17_),
    .Y(_28_)
  );
  OAI21X1 _70_ (
    .A(_27_),
    .B(_28_),
    .C(_26_),
    .Y(x)
  );
  NAND2X1 _71_ (
    .A(i),
    .B(c),
    .Y(_29_)
  );
  NOR2X1 _72_ (
    .A(_01_),
    .B(n),
    .Y(_30_)
  );
  OR2X2 _73_ (
    .A(_02_),
    .B(_17_),
    .Y(_31_)
  );
  OAI21X1 _74_ (
    .A(_30_),
    .B(_31_),
    .C(_29_),
    .Y(w)
  );
  NAND2X1 _75_ (
    .A(i),
    .B(b),
    .Y(_32_)
  );
  INVX1 _76_ (
    .A(_01_),
    .Y(_33_)
  );
  OR2X2 _77_ (
    .A(m),
    .B(l),
    .Y(_34_)
  );
  NAND3X1 _78_ (
    .A(_09_),
    .B(_33_),
    .C(_34_),
    .Y(_35_)
  );
  NAND2X1 _79_ (
    .A(_32_),
    .B(_35_),
    .Y(v)
  );
  NAND2X1 _80_ (
    .A(i),
    .B(a),
    .Y(_36_)
  );
  OAI21X1 _81_ (
    .A(l),
    .B(_17_),
    .C(_36_),
    .Y(u)
  );
  NOR2X1 _82_ (
    .A(_10_),
    .B(_17_),
    .Y(t)
  );
endmodule
