/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module cm152a(a, b, c, d, e, f, g, h, i, j, k, l);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  input a;
  input b;
  input c;
  input d;
  input e;
  input f;
  input g;
  input h;
  input i;
  input j;
  input k;
  output l;
  INVX1 _23_ (
    .A(i),
    .Y(_00_)
  );
  OR2X2 _24_ (
    .A(f),
    .B(_00_),
    .Y(_01_)
  );
  INVX1 _25_ (
    .A(j),
    .Y(_02_)
  );
  OR2X2 _26_ (
    .A(i),
    .B(e),
    .Y(_03_)
  );
  AND2X2 _27_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  AND2X2 _28_ (
    .A(_01_),
    .B(_04_),
    .Y(_05_)
  );
  INVX1 _29_ (
    .A(k),
    .Y(_06_)
  );
  OR2X2 _30_ (
    .A(h),
    .B(_00_),
    .Y(_07_)
  );
  OR2X2 _31_ (
    .A(i),
    .B(g),
    .Y(_08_)
  );
  AND2X2 _32_ (
    .A(_08_),
    .B(j),
    .Y(_09_)
  );
  AND2X2 _33_ (
    .A(_07_),
    .B(_09_),
    .Y(_10_)
  );
  OR2X2 _34_ (
    .A(_06_),
    .B(_10_),
    .Y(_11_)
  );
  OR2X2 _35_ (
    .A(_05_),
    .B(_11_),
    .Y(_12_)
  );
  OR2X2 _36_ (
    .A(b),
    .B(_00_),
    .Y(_13_)
  );
  OR2X2 _37_ (
    .A(i),
    .B(a),
    .Y(_14_)
  );
  AND2X2 _38_ (
    .A(_02_),
    .B(_14_),
    .Y(_15_)
  );
  AND2X2 _39_ (
    .A(_13_),
    .B(_15_),
    .Y(_16_)
  );
  OR2X2 _40_ (
    .A(d),
    .B(_00_),
    .Y(_17_)
  );
  OR2X2 _41_ (
    .A(i),
    .B(c),
    .Y(_18_)
  );
  AND2X2 _42_ (
    .A(_18_),
    .B(j),
    .Y(_19_)
  );
  AND2X2 _43_ (
    .A(_17_),
    .B(_19_),
    .Y(_20_)
  );
  OR2X2 _44_ (
    .A(k),
    .B(_20_),
    .Y(_21_)
  );
  OR2X2 _45_ (
    .A(_16_),
    .B(_21_),
    .Y(_22_)
  );
  AND2X2 _46_ (
    .A(_12_),
    .B(_22_),
    .Y(l)
  );
endmodule
