/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module clpl(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, \v11.0 , \v11.1 , \v11.2 , \v11.3 , \v11.4 );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  input v0;
  input v1;
  input v10;
  output \v11.0 ;
  output \v11.1 ;
  output \v11.2 ;
  output \v11.3 ;
  output \v11.4 ;
  input v2;
  input v3;
  input v4;
  input v5;
  input v6;
  input v7;
  input v8;
  input v9;
  OR2X2 _05_ (
    .A(v1),
    .B(_02_),
    .Y(\v11.0 )
  );
  AND2X2 _06_ (
    .A(\v11.0 ),
    .B(v8),
    .Y(_03_)
  );
  OR2X2 _07_ (
    .A(v7),
    .B(_03_),
    .Y(\v11.4 )
  );
  AND2X2 _08_ (
    .A(\v11.4 ),
    .B(v9),
    .Y(_04_)
  );
  OR2X2 _09_ (
    .A(v10),
    .B(_04_),
    .Y(\v11.3 )
  );
  AND2X2 _10_ (
    .A(v0),
    .B(v4),
    .Y(_00_)
  );
  OR2X2 _11_ (
    .A(v2),
    .B(_00_),
    .Y(\v11.2 )
  );
  AND2X2 _12_ (
    .A(\v11.2 ),
    .B(v5),
    .Y(_01_)
  );
  OR2X2 _13_ (
    .A(v3),
    .B(_01_),
    .Y(\v11.1 )
  );
  AND2X2 _14_ (
    .A(\v11.1 ),
    .B(v6),
    .Y(_02_)
  );
endmodule
