/* Generated by Yosys 0.11+20 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
module newcpla1(WAIT, \CPIPE1s<0> , \CPIPE1s<1> , \CPIPE1s<2> , \CPIPE1s<3> , \CPIPE1s<4> , \CPIPE1s<5> , \CPIPE1s<7> , RESET, changeCWP2t, trap, lastPCload, pDATABUSintoLOADL, enableINTS1, changeCWP1, PCtoMAL1, pALUtoMAL, pPCIncr, pALUtoPC, DST2step1, PCstuffoncall1
, SRC2smin1, DST1min1, CPIPE1flush, CPIPE1load1);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  output CPIPE1flush;
  output CPIPE1load1;
  input \CPIPE1s<0> ;
  input \CPIPE1s<1> ;
  input \CPIPE1s<2> ;
  input \CPIPE1s<3> ;
  input \CPIPE1s<4> ;
  input \CPIPE1s<5> ;
  input \CPIPE1s<7> ;
  output DST1min1;
  output DST2step1;
  output PCstuffoncall1;
  output PCtoMAL1;
  input RESET;
  output SRC2smin1;
  input WAIT;
  output changeCWP1;
  output changeCWP2t;
  output enableINTS1;
  output lastPCload;
  output pALUtoMAL;
  output pALUtoPC;
  output pDATABUSintoLOADL;
  output pPCIncr;
  output trap;
  INVX1 _056_ (
    .A(RESET),
    .Y(_000_)
  );
  INVX1 _057_ (
    .A(WAIT),
    .Y(_001_)
  );
  NAND2X1 _058_ (
    .A(_000_),
    .B(_001_),
    .Y(_002_)
  );
  INVX1 _059_ (
    .A(\CPIPE1s<7> ),
    .Y(_003_)
  );
  NAND2X1 _060_ (
    .A(\CPIPE1s<5> ),
    .B(\CPIPE1s<4> ),
    .Y(_004_)
  );
  NOR2X1 _061_ (
    .A(_004_),
    .B(_003_),
    .Y(_005_)
  );
  NOR2X1 _062_ (
    .A(_005_),
    .B(_002_),
    .Y(CPIPE1load1)
  );
  INVX1 _063_ (
    .A(\CPIPE1s<0> ),
    .Y(_006_)
  );
  AOI21X1 _064_ (
    .A(\CPIPE1s<2> ),
    .B(_006_),
    .C(\CPIPE1s<4> ),
    .Y(_007_)
  );
  AND2X2 _065_ (
    .A(\CPIPE1s<5> ),
    .B(\CPIPE1s<4> ),
    .Y(_008_)
  );
  OR2X2 _066_ (
    .A(\CPIPE1s<3> ),
    .B(_008_),
    .Y(_009_)
  );
  OR2X2 _067_ (
    .A(_009_),
    .B(_007_),
    .Y(_010_)
  );
  INVX1 _068_ (
    .A(\CPIPE1s<2> ),
    .Y(_011_)
  );
  OR2X2 _069_ (
    .A(\CPIPE1s<5> ),
    .B(\CPIPE1s<3> ),
    .Y(_012_)
  );
  NOR3X1 _070_ (
    .A(_011_),
    .B(\CPIPE1s<1> ),
    .C(_012_),
    .Y(_013_)
  );
  AND2X2 _071_ (
    .A(_013_),
    .B(\CPIPE1s<7> ),
    .Y(_014_)
  );
  AND2X2 _072_ (
    .A(_010_),
    .B(_014_),
    .Y(trap)
  );
  INVX1 _073_ (
    .A(\CPIPE1s<5> ),
    .Y(_015_)
  );
  INVX1 _074_ (
    .A(\CPIPE1s<4> ),
    .Y(_016_)
  );
  NAND3X1 _075_ (
    .A(_015_),
    .B(\CPIPE1s<3> ),
    .C(_016_),
    .Y(_017_)
  );
  NOR2X1 _076_ (
    .A(_017_),
    .B(_003_),
    .Y(_018_)
  );
  OR2X2 _077_ (
    .A(trap),
    .B(_018_),
    .Y(_019_)
  );
  AND2X2 _078_ (
    .A(_019_),
    .B(_000_),
    .Y(CPIPE1flush)
  );
  OR2X2 _079_ (
    .A(\CPIPE1s<0> ),
    .B(\CPIPE1s<2> ),
    .Y(_020_)
  );
  NOR2X1 _080_ (
    .A(_020_),
    .B(\CPIPE1s<1> ),
    .Y(_021_)
  );
  AOI21X1 _081_ (
    .A(\CPIPE1s<5> ),
    .B(_021_),
    .C(\CPIPE1s<3> ),
    .Y(_022_)
  );
  NAND2X1 _082_ (
    .A(_020_),
    .B(_015_),
    .Y(_023_)
  );
  NAND3X1 _083_ (
    .A(_023_),
    .B(\CPIPE1s<7> ),
    .C(\CPIPE1s<4> ),
    .Y(_024_)
  );
  OR2X2 _084_ (
    .A(_022_),
    .B(_024_),
    .Y(_025_)
  );
  AND2X2 _085_ (
    .A(_025_),
    .B(_001_),
    .Y(_026_)
  );
  AND2X2 _086_ (
    .A(_026_),
    .B(_005_),
    .Y(DST1min1)
  );
  NAND2X1 _087_ (
    .A(\CPIPE1s<4> ),
    .B(_023_),
    .Y(_027_)
  );
  NAND2X1 _088_ (
    .A(\CPIPE1s<7> ),
    .B(_001_),
    .Y(_028_)
  );
  OAI21X1 _089_ (
    .A(\CPIPE1s<2> ),
    .B(\CPIPE1s<1> ),
    .C(\CPIPE1s<3> ),
    .Y(_029_)
  );
  NOR3X1 _090_ (
    .A(_027_),
    .B(_028_),
    .C(_029_),
    .Y(SRC2smin1)
  );
  AOI21X1 _091_ (
    .A(_014_),
    .B(_010_),
    .C(WAIT),
    .Y(lastPCload)
  );
  NAND3X1 _092_ (
    .A(_003_),
    .B(_001_),
    .C(_015_),
    .Y(_030_)
  );
  AND2X2 _093_ (
    .A(lastPCload),
    .B(_030_),
    .Y(DST2step1)
  );
  INVX1 _094_ (
    .A(_030_),
    .Y(PCstuffoncall1)
  );
  AOI21X1 _095_ (
    .A(\CPIPE1s<7> ),
    .B(_017_),
    .C(_002_),
    .Y(pALUtoPC)
  );
  INVX1 _096_ (
    .A(_028_),
    .Y(_031_)
  );
  OAI21X1 _097_ (
    .A(\CPIPE1s<0> ),
    .B(_011_),
    .C(_016_),
    .Y(_032_)
  );
  INVX1 _098_ (
    .A(_009_),
    .Y(_033_)
  );
  AND2X2 _099_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  AND2X2 _100_ (
    .A(\CPIPE1s<2> ),
    .B(\CPIPE1s<1> ),
    .Y(_035_)
  );
  OR2X2 _101_ (
    .A(\CPIPE1s<3> ),
    .B(_035_),
    .Y(_036_)
  );
  AND2X2 _102_ (
    .A(_029_),
    .B(_036_),
    .Y(_037_)
  );
  OR2X2 _103_ (
    .A(_006_),
    .B(_037_),
    .Y(_038_)
  );
  OAI21X1 _104_ (
    .A(\CPIPE1s<1> ),
    .B(_020_),
    .C(\CPIPE1s<4> ),
    .Y(_039_)
  );
  AND2X2 _105_ (
    .A(_039_),
    .B(\CPIPE1s<5> ),
    .Y(_040_)
  );
  AND2X2 _106_ (
    .A(_038_),
    .B(_040_),
    .Y(_041_)
  );
  OR2X2 _107_ (
    .A(_034_),
    .B(_041_),
    .Y(_042_)
  );
  AND2X2 _108_ (
    .A(_042_),
    .B(_031_),
    .Y(PCtoMAL1)
  );
  AND2X2 _109_ (
    .A(_031_),
    .B(_013_),
    .Y(_043_)
  );
  OR2X2 _110_ (
    .A(_043_),
    .B(PCtoMAL1),
    .Y(_044_)
  );
  AND2X2 _111_ (
    .A(_044_),
    .B(_000_),
    .Y(pPCIncr)
  );
  OAI21X1 _112_ (
    .A(_003_),
    .B(_017_),
    .C(_004_),
    .Y(_045_)
  );
  AND2X2 _113_ (
    .A(_045_),
    .B(\CPIPE1s<0> ),
    .Y(_046_)
  );
  NAND2X1 _114_ (
    .A(\CPIPE1s<3> ),
    .B(_015_),
    .Y(_047_)
  );
  INVX1 _115_ (
    .A(\CPIPE1s<1> ),
    .Y(_048_)
  );
  AOI21X1 _116_ (
    .A(\CPIPE1s<2> ),
    .B(_048_),
    .C(_006_),
    .Y(_049_)
  );
  OR2X2 _117_ (
    .A(\CPIPE1s<2> ),
    .B(\CPIPE1s<1> ),
    .Y(_050_)
  );
  AOI21X1 _118_ (
    .A(_008_),
    .B(_050_),
    .C(_003_),
    .Y(_051_)
  );
  OAI21X1 _119_ (
    .A(_047_),
    .B(_049_),
    .C(_051_),
    .Y(_052_)
  );
  OR2X2 _120_ (
    .A(_052_),
    .B(_046_),
    .Y(_053_)
  );
  AND2X2 _121_ (
    .A(_053_),
    .B(_001_),
    .Y(pALUtoMAL)
  );
  NOR3X1 _122_ (
    .A(_017_),
    .B(_003_),
    .C(_011_),
    .Y(enableINTS1)
  );
  INVX1 _123_ (
    .A(_021_),
    .Y(_054_)
  );
  NOR3X1 _124_ (
    .A(_054_),
    .B(WAIT),
    .C(_015_),
    .Y(_055_)
  );
  OR2X2 _125_ (
    .A(_055_),
    .B(_026_),
    .Y(pDATABUSintoLOADL)
  );
  NOR3X1 _126_ (
    .A(_017_),
    .B(_006_),
    .C(_028_),
    .Y(changeCWP2t)
  );
  assign changeCWP1 = PCstuffoncall1;
endmodule
